%% TEST_EXP23AE_CLOSURE_COMMON_PHY_CONTRACTS Registry and smoke preflight.
startup;
fprintf('\n============================================================\n');
fprintf('test_exp23ae_closure_common_phy_contracts\n');
fprintf('============================================================\n\n');

R=exp23aeClosureCommonPhyRegistry(); checks=0;
assert(R.expectedRuns==2100 && numel(R.seeds)==50 && ...
    isequal(R.swarmSizes,[5 10 20]) && numel(R.conditions)==7 && ...
    numel(R.clockArms)==2 && R.requiredValidationContracts==22);
fprintf('    ok   2100-row size/fault/clock matrix is frozen\n'); checks=checks+1;

B=continuousTdmaGuardBound( ...
    R.maxOffsetSec,R.maxDriftPpm,R.clockResetHorizonSec);
assert(abs(R.safeGuardSec-B.safeGuardSec)<1e-15 && ...
    R.clockResetHorizonSec==30);
fprintf('    ok   affine guard is analytical\n'); checks=checks+1;

a=runExp23aeClosureCommonPhyCell( ...
    R.seeds(1),5,'nominal-zero','zero-clock',R);
b=runExp23aeClosureCommonPhyCell( ...
    R.seeds(1),5,'nominal-zero','affine-clock',R);
assert(a.dataStateSlotExact && b.dataStateSlotExact && ...
    a.kernelCollisionFrames==0 && b.physicalCollisionFrames==0 && ...
    a.traceHash==b.traceHash && a.kernelStateHash==b.kernelStateHash && ...
    a.nativeScheduleHash==b.nativeScheduleHash && ...
    a.logicalHash==b.logicalHash && b.clockTimingConflictFree);
fprintf('    ok   paired nominal smoke maps kernel state exactly\n'); checks=checks+1;

c=runExp23aeClosureCommonPhyCell( ...
    R.seeds(1),5,'incomplete-union','affine-clock',R);
assert(~c.actualSubsetUnion && c.kernelCollisionFrames>0 && ...
    c.physicalCollisionFrames==c.kernelCollisionFrames);
fprintf('    ok   incomplete-union oracle survives PHY mapping\n'); checks=checks+1;

assert(~R.freshSeedEvidence && ~R.closedLoopClaimPermitted && ...
    ~R.onlinePlantCouplingPermitted && ~R.submissionClaimPermitted);
fprintf('    ok   integration result cannot promote downstream claims\n');
checks=checks+1;

fprintf('\ntest_exp23ae_closure_common_phy_contracts: PASS (%d checks)\n',checks);
