%% TEST_EXP21A_CONTRACTS Distributed scheduling and accounting contracts.

startup;
fprintf('\n============================================================\n');
fprintf('test_exp21a_contracts\n');
fprintf('============================================================\n\n');
checks=cell(0,2);
R=exp21aRegistry();

checks(end+1,:)={R.expectedRuns==1680 && numel(R.seeds)==30 && ...
    numel(R.cells)==8 && numel(R.arms)==7, ...
    'frozen matrix contains 30 x 8 x 7 = 1680 trajectories'};
old=exp20aRegistry();
checks(end+1,:)={isempty(intersect(R.seeds,old.formationSeeds)) && ...
    isempty(intersect(R.seeds,old.nativeSeeds)), ...
    'EXP21A development seeds are fresh relative to EXP20A'};

nominal=applyExp21ACell('n5-stressed-nominal',R.seeds(1));
clock=applyExp21ACell('n5-stressed-clock',R.seeds(1));
hidden=applyExp21ACell('n10-moderate-hidden',R.seeds(1));
checks(end+1,:)={all(nominal.exp21a.controlReach,'all') && ...
    mean(hidden.exp21a.controlReach(:))<1 && ...
    all(diag(hidden.exp21a.controlReach)), ...
    'full and two-hop control-visibility contracts differ explicitly'};

nominal.swarm.T=2.0;
trace=generateSharedMediumTrace(nominal);
trace2=generateSharedMediumTrace(nominal);
checks(end+1,:)={trace.exp21HashExact==trace2.exp21HashExact && ...
    trace.hashExact==trace2.hashExact && ...
    all(isfield(trace,{'exp21ControlChoiceU','exp21RequestLossU', ...
    'exp21ResponseLossU','exp21CommitLossU', ...
    'exp21ClockOffsetU','exp21ClockDriftU'})), ...
    'proposal, loss and clock tensors are absolute and deterministic'};

allMapped=true;
for k=1:numel(R.arms)
    try
        applyExp21AArm(nominal,R.arms(k));
    catch
        allMapped=false;
    end
end
checks(end+1,:)={allMapped,'all seven frozen arm identifiers resolve'};

arm=R.arms(strcmp({R.arms.id}, ...
    'distributed-reservation-p8p333'));
[cfg,method,label,details]=applyExp21AArm(nominal,arm);
meta=localMeta('n5-stressed-nominal',arm,1);
row=runExp21ACell(cfg,method,label,meta,trace,details);
checks(end+1,:)={row.RESERVATION_EPOCHS>=4 && ...
    row.CONTROL_FRAMES>0 && row.CONTROL_AIRTIME>0 && ...
    row.CHARGED_OFFERED_UTIL>row.OFFERED_UTIL, ...
    'reservation epochs serialize positive charged control airtime'};
checks(end+1,:)={row.CONTROL_ACCOUNTING_CLOSE==1 && ...
    row.CONTROL_RECIPIENT_SUCCESS+row.CONTROL_RECIPIENT_LOSS== ...
    row.CONTROL_RECIPIENT_ATTEMPTS, ...
    'request, response and commit recipient accounting closes'};
checks(end+1,:)={row.FIRST_CONVERGENCE_SEC<=2 && ...
    row.FINAL_FULL_UNIQUE==1 && row.LOCAL_SCHEDULE_ONLY==1 && ...
    row.FUTURE_RANDOM_READS==0 && row.RECEIVER_TRUTH_READS==0, ...
    'nominal projection converges without future or receiver-truth reads'};

clock.swarm.T=0.5;
clockTrace=generateSharedMediumTrace(clock);
staticArm=R.arms(strcmp({R.arms.id},'local-static-p8p333'));
[staticCfg,staticMethod,staticLabel,staticDetails]= ...
    applyExp21AArm(clock,staticArm);
staticRow=runExp21ACell(staticCfg,staticMethod,staticLabel, ...
    localMeta('n5-stressed-clock',staticArm,1),clockTrace,staticDetails);
checks(end+1,:)={staticRow.MAX_ABS_CLOCK_OFFSET_SEC>0 && ...
    staticRow.MAX_ABS_CLOCK_OFFSET_SEC<= ...
    R.reservation.clockOffsetMaxSec+1e-15 && ...
    staticRow.MAX_ABS_CLOCK_DRIFT_PPM>0 && ...
    staticRow.MAX_ABS_CLOCK_DRIFT_PPM<= ...
    R.reservation.clockDriftMaxPpm+1e-12, ...
    'local static TDMA consumes bounded pre-drawn clock impairment'};

lossBase=applyExp21ACell('n5-stressed-control-loss',R.seeds(2));
lossBase.swarm.T=0.6;
lossTrace=generateSharedMediumTrace(lossBase);
[lossCfg,lossMethod,lossLabel,lossDetails]= ...
    applyExp21AArm(lossBase,arm);
lossCfg.shared.serviceScheduler.controlLoss=1;
lossCfg.shared.serviceScheduler=serviceSchedulerConfig(lossCfg);
lossRow=runExp21ACell(lossCfg,lossMethod,lossLabel, ...
    localMeta('n5-stressed-control-loss',arm,1),lossTrace,lossDetails);
checks(end+1,:)={lossRow.CONTROL_RECIPIENT_ATTEMPTS>0 && ...
    lossRow.CONTROL_RECIPIENT_SUCCESS==0 && ...
    lossRow.CONTROL_RECIPIENT_LOSS==lossRow.CONTROL_RECIPIENT_ATTEMPTS && ...
    lossRow.FINAL_ASSIGNED_NODES==0, ...
    'complete control erasure prevents assignment without hidden truth'};

flags=cellfun(@logical,checks(:,1));
for k=1:size(checks,1)
    if flags(k), tag='ok'; else, tag='FAIL'; end
    fprintf('    %-4s %s\n',tag,checks{k,2});
end
if ~all(flags)
    error('test_exp21a_contracts: %d of %d checks failed.', ...
        nnz(~flags),numel(flags));
end
fprintf('\ntest_exp21a_contracts: PASS (%d checks)\n',numel(flags));


function meta=localMeta(scenario,arm,index)

meta=struct('stage','contract-smoke','scenario',scenario, ...
    'scenarioLabel',scenario,'family','EXP21A contract', ...
    'arm',arm.id,'pointIndex',index,'parameterValue',arm.periodicRateHz);

end
