%% TEST_RECEIVER_LIFTED_ROUTED_CLOSURE_KERNEL_CONTRACTS Causal relay state.
startup;

R=exp23afOnlineClosureRegistry(); N=5;
direct=false(N);
for node=1:N
    direct(mod(node,N)+1,node)=true;
    direct(mod(node-2,N)+1,node)=true;
end
oldInterference=false(N); newInterference=oldInterference;
newInterference(5,[2 3])=true; newInterference([2 3],5)=true;
neighbor=false(N); neighbor(5,1)=true;
oldGraph=buildSenderConflictGraph(neighbor,oldInterference);
newGraph=buildSenderConflictGraph(neighbor,newInterference);
slot=elcsWitnessPriorityColor(oldGraph); management=true(N);
management(1:N+1:end)=false;
packet=struct('maxDataSlots',2*N,'maxAffectedNodes',N, ...
    'prepareHeaderBytes',R.prepareHeaderBytes, ...
    'affectedEntryBytes',R.affectedEntryBytes,'claimBytes',R.claimBytes, ...
    'quietBytes',R.quietBytes,'lockProofBytes',R.lockProofBytes, ...
    'certificateHeaderBytes',R.certificateHeaderBytes, ...
    'certificateEntryBytes',R.certificateEntryBytes, ...
    'commitBytes',R.commitBytes,'revokeBytes',R.revokeBytes, ...
    'maxControlPacketBytes',R.maxControlPacketBytes);
M=buildReceiverLiftedDependencyMigration( ...
    oldGraph,newGraph,slot,5,management,packet);
C=struct('maxFrames',11,'prepareFrame',1,'transactionVersion',3, ...
    'prepareDenseRetryFrames',3,'prepareMaxBackoffFrames',1, ...
    'prepareRetryAttemptLimit',3,'claimEligibilityDelayFrames',2, ...
    'lockProofRepeatFrames',2,'claimBackoffEnabled',true, ...
    'claimDenseRetryFrames',4,'claimMaxBackoffFrames',1, ...
    'claimRetryAttemptLimit',4,'commitRetryAttemptLimit',2, ...
    'phyRateBps',250e3);
route=struct('directReach',direct, ...
    'physicalInterference',newInterference, ...
    'linkErasureProbability',.2,'repetitionsPerHop',4, ...
    'safeGuardSec',R.safeGuardSec);

T=generateReceiverLiftedRoutedClosureTrace(7,M,C,route);
assert(strcmp(T.version,'RECEIVER-LIFTED-ROUTED-CLOSURE-TRACE-v1')&& ...
    receiverLiftedRoutedClosureTraceHash(T)==T.hashExact);
kinds=fieldnames(T.linkUniform);
for k=1:numel(kinds), T.linkUniform.(kinds{k})(:)=1; end
T.hashExact=receiverLiftedRoutedClosureTraceHash(T);
O=simulateReceiverLiftedRoutedClosureMigration(M,C,T,route);
assert(strcmp(O.version,'RECEIVER-LIFTED-ROUTED-CLOSURE-KERNEL-v1')&& ...
    O.barrierClosed&&O.motionAuthorized&&O.commitReady&& ...
    O.allAffectedReactivated&&O.finalSuppressedCount==0&& ...
    O.actualSubsetOld&&O.actualSubsetUnion&& ...
    O.scheduledCollisionFrames==0&&O.routeCollisionRecipients==0&& ...
    O.crossPacketStateWrites==0&&O.futureRandomReads==0&& ...
    O.physicalControlAttempts==sum([O.bundleLog.physicalAttempts])&& ...
    O.physicalControlBytes==sum([O.bundleLog.physicalBytes])&& ...
    O.physicalControlAirtimeSec==8*O.physicalControlBytes/C.phyRateBps&& ...
    all([O.bundleLog.reservedSlotCount]<=[O.bundleLog.serialSlotCount]));

P=struct('guardSec',route.safeGuardSec,'dataBytes',R.dataBytes, ...
    'horizonSec',6.5);
Q=buildReceiverLiftedRoutedClosureContinuousSchedule(M,C,T,P,route);
Q=bindReplayDataOutcomes(Q,neighbor,Q.kernel.debug.actualGraph);
clock=struct('clockOffsetSec',linspace(-R.maxOffsetSec, ...
    R.maxOffsetSec,N)','clockDriftPpm',linspace(-R.maxDriftPpm, ...
    R.maxDriftPpm,N)','maxOffsetSec',R.maxOffsetSec, ...
    'maxDriftPpm',R.maxDriftPpm,'leadTimeSec',R.clockLeadTimeSec, ...
    'safeGuardSec',R.safeGuardSec);
A=applyDstrAffineClockSchedule(Q,clock);
assert(strcmp(Q.version, ...
    'RECEIVER-LIFTED-ROUTED-CLOSURE-CONTINUOUS-v1')&& ...
    Q.frameEndTime(end)<=P.horizonSec&& ...
    Q.expectedManagementAttempts==O.physicalControlAttempts&& ...
    Q.expectedManagementBytes==O.physicalControlBytes&& ...
    Q.expectedManagementAirtime==O.physicalControlAirtimeSec&& ...
    Q.expectedManagementRecipientCollision==0&&A.clockApplied&& ...
    A.expectedManagementAttempts==Q.expectedManagementAttempts&& ...
    A.expectedManagementBytes==Q.expectedManagementBytes&& ...
    A.expectedManagementRecipientCollision==0);

% PREPARE blackout prevents the barrier and therefore every later phase.
P=T; P.linkUniform.prepare(:)=0;
P.hashExact=receiverLiftedRoutedClosureTraceHash(P);
OP=simulateReceiverLiftedRoutedClosureMigration(M,C,P,route);
assert(~OP.barrierClosed&&~OP.motionAuthorized&&~OP.commitReady&& ...
    ~OP.allAffectedReactivated&&OP.logicalPackets.claim==0&& ...
    OP.logicalPackets.response==0&&OP.logicalPackets.commit==0);

% A leaf-specific erasure preserves successful receipt state at the other
% multicast destinations; routing is not collapsed to all-or-nothing.
prepareRecipients=receiverLiftedClosureControlRecipients( ...
    M,'prepare',M.initiator);
preparePlan=buildSlottedManagementFloodPlan(direct,newInterference, ...
    M.initiator,prepareRecipients,N-1);
remote=M.affectedNodes(M.affectedNodes~=M.initiator);
[~,order]=sort(preparePlan.depth(remote),'descend'); target=remote(order(1));
parent=preparePlan.parent(target);
partial=T;
partial.linkUniform.prepare(1:C.prepareRetryAttemptLimit, ...
    M.initiator,target,parent,:)=0;
partial.hashExact=receiverLiftedRoutedClosureTraceHash(partial);
OX=simulateReceiverLiftedRoutedClosureMigration(M,C,partial,route);
preparedCount=nnz(OX.debug.prepared(end,M.affectedNodes));
assert(~OX.barrierClosed&&preparedCount>1&&preparedCount<M.affectedCount);

% RESPONSE blackout closes the safety barrier but cannot authorize commit.
E=T; E.linkUniform.response(:)=0;
E.hashExact=receiverLiftedRoutedClosureTraceHash(E);
OE=simulateReceiverLiftedRoutedClosureMigration(M,C,E,route);
assert(OE.barrierClosed&&OE.motionAuthorized&&~OE.commitReady&& ...
    ~OE.allAffectedReactivated&&OE.logicalPackets.commit==0);

% COMMIT blackout reaches certification but cannot reactivate remote nodes.
K=T; K.linkUniform.commit(:)=0;
K.hashExact=receiverLiftedRoutedClosureTraceHash(K);
OK=simulateReceiverLiftedRoutedClosureMigration(M,C,K,route);
assert(OK.barrierClosed&&OK.motionAuthorized&&OK.commitReady&& ...
    ~OK.allAffectedReactivated&&OK.commitBudgetExhausted&& ...
    OK.logicalPackets.commit==C.commitRetryAttemptLimit);

% Trace mutation without a new hash fails closed.
bad=T; bad.linkUniform.prepare(1)=0; rejected=false;
try
    simulateReceiverLiftedRoutedClosureMigration(M,C,bad,route);
catch ME
    rejected=contains(ME.message,'trace hash');
end
assert(rejected);

fprintf('test_receiver_lifted_routed_closure_kernel_contracts: PASS\n');
