%% TEST_TCNS_R2_5_PERSISTED_WITNESS_REPLAY Independent artifact replay.

startup;
fprintf('\n=== TCNS R2.5 persisted witness replay checks ===\n\n');

testPath = mfilename('fullpath');
repoRoot = fileparts(fileparts(testPath));
root = fullfile(repoRoot,'results','tcns_r2_generalization_validation');
r2Id = strtrim(fileread(fullfile(root,'LATEST.txt')));
S = load(fullfile(root,r2Id,'workspace.mat'),'cfg','witness');
W = S.witness;
assert(W.actionCount==10, ...
    'R25WitnessReplay: persisted R2 catalog does not contain ten actions.');

options = struct('informationTolerance',1e-9, ...
    'reachabilityTolerance',1e-9,'responseTolerance',1e-9, ...
    'oracleTolerance',1e-9,'signTolerance',1e-12, ...
    'saturationMarginTolerance',1e-6);
for a = 1:W.actionCount
    persisted = W.witnessTable(a,:);
    detail = W.details{a};
    epsilon = W.options.initialSignHalfSeparation;
    uMinus = detail.uCenter-epsilon*detail.direction;
    uPlus = detail.uCenter+epsilon*detail.direction;
    leaderVelocity = reshape(detail.baseRun.finalLeader.vel,1,3);
    minusRun = tcnsInformationLimitsReplayWitness( ...
        S.cfg,W.horizonSamples,W.delaySamples,persisted.linkClass, ...
        persisted.receiver,persisted.sender,uMinus,leaderVelocity, ...
        persisted.historyLength);
    plusRun = tcnsInformationLimitsReplayWitness( ...
        S.cfg,W.horizonSamples,W.delaySamples,persisted.linkClass, ...
        persisted.receiver,persisted.sender,uPlus,leaderVelocity, ...
        persisted.historyLength);
    verdict = tcnsR25ValidateWitnessPair(minusRun,plusRun,options);
    assert(verdict.pass, ...
        'R25WitnessReplay: persisted action %s fails: %s.', ...
        persisted.actionId,verdict.failureReason);
    assert(abs(minusRun.oracleValue-persisted.qMinus)<1e-12 && ...
        abs(plusRun.oracleValue-persisted.qPlus)<1e-12, ...
        'R25WitnessReplay: direct value does not reproduce persisted data.');
    assert(abs(norm(minusRun.commandCorrection,2)-0.01)<1e-12 && ...
        abs(norm(plusRun.commandCorrection,2)-0.01)<1e-12, ...
        'R25WitnessReplay: candidate correction is not the frozen actual value.');
end

% The validator must reject intentional sender-history corruption.
badInformation = plusRun;
badInformation.senderObservation(1) = ...
    badInformation.senderObservation(1)+1e-7;
verdict = tcnsR25ValidateWitnessPair(minusRun,badInformation,options);
assert(~verdict.pass && contains(verdict.failureReason, ...
    "INFORMATION_MISMATCH"), ...
    'R25WitnessReplay: information corruption was not rejected.');

% It must independently reject an intentional fixed-response corruption.
badResponse = plusRun;
badResponse.actionResponse(1) = badResponse.actionResponse(1)+1e-7;
verdict = tcnsR25ValidateWitnessPair(minusRun,badResponse,options);
assert(~verdict.pass && contains(verdict.failureReason, ...
    "RESPONSE_MISMATCH"), ...
    'R25WitnessReplay: response corruption was not rejected.');

fprintf('  independently replayed actions  %d / %d\n',W.actionCount,W.actionCount);
fprintf('  intentional information fault   rejected\n');
fprintf('  intentional response fault      rejected\n');
fprintf('test_tcns_r2_5_persisted_witness_replay: PASS\n');
