% TEST_PROBABILISTIC_SAFETY_CERTIFICATE Check Study-2 analytical bounds.

startup;

%% p-persistent contention bound and non-data-driven optimum.
model = struct( ...
    'pAccess',0.2, ...
    'dataCompetitors',4, ...
    'ackCompetitors',4, ...
    'dataOpportunities',2, ...
    'ackOpportunities',2, ...
    'dataResidualLoss',0.1, ...
    'ackResidualLoss',0.1);

atOptimum = blockServiceLowerBound(model);
assert(abs(atOptimum.recommendedPData-0.2) < 1e-12, ...
    'Worst-case five-contender access should give p*=1/5.');
assert(atOptimum.qConfirmedBlock > 0, ...
    'Interior p-access with finite competitors should give a positive bound.');
assert(atOptimum.qConfirmedBlock <= atOptimum.qDataBlock, ...
    'End-to-end confirmation cannot exceed DATA success in this certificate.');

lowPModel = model;
lowPModel.pAccess = 0.1;
highPModel = model;
highPModel.pAccess = 0.4;
assert(atOptimum.qConfirmedBlock > ...
    blockServiceLowerBound(lowPModel).qConfirmedBlock, ...
    'Analytical p*=1/(c+1) should improve on p=0.1 for c=4.');
assert(atOptimum.qConfirmedBlock > ...
    blockServiceLowerBound(highPModel).qConfirmedBlock, ...
    'Analytical p*=1/(c+1) should improve on p=0.4 for c=4.');

implosion = model;
implosion.pAccess = 1;
implosionBound = blockServiceLowerBound(implosion);
assert(implosionBound.qConfirmedBlock == 0, ...
    'Synchronous p=1 contenders must expose a zero collision-free bound.');

moreData = model;
moreData.dataOpportunities = 3;
assert(blockServiceLowerBound(moreData).qDataBlock ...
    > atOptimum.qDataBlock, ...
    'More guaranteed recovery opportunities should improve the DATA bound.');

%% Finite-horizon composition in a zero-disturbance diagnostic cell.
cfg = defaultConfig();
motion = struct( ...
    'maxVelocity',0, ...
    'maxAcceleration',0, ...
    'maxLeaderAcceleration',0, ...
    'maxLeaderAccelEstimateError',0);
service = struct('qConfirmed',0.9);
analysis = struct( ...
    'blockLength',0.1, ...
    'failureRunLength',3, ...
    'horizon',1.0, ...
    'evaluationStart',0, ...
    'initialStateNorm',0, ...
    'safeDistance',0.25, ...
    'targetFailureProbability',0.1);

safe = finiteHorizonSafetyCertificate(cfg,motion,service,analysis);
assert(safe.deterministicCondition, ...
    'Zero-state/zero-motion diagnostic should pass the geometric condition.');
assert(safe.leaderStepResidualBound == 0 && safe.sampledInputBound == 0, ...
    'Zero-motion diagnostic should have zero sampled disturbance input.');
assert(safe.safetyFailureUpperBound < analysis.targetFailureProbability, ...
    'High-q diagnostic should meet the declared finite-horizon target.');
assert(safe.meetsTarget, ...
    'Certificate should report that the high-q diagnostic meets target.');

motionLeader = motion;
motionLeader.maxLeaderAcceleration = 1;
leaderDriven = finiteHorizonSafetyCertificate( ...
    cfg,motionLeader,service,analysis);
expectedStepResidual = sqrt(cfg.swarm.N-1)*0.5*cfg.swarm.dt^2;
assert(abs(leaderDriven.leaderStepResidualBound-expectedStepResidual) < 1e-14, ...
    'Analytic-leader semi-implicit position residual bound is incorrect.');
assert(abs(leaderDriven.accelerationStepIncrementBound ...
    -cfg.swarm.dt^2*leaderDriven.disturbanceBound) < 1e-14, ...
    'Acceleration disturbance was not converted to h^2 position increment.');

servicePoor = struct('qConfirmed',0);
poor = finiteHorizonSafetyCertificate(cfg,motion,servicePoor,analysis);
assert(poor.ageViolationUpperBound == 1 && ~poor.meetsTarget, ...
    'q=0 must not yield a probabilistic safety certificate.');

analysisImpossible = analysis;
analysisImpossible.safeDistance = safe.desiredMinSeparation;
impossible = finiteHorizonSafetyCertificate( ...
    cfg,motion,service,analysisImpossible);
assert(~impossible.geometryFeasible && ~impossible.meetsTarget, ...
    'Required separation at desired spacing must be geometrically infeasible.');

fprintf(['test_probabilistic_safety_certificate: PASS ' ...
    '(service bound, p optimum, finite horizon)\n']);
