%% TEST_EXP18B_SCIENTIFIC_AUDIT_CONTRACTS Post-hoc audit semantics.

startup;
fprintf('\n============================================================\n');
fprintf('test_exp18b_scientific_audit_contracts\n');
fprintf('============================================================\n\n');

checks={ ...
    strcmp(classifyTwoMetricRoute(-2,-1,-4,-0.5), ...
    'PIGGYBACK_DOMINATES'), ...
    'two negative intervals classify piggyback dominance'; ...
    strcmp(classifyTwoMetricRoute(0.1,1,0.2,2), ...
    'ADAPTIVE_DOMINATES'), ...
    'two positive intervals classify adaptive dominance'; ...
    strcmp(classifyTwoMetricRoute(-2,-1,-0.2,0.3), ...
    'MIXED_OR_UNRESOLVED'), ...
    'mixed interval signs do not manufacture dominance'};

invalid=false;
try
    classifyTwoMetricRoute(1,-1,0,1);
catch
    invalid=true;
end
checks(end+1,:)={invalid,'invalid interval order is rejected'};

runDir=fullfile(projectRoot(),'results','exp18b_preregistered_holdout', ...
    '2026-08-31_152137');
A=analyzeExp18BScientificAudit(runDir);
checks(end+1,:)={height(A.routeValue)==20 && ...
    height(A.serviceScreen)==20 && height(A.accessIsolation)==10, ...
    'frozen audit covers every context/MAC and ALOHA access pair'};
checks(end+1,:)={strcmp(A.verdict.status, ...
    'CURRENT_CANDIDATE_NOT_SUBMISSION_READY') && ...
    ~A.verdict.confirmatoryClaimAdded && ...
    ~A.verdict.standaloneAckAsPrimaryNoveltyPermitted, ...
    'post-hoc audit cannot add a confirmatory or ACK-selector claim'};
checks(end+1,:)={A.verdict.feasibleAlohaCells==3 && ...
    A.verdict.feasibleAlohaPiggybackDominates==3 && ...
    A.verdict.feasibleAlohaAdaptiveDominates==0 && ...
    A.verdict.candidateMisroutesResolvedFeasibleAloha==3, ...
    'all feasible ALOHA cells expose the selected adaptive-route failure'};
checks(end+1,:)={A.verdict.screenFalsePositiveCellMeans==0 && ...
    A.verdict.screenConservativeFalseNegativeCellMeans==1, ...
    'screen remains sufficient but not necessary at cell-mean level'};
checks(end+1,:)={~A.verdict.registeredH8H9CleanAccessIsolation && ...
    A.verdict.descriptiveMatchedAccessRepairN10Collision && ...
    A.verdict.descriptiveMatchedAccessRepairN10Load, ...
    'registered bundled contrast is separated from descriptive access isolation'};

flags=cellfun(@logical,checks(:,1));
for k=1:size(checks,1)
    if flags(k), tag='ok'; else, tag='FAIL'; end
    fprintf('    %-4s %s\n',tag,checks{k,2});
end
if ~all(flags)
    error('test_exp18b_scientific_audit_contracts: %d/%d failed.', ...
        nnz(~flags),numel(flags));
end
fprintf('\ntest_exp18b_scientific_audit_contracts: PASS (%d checks)\n', ...
    numel(flags));
