%% TEST_TCNS_CENTRALIZED_STATE_ORACLE O1 value and causal scheduler contracts.

startup;

fprintf('\n=== TCNS centralized online-oracle checks ===\n\n');

[cfg,~] = tcnsGate6Scenario(27020001,'S1');
frozenArms = tcnsO1FrontierArms([1 10],[0 1e-3], ...
    cfg.swarm.dt,25);
assert(numel(frozenArms)==4 && ...
    all([frozenArms(1:2).kind]=="periodic") && ...
    all([frozenArms(3:4).kind]=="centralized-state-oracle") && ...
    isequal([frozenArms(3:4).oracleLambda],[0 1e-3]), ...
    'CentralizedOracle: arm construction contract failed.');
leader = leaderReference(0);
P = cfg.swarm.initialPositions;
V = cfg.swarm.initialVelocities;
net = initQueuedNetworkState(P,V,leader,cfg);

% Excite one current receiver residual without introducing any future data.
[i,j] = find(cfg.swarm.A>0,1,'first');
net.Pij(i,j,1) = net.Pij(i,j,1)-0.2;
H = 25;
Q = tcnsCentralizedStateOracleValue(P,V,leader,net,0,cfg,H);

assert(Q.centralizedStateOracle && Q.onlineNonanticipative && ...
    Q.usesCurrentReceiverTruth && ~Q.usesFutureChannelOutcome && ...
    ~Q.usesFutureDisturbance && ~Q.usesFutureFormationChange && ...
    ~Q.usesFutureTrajectory, ...
    'CentralizedOracle: information-privilege metadata is incorrect.');
assert(Q.horizonSamples==H && Q.delaySamples>=0 && ...
    all(isfinite(Q.predictedCommandMagnitude),'all') && ...
    Q.predictedSaturationFraction>=0 && ...
    Q.predictedSaturationFraction<=1, ...
    'CentralizedOracle: prediction metadata is invalid.');

G = Q.ordinaryActionResponse{i,j};
m = cfg.swarm.N-1;
direct = Q.successProbability*(sum(Q.baselineResponse.^2,'all') - ...
    sum((Q.baselineResponse+G).^2,'all'))/m;
decomposed = Q.ordinaryCrossContribution(i,j) - ...
    Q.ordinaryIsolatedResponseEnergy(i,j);
assert(abs(Q.ordinaryValue(i,j)-direct)<1e-13 && ...
    abs(Q.ordinaryValue(i,j)-decomposed)<1e-13, ...
    'CentralizedOracle: Gate-3 cross-term decomposition drifted.');

% The value calculation itself must have no channel-realization handle.
valueSource = fileread(which('tcnsCentralizedStateOracleValue'));
for forbidden = ["dropMask","lossU","jitterZ","netTrace"]
    assert(~contains(valueSource,forbidden), ...
        'CentralizedOracle: value utility contains forbidden token %s.', ...
        forbidden);
end

runCfg = cfg;
runCfg.swarm.T = 2;
runCfg.centralizedStateOracle = struct( ...
    'lambda',0,'horizonSamples',H);
outA = simSwarmCentralizedStateOracle(runCfg);
outB = simSwarmCentralizedStateOracle(runCfg);

assert(outA.centralizedStateOracleActive && ...
    strcmp(outA.centralizedStateOracleLabel,'centralized_state_oracle') && ...
    outA.onlineNonanticipative && ~outA.usesFutureChannelOutcome && ...
    ~outA.usesFutureDisturbance && ~outA.usesFutureFormationChange && ...
    ~outA.usesFutureTrajectory, ...
    'CentralizedOracle: simulator privilege metadata is incorrect.');
assert(outA.txCount==outA.oracleSendCount && ...
    outA.ackCountLog(end)==0 && ...
    height(outA.oracleActions)==outA.oracleSendCount && ...
    all(outA.oracleActions.attempted) && ...
    all(outA.oracleActions.predictedValue>runCfg.centralizedStateOracle.lambda), ...
    'CentralizedOracle: action/accounting contract failed.');
assert(all(abs(outA.oracleActions.predictedValue - ...
    (outA.oracleActions.predictedCrossContribution - ...
     outA.oracleActions.predictedIsolatedEnergy))<1e-13), ...
    'CentralizedOracle: logged cross-term decomposition drifted.');
accepted = outA.oracleActions.accepted;
assert(any(accepted) && ...
    all(outA.oracleActions.positionResidualAfter_m(accepted)<1e-12) && ...
    all(outA.oracleActions.velocityResidualAfter_mps(accepted)<1e-12), ...
    'CentralizedOracle: accepted packets do not match receiver truth.');
assert(outA.oracleUsefulDeliveryCount==nnz(accepted) && ...
    outA.oracleFailedTransmissionCount==nnz(outA.oracleActions.dropped) && ...
    outA.oracleNoInformationAttemptCount==height(outA.oracleActions)-nnz(accepted), ...
    'CentralizedOracle: delivery diagnostics are inconsistent.');

for field = {'P','V','A','txCountLog','broadcastCountLog', ...
        'oracleSendCountLog','oracleStepMaxValueLog', ...
        'oraclePredictedSaturationFractionLog','oracleActions'}
    name = field{1};
    assert(isequaln(outA.(name),outB.(name)), ...
        'CentralizedOracle: deterministic replay changed out.%s.',name);
end

silentCfg = runCfg;
silentCfg.centralizedStateOracle.lambda = 1e6;
silent = simSwarmCentralizedStateOracle(silentCfg);
assert(silent.txCount==0 && silent.oracleSendCount==0 && ...
    isempty(silent.oracleActions) && silent.ackCountLog(end)==0, ...
    'CentralizedOracle: a prohibitive value threshold was not silent.');
assert(silent.traceHashExact==outA.traceHashExact, ...
    'CentralizedOracle: lambda sweep did not preserve the channel trace.');

runScenario = struct('id','S1','name','test-static', ...
    'evaluationStart_s',0.5,'eventWindows_s',[1 1.5], ...
    'performanceWindows_s',[0.5 2]);
arm = struct('id',"O1TEST",'family',"Centralized state oracle", ...
    'label',"centralized_state_oracle", ...
    'kind',"centralized-state-oracle",'parameterName',"lambda", ...
    'parameterValue',0,'period_s',NaN,'epsilon_m',NaN, ...
    'retry_s',NaN,'oracleLambda',0,'oracleHorizonSamples',H);
[frontierRow,frontierOut] = runTcnsFrontierCell( ...
    runCfg,arm,runScenario);
assert(~frontierRow.failed && ...
    frontierRow.oracleLambda==arm.oracleLambda && ...
    frontierRow.oracleHorizonSamples==H && ...
    frontierRow.ackCount==0 && ...
    frontierRow.oracleSendCount==frontierOut.oracleSendCount && ...
    isfinite(frontierRow.evaluationCost025PerChannel_Hz) && ...
    isfinite(frontierRow.primaryFormationRMSE_m) && ...
    isfinite(frontierRow.oracleEventAllocationRatio), ...
    'CentralizedOracle: frontier-runner integration failed.');

fprintf('  direct/decomposed q residual                 %.3e\n', ...
    abs(direct-decomposed));
fprintf('  deterministic online actions                %d\n',outA.oracleSendCount);
fprintf('  prohibitive-threshold DATA/ACK               %d / %d\n', ...
    silent.txCount,silent.ackCountLog(end));
fprintf('test_tcns_centralized_state_oracle: PASS\n');
