%% TEST_EXP23AN_FULL_DETECTABILITY_ROUTING_CONTRACTS Independent collision.
startup;

R=exp23anFullDetectabilityRoutingRegistry();
P0=exp23ajRoutedManagementRegistry();
assert(strcmp(R.version,'EXP23AN-FULL-DETECTABILITY-ROUTING-v1')&& ...
    R.detectabilityRepair&&R.expectedDetectabilityAuditRows==94&& ...
    R.expectedLegacyInvalidStructuralRoutes==30&& ...
    R.expectedLegacyInvalidSemanticRoutes==5&& ...
    R.requiredValidationContracts==19);
assert(isempty(intersect(R.monteCarloSeeds,P0.monteCarloSeeds))&& ...
    strcmp(R.repairedSimulatorVersion, ...
    'REPEATED-HOP-MANAGEMENT-FLOOD-REPLAY-v3'));

N=5; reach=false(N); reach(2,1)=true; reach(3,1)=true;
reach(4,2)=true; reach(4,3)=true; reach(5,3)=true;
P=buildSlottedManagementFloodPlan(reach,false(N),1,[4 5],2);
A=auditLegacyManagementFloodDetectability(P);
assert(P.senderConflictGraph(2,3)&& ...
    P.transmitterSlot(2)~=P.transmitterSlot(3)&&A.legacyInvalid&& ...
    A.legacyOracleCollisionRecipients>=1&&A.currentValid);
O=simulateRepeatedHopManagementFlood(P,ones(N),.2,1,40,250e3,.001);
assert(strcmp(O.version,R.repairedSimulatorVersion)&& ...
    O.allRecipientsDelivered&&O.collisionRecipients==0&& ...
    O.offeredAirtimeSec==8*O.bytes/250e3);

fprintf('test_exp23an_full_detectability_routing_contracts: PASS\n');
