%% TEST_EXP23AK_ROUTED_ACCOUNTING_CONTRACTS Frozen repair registry.
startup;

R=exp23akRoutedAccountingRegistry();
assert(strcmp(R.version,'EXP23AK-ROUTED-INTEGER-ACCOUNTING-v1')&& ...
    strcmp(R.repairedSimulatorVersion, ...
    'REPEATED-HOP-MANAGEMENT-FLOOD-REPLAY-v2'));
assert(R.parentGatesPassed==15&&R.parentGatesTotal==17&& ...
    isequal(R.parentFailedGates, ...
    {'integer_bytes_and_derived_airtime', ...
    'semantic_routes_reliable_and_accounted'}));
assert(R.expectedStructuralRows==210&&R.expectedSemanticRows==25&& ...
    R.expectedRandomCells==18&&numel(R.randomReplaySeeds)==18&& ...
    R.expectedRandomRows==36000&& ...
    R.randomReplayTrialsPerCell==2000&& ...
    R.randomReplayRepetitionsPerHop==1&& ...
    R.requiredValidationContracts==10);
assert(~R.managementRelayingValidated&& ...
    ~R.repeatedOnlineRenewalValidated&&~R.freshSeedEvidence&& ...
    ~R.robustnessClaimPermitted&&~R.submissionClaimPermitted);

N=4; reach=false(N); reach(2,1)=true; reach(3,2)=true; reach(4,3)=true;
P=buildSlottedManagementFloodPlan(reach,reach|reach',1,2:4,3);
O=simulateRepeatedHopManagementFlood(P,ones(N,N,3),.2,3, ...
    72,R.phyRateBps,R.safeGuardSec);
assert(strcmp(O.version,R.repairedSimulatorVersion)&& ...
    O.bytes==O.attempts*72&& ...
    O.offeredAirtimeSec==8*O.bytes/R.phyRateBps);

fprintf('test_exp23ak_routed_accounting_contracts: PASS\n');
