%% TEST_EXP23AQ_ROUTED_STATE_MACHINE_CONFIRMATION_CONTRACTS Fresh lineage.
startup;

R=exp23aqRoutedStateMachineConfirmationRegistry();
assert(strcmp(R.version, ...
    'EXP23AQ-ROUTED-STATE-MACHINE-CONFIRMATION-v1')&& ...
    strcmp(R.supersededStatus, ...
    'SUPERSEDED_BY_CONTINUOUS_VERSION_IDENTITY_AUDIT')&& ...
    strcmp(R.supersededReasonCode, ...
    'CONTINUOUS_VERSION_HASH_NOT_ASSERTED')&& ...
    R.normalTrials==500&&numel(unique(R.normalSeeds))==500&& ...
    R.normalSeeds(1)==16095702&&R.normalSeeds(end)==16096201&& ...
    ~ismember(R.faultSeed,R.normalSeeds)&&R.faultSeed==16096202&& ...
    R.requiredValidationContracts==19&&strcmp(R.continuousVersion, ...
    'RECEIVER-LIFTED-ROUTED-CLOSURE-CONTINUOUS-v1'));
assert(~R.managementRelayingValidated&& ...
    ~R.closedLoopManagementRelayingValidated&& ...
    ~R.repeatedOnlineRenewalValidated&&~R.freshSeedEvidence&& ...
    ~R.robustnessClaimPermitted&&~R.submissionClaimPermitted);

fprintf('test_exp23aq_routed_state_machine_confirmation_contracts: PASS\n');
