%% TEST_RECEIVER_LIFTED_ROUTED_MISSION_SCHEDULE_CONTRACTS Embedding smoke.
startup;

R=exp23arRoutedPlantClosedLoopRegistry();
I=exp23aiIntegerAccountingRegistry();
[~,context]=runExp23afOnlineClosureSeed(R.smokeSeed,I);
M=context.geometry.migration;
C=struct('maxFrames',R.transactionFrames,'prepareFrame',1, ...
    'transactionVersion',R.transactionVersion, ...
    'prepareDenseRetryFrames',R.prepareAttempts, ...
    'prepareMaxBackoffFrames',1, ...
    'prepareRetryAttemptLimit',R.prepareAttempts, ...
    'claimEligibilityDelayFrames',R.claimEligibilityDelayFrames, ...
    'lockProofRepeatFrames',R.evidencePrefixAttempts, ...
    'claimBackoffEnabled',true, ...
    'claimDenseRetryFrames',R.claimAttempts, ...
    'claimMaxBackoffFrames',1, ...
    'claimRetryAttemptLimit',R.claimAttempts, ...
    'commitRetryAttemptLimit',R.commitAttempts,'phyRateBps',R.phyRateBps);
route=struct('directReach',logical(context.neighborGraph), ...
    'physicalInterference',context.geometry.oldPhysicalGraph| ...
        context.geometry.proposedPhysicalGraph, ...
    'linkErasureProbability',R.linkErasureProbability, ...
    'repetitionsPerHop',R.repetitionsPerHop,'safeGuardSec',R.safeGuardSec);
T=generateReceiverLiftedRoutedClosureTrace( ...
    R.smokeSeed+R.routeSeedOffset,M,C,route);
kinds=fieldnames(T.linkUniform);
for k=1:numel(kinds), T.linkUniform.(kinds{k})(:)=1; end
T.hashExact=receiverLiftedRoutedClosureTraceHash(T);
Ptxn=struct('guardSec',R.safeGuardSec,'dataBytes',R.dataBytes, ...
    'horizonSec',R.postRequestTimeBudgetSec);
native=buildReceiverLiftedRoutedClosureContinuousSchedule(M,C,T,Ptxn,route);
P=struct('missionSec',R.missionSec,'requestTimeSec',R.requestTimeSec, ...
    'emergencyEnabled',true,'emergencySlots',R.emergencySlots);
Q=embedReceiverLiftedRoutedClosureMissionSchedule(native,M,P);

assert(strcmp(Q.version,R.missionEmbeddingVersion)&& ...
    Q.transactionMissionEmbeddingExact&&Q.horizonSec==R.missionSec&& ...
    min(Q.controlStartTime)>=R.requestTimeSec&& ...
    Q.expectedManagementAttempts==native.expectedManagementAttempts&& ...
    Q.expectedManagementBytes==native.expectedManagementBytes&& ...
    Q.emergencyData.mappingExact&& ...
    Q.emergencyData.opportunities==Q.emergencyData.suppressedDemand&& ...
    any(Q.missionFrameKind=="pre")&&any(Q.missionFrameKind=="post"));

fprintf('test_receiver_lifted_routed_mission_schedule_contracts: PASS\n');

