%% TEST_EXP21D_BOUNDARY_CONTRACTS Frozen Stage-C mechanism mappings.

startup;
fprintf('\n============================================================\n');
fprintf('test_exp21d_boundary_contracts\n');
fprintf('============================================================\n\n');
checks=cell(0,2);
R=exp21dBoundaryRegistry();

checks(end+1,:)={R.expectedRuns==360 && numel(R.seeds)==30 && ...
    numel(R.cells)==2 && numel(R.arms)==6 && ...
    ~R.policyOptimizationAllowed && ~R.newMethodPromotionAllowed && ...
    ~R.submissionClaimPermitted, ...
    'registry freezes 360 falsification rows without promotion rights'};

base=applyExp21dBoundaryCell(R.cells(1).id,R.seeds(1));
base.swarm.T=0.60;
base.shared.evalStart=0;
base.sixdof.enable=false;
T=generateExp21dDstrTrace(base.net.seed,base.swarm.N,R);
C0=buildExp21dBoundaryKernelConfig(base,R,'zero');
CL=buildExp21dBoundaryKernelConfig(base,R,'beacon-loss');
CR=buildExp21dBoundaryKernelConfig(base,R,'restricted-management');
CC=buildExp21dBoundaryKernelConfig(base,R,'churn-rejoin');
checks(end+1,:)={C0.dataErasureProbability==0 && ...
    CL.dataErasureProbability==R.beaconErasureProbability && ...
    isequal(CL.managementReach,C0.managementReach) && ...
    isequal(CR.managementReach,CR.neighborGraph) && ...
    CC.churnEnabled && CC.churnFrame==R.churnFrame, ...
    'loss, visibility and rejoin arms change only declared kernel factors'};

lossArm=R.arms(strcmp({R.arms.id},R.lossNativeArm));
[lossCfg,lossMethod,lossLabel,lossDetails,lossQ]= ...
    applyExp21dBoundaryArm(base,lossArm,T);
trace=generateSharedMediumTrace(lossCfg);
meta=struct('stage',R.stage,'scenario',R.cells(1).id, ...
    'scenarioLabel',R.cells(1).label,'family','boundary-contract', ...
    'arm',lossArm.id,'pointIndex',1,'parameterValue', ...
    R.beaconErasureProbability);
[lossRow,~]=runExp21dBoundaryCell(lossCfg,lossMethod,lossLabel, ...
    meta,trace,lossDetails,lossQ,lossArm);
checks(end+1,:)={lossQ.expectedCompletedDataRecipientErasure>0 && ...
    lossRow.DSTR_DATA_OUTCOME_MISMATCHES==0 && ...
    lossRow.DSTR_OBSERVED_DATA_RECIPIENT_ERASURE== ...
        lossRow.DSTR_EXPECTED_DATA_RECIPIENT_ERASURE && ...
    lossRow.DATA_RECIPIENT_SUCCESS+lossRow.DATA_RECIPIENT_LOSS+ ...
        lossRow.TERMINAL_DATA_INFLIGHT== ...
        lossRow.DATA_RECIPIENT_ATTEMPTS, ...
    'beacon erasure reaches controller and right-censor accounting closes'};

warmArm=R.arms(strcmp({R.arms.id},R.lossWarmArm));
[warmCfg,warmMethod,~,~,warmQ]=applyExp21dBoundaryArm(base,warmArm,T);
warmTrace=generateSharedMediumTrace(warmCfg);
warmOut=simSwarmSharedMedium(warmCfg,warmMethod,warmTrace);
checks(end+1,:)={warmQ.firstConvergenceTimeSec==0 && ...
    isempty(warmQ.controlGroupStartTime) && ...
    warmQ.expectedCompletedDataRecipientErasure>0 && ...
    warmOut.serviceScheduler.dstrDataOutcomeMismatchCount==0 && ...
    warmOut.serviceScheduler.dstrDataRecipientErasureObserved== ...
        warmQ.expectedCompletedDataRecipientErasure, ...
    'loss-warm arm isolates physical erasure without acquisition traffic'};

restrictedArm=R.arms(strcmp({R.arms.id},R.restrictedArm));
[~,~,~,~,restrictedQ]=applyExp21dBoundaryArm(base,restrictedArm,T);
checks(end+1,:)={restrictedQ.kernelTraceHash==lossQ.kernelTraceHash && ...
    restrictedQ.kernel.managementAttempts>=0 && ...
    restrictedQ.prefixFrameAgreement== ...
        (restrictedQ.maxPrefixFrameDisagreement==0), ...
    'restricted reach retains paired draws and explicit composability flag'};

churnArm=R.arms(strcmp({R.arms.id},R.churnArm));
[~,~,~,~,churnQ]=applyExp21dBoundaryArm(base,churnArm,T);
checks(end+1,:)={churnQ.kernelTraceHash==lossQ.kernelTraceHash && ...
    churnQ.kernel.churnApplied && ...
    isfinite(churnQ.kernel.recoveryFrame), ...
    'state-loss arm activates and rejoins through the normal kernel path'};

flags=cellfun(@logical,checks(:,1));
for k=1:size(checks,1)
    if flags(k), tag='ok'; else, tag='FAIL'; end
    fprintf('    %-4s %s\n',tag,checks{k,2});
end
if ~all(flags)
    error('test_exp21d_boundary_contracts: %d of %d failed.', ...
        nnz(~flags),numel(flags));
end
fprintf('\ntest_exp21d_boundary_contracts: PASS (%d checks)\n', ...
    numel(flags));

