%% TEST_EXP14_INFRASTRUCTURE Frozen holdout design without consuming a seed.

startup;

fprintf('\n============================================================\n');
fprintf('test_exp14_infrastructure\n');
fprintf('============================================================\n\n');

checks = cell(0,2);
R = exp14Registry();

[registryHash,registryLeaves] = configHash(R);
checks(end+1,:) = {registryHash==201658753 && registryLeaves==139, ...
    'the frozen EXP14 registry has the preregistered exact hash'};

checks(end+1,:) = {isequal(R.seeds,(14014001:14014100)') && ...
    numel(unique(R.seeds))==100 && ...
    ~any(ismember(R.seeds,13013001:13013004)) && ...
    ~any(ismember(R.seeds,25000001:25000050)), ...
    '100 holdout seeds are unique and disjoint from known development/final seeds'};

checks(end+1,:) = {R.expected.primaryFrontierRuns==9000 && ...
    R.expected.primaryMechanismRuns==1500 && ...
    R.expected.oodRuns==4800 && R.expected.totalRuns==15300, ...
    'all primary, mechanism and OOD run counts close exactly'};

expectedHashes = [103822268 103613168 101886664];
for k = 1:numel(R.scenarios)
    c = study2Exp14Config(0,R.scenarios(k).id);
    [h,nLeaf] = configHash(c);
    checks(end+1,:) = {h==expectedHashes(k) && nLeaf==102, ...
        sprintf('%s primary configuration has its frozen exact hash', ...
        R.scenarios(k).label)};
end

c = study2Exp14Config(0,'moderate');
checks(end+1,:) = {c.swarm.N==5 && strcmp(c.swarm.topology,'ring2') && ...
    c.sixdof.enable && c.sixdof.ratio==10 && ...
    strcmp(c.mac.type,'csma') && c.mac.pAccess==0.2 && ...
    strcmp(c.mac.lossModel,'gilbert-elliott') && ...
    c.mac.separateAckTrace && ...
    ceil(8*c.mac.dataBytes/c.mac.phyRateBps/c.mac.slotTime)==4, ...
    'primary plant, topology, multi-slot CSMA and burst channel are frozen'};

stationaryLoss = [R.scenarios.stationaryMeanLoss];
checks(end+1,:) = {max(abs(stationaryLoss-[0.005 0.097 0.29]))<1e-12 && ...
    all(diff(stationaryLoss)>0), ...
    'channel cells have declared stationary mean-loss ordering'};

closedFrontier = false;
try
    applyExp14FrontierPoint(c,'post-hoc-oracle',1);
catch
    closedFrontier = true;
end
checks(end+1,:) = {closedFrontier, ...
    'frontier family identifiers form a closed fail-fast interface'};

for k = 1:numel(R.frontiers)
    for q = 1:numel(R.frontiers(k).values)
        [~,method,label] = applyExp14FrontierPoint( ...
            c,R.frontiers(k).id,R.frontiers(k).values(q));
        if q==1
            checks(end+1,:) = {~isempty(method) && ~isempty(label), ...
                sprintf('%s frontier is executable at all five frozen points', ...
                R.frontiers(k).label)};
        end
    end
end

ch = applyExp14OODPoint('hidden-terminal',13013001);
checks(end+1,:) = {all(ch.mac.interferenceMatrix(:)) && ...
    any(~ch.mac.carrierSenseMatrix(:)) && ...
    all(diag(ch.mac.carrierSenseMatrix)), ...
    'hidden-terminal OOD separates sensing from physical interference'};

cr = applyExp14OODPoint('reverse-asymmetric',13013001);
piAck = cr.mac.burst.ackGoodToBad/(cr.mac.burst.ackGoodToBad+ ...
    cr.mac.burst.ackBadToGood);
ackMeanLoss = (1-piAck)*cr.mac.burst.ackGoodLoss+ ...
    piAck*cr.mac.burst.ackBadLoss;
checks(end+1,:) = {abs(ackMeanLoss-0.3633333333333333)<1e-12 && ...
    ackMeanLoss>R.scenarios(2).stationaryMeanLoss, ...
    'reverse-asymmetric OOD worsens only standalone-ACK channel marginals'};

cn20 = applyExp14OODPoint('n20-ring2',13013001);
checks(end+1,:) = {cn20.swarm.N==20 && ~cn20.sixdof.enable && ...
    isequal(size(cn20.mac.interferenceMatrix),[20 20]) && ...
    isequal(size(cn20.mac.carrierSenseMatrix),[20 20]), ...
    'N20 OOD resizes plant, topology, interference and sensing consistently'};

ce = applyExp14OODPoint('estimator-c3',13013001);
checks(end+1,:) = {ce.estimator.latency==0.050 && ...
    ce.estimator.noise.posSigma==0.03 && ...
    ce.estimator.noise.velSigma==0.05, ...
    'estimator OOD is the previously validated synthetic C3 point'};

unknownOOD = false;
try
    applyExp14OODPoint('invented-after-holdout',13013001);
catch
    unknownOOD = true;
end
checks(end+1,:) = {unknownOOD, ...
    'OOD point identifiers form a closed fail-fast interface'};

% Development-seed smoke run: validates the frozen row/6-DOF boundary without
% consuming any EXP14 holdout realization.
cs = study2Exp14Config(13013001,'moderate');
[cs,ms,ls] = applyExp14FrontierPoint(cs,'proposed',1);
ts = generateSharedMediumTrace(cs);
meta = struct('stage','smoke','scenario','moderate', ...
    'scenarioLabel','Moderate','family','Causal-Broadcast', ...
    'arm','proposed-3','pointIndex',3,'parameterValue',1);
rs = runExp14Cell(cs,ms,ls,meta,ts);
checks(end+1,:) = {isfinite(rs.RMSE) && isfinite(rs.ROLL_PEAK_DEG) && ...
    rs.DIVERGED==0 && rs.INVARIANT_VIOLATIONS==0 && ...
    rs.TRACE_HASH_EXACT==ts.hashExact && ...
    rs.CHANNEL_STATE_HASH==ts.channelStateHash, ...
    'development-seed primary smoke run satisfies the frozen row contract'};

bt = pairedBootstrapCI((1:100)',zeros(100,1),10000,14141414,100);
wi = wilsonCI(0,100);
checks(end+1,:) = {bt.complete && bt.lo>0 && bt.hi>bt.lo && ...
    wi.rate==0 && wi.lo==0 && wi.hi>0, ...
    'frozen paired-bootstrap and Wilson interval utilities expose denominators'};

flags = cellfun(@logical,checks(:,1));
for k = 1:size(checks,1)
    if flags(k), tag='ok'; else, tag='FAIL'; end
    fprintf('    %-4s %s\n',tag,checks{k,2});
end
if ~all(flags)
    error('test_exp14_infrastructure: %d of %d checks failed.', ...
        nnz(~flags),numel(flags));
end
fprintf('\ntest_exp14_infrastructure: PASS (%d checks)\n',numel(flags));
