%% TEST_TCNS_R1_THEORY_DEPTH R1 theorem-diagnostic contracts.

startup;
fprintf('\n=== TCNS R1 theory-depth checks ===\n\n');
[cfg,~] = tcnsGate6Scenario(27020001,'S1');
model = tcnsInformationLimitsModel(cfg,25,4,0);
audit = tcnsR1TheoryDepthAudit(model);

assert(height(audit.actionCatalog)==10, ...
    'R1TheoryDepth: expected all ten controller-relevant actions.');
assert(isequal(sort(audit.senderTable.sender)',1:5), ...
    'R1TheoryDepth: every actual sender must be represented.');
assert(all(audit.senderTable.missingRank>=1 & ...
    audit.senderTable.missingRank<=audit.senderTable.actionCount), ...
    'R1TheoryDepth: invalid sender-wise missing dimension.');
assert(all(audit.senderTable.allAgentsIdentifyAllValues), ...
    'R1TheoryDepth: full coalition did not identify all action values.');
assert(all(audit.rankTable.stableAcrossToleranceGrid), ...
    'R1TheoryDepth: a ten-link conclusion changed across tolerance sweep.');
assert(all(audit.rankTable.vpaNormalizedResidual>1e-12), ...
    'R1TheoryDepth: 80-digit audit did not preserve a nonzero residual.');
assert(all(audit.rankTable.augmentedRank== ...
    audit.rankTable.referenceRank+1), ...
    'R1TheoryDepth: value row did not add exactly one rank.');

ordinary = tcnsInformationLimitsDynamicWitness( ...
    cfg,25,4,'ordinary',5,1);
pin = tcnsInformationLimitsDynamicWitness( ...
    cfg,25,4,'pinned-leader',4,1);
for W = {ordinary,pin}
    qMinus = W{1}.minus.expectedValue;
    qPlus = W{1}.plus.expectedValue;
    p = qPlus/(qPlus-qMinus);
    randomized = qPlus*(-qMinus)/(qPlus-qMinus);
    deterministic = min(qPlus,-qMinus);
    assert(p>0 && p<1 && randomized>0 && deterministic>0, ...
        'R1TheoryDepth: reachable regret must be strictly positive.');
    assert(abs((1-p)*qPlus-p*(-qMinus))<1e-16, ...
        'R1TheoryDepth: randomized minimax regrets are not equalized.');
end

fprintf('  senders/actions                         %d / %d\n', ...
    height(audit.senderTable),height(audit.actionCatalog));
fprintf('  tolerance-stable link tests             %d / %d\n', ...
    nnz(audit.rankTable.stableAcrossToleranceGrid), ...
    height(audit.rankTable));
fprintf('test_tcns_r1_theory_depth: PASS\n');

