%% TEST_TCNS_AF2_CALIBRATION_ARTIFACT Frozen-result integrity checks.

startup;

root = fullfile(projectRoot(),'results', ...
    'tcns_af2_passive_ack_free_calibration');
runId = strtrim(fileread(fullfile(root,'LATEST.txt')));
runDir = fullfile(root,runId);
summary = jsondecode(fileread(fullfile(runDir,'summary.json')));
scenarios = readtable(fullfile(runDir,'scenario_summary.csv'), ...
    'TextType','string');
runs = readtable(fullfile(runDir,'run_provenance.csv'),'TextType','string');
bins = readtable(fullfile(runDir,'calibration_bins.csv'),'TextType','string');

assert(strcmp(summary.verdict,'AF2_CALIBRATION_PASS') && ...
    summary.technicalPass && summary.calibrationPass, ...
    'AF2Artifact: authoritative verdict is not PASS.');
assert(height(scenarios)==2 && ...
    isequal(sort(scenarios.scenarioId),["S2";"S6"]) && ...
    all(scenarios.pass), ...
    'AF2Artifact: scenario coverage/verdict is invalid.');
assert(all(scenarios.supportViolationCount==0) && ...
    all(scenarios.maxNormalizationResidual<=1e-12) && ...
    all(abs(scenarios.nllMinusEntropy)<=0.05) && ...
    all(abs(scenarios.brierMinusBayes)<=0.03) && ...
    all(scenarios.ECE<=0.03) && all(scenarios.MCE<=0.10), ...
    'AF2Artifact: a preregistered calibration threshold failed.');
assert(height(runs)==10 && numel(unique(runs.seed))==5 && ...
    all(runs.ackCount==0) && all(~runs.diverged) && ...
    all(runs.receiverLogPresent) && all(runs.senderFireLogPresent), ...
    'AF2Artifact: passive run provenance is invalid.');
assert(height(bins)==20 && sum(bins.count)==summary.candidateForecastCount, ...
    'AF2Artifact: calibration-bin accounting does not close.');

fprintf('  run                         %s\n',runId);
fprintf('  observations                %d\n',summary.observationCount);
fprintf('  candidate forecasts         %d\n',summary.candidateForecastCount);
fprintf('test_tcns_af2_calibration_artifact: PASS\n');

