%% TEST_EXP10_INFRASTRUCTURE
%
% Checks the EXP10 layer before any EXP10 number is believed. Each of the
% failures below would be invisible in the final results and would each
% change a conclusion:
%
%   - a transmission phase drawn per DIRECTED LINK instead of per sender
%     would break the broadcast synchronisation that is the physical
%     meaning of a periodic radio, and would manufacture an advantage for
%     the event-triggered methods out of pure accounting
%   - P10 and P20 drawing different phase realizations would make the two
%     periodic baselines incomparable to each other
%   - a phase implementation that also perturbed State-event or Causal-v3
%     would confound the phase change with the method comparison
%   - a trace hash that moved with how much traffic a policy generated
%     would mean the methods were not on a common realization at all, and
%     every paired statistic in EXP10 would be unfounded
%   - realizationHash collapsing logical inputs to zero would make the
%     link-fault and blackout hash checks pass on realizations that do
%     not match
%   - an EXP10 seed that had been used during development would make
%     EXP10 a re-test rather than a holdout validation
%
% ============================================================

startup;

fprintf('\n');
fprintf('============================================================\n');
fprintf('test_exp10_infrastructure\n');
fprintf('============================================================\n\n');

verdict = @(f) subsref({'FAIL','ok'}, struct('type','{}','subs',{{f+1}}));

base = applyTopologyConfig(defaultConfig(), 5, 'ring2');
base.swarm.normalizeConsensusDegree = false;
base.net.seed       = 25000001;
base.net.packetLoss = 0.20;
base.net.delay      = 0.08;
base.net.jitterStd  = 0;
base.net.useTrace   = true;
base.ack.useTrace   = true;
base.ack.delay      = 0.08;
base.ack.loss       = 0;
base.ack.jitterStd  = 0;
base.ack.assertInvariants = true;
base.causal.useAdaptiveScale   = true;
base.causal.useAckFeedback     = true;
base.causal.innovationPriority = true;
base.event.posThreshold = 0.05;
base.event.velThreshold = 0.10;
base.event.maxSilence   = 0.50;
base.aoiEvent.posThreshold      = 0.05;
base.aoiEvent.velThreshold      = 0.10;
base.aoiEvent.aoiThreshold      = 0.12;
base.aoiEvent.maxSilence        = 0.50;
base.aoiEvent.minInterTx        = base.swarm.dt;
base.aoiEvent.aoiMinInterTx     = 0.10;
base.aoiEvent.aoiStateScaleBase = 0.50;
base.aoiEvent.aoiStateScaleMin  = 0.20;
base.aoiEvent.aoiAdaptRange     = 1.00;
base.sixdof.enable = false;


%% ============================================================
% [1] realizationHash: the property the locked localHash lacks
%
% mod(floor(abs(v)*1e12), 1e9) is zero for every logical input, so the
% locked trace-generator formula would hash every link-fault pattern to
% the same value. The EXP10 realization set contains logical
% realizations, so this is checked directly rather than assumed.
% ============================================================

L1 = logical([1 0 0 1 0]);
L2 = logical([0 1 0 1 0]);

checks = { ...
    realizationHash(L1) ~= realizationHash(L2), ...
        'realizationHash separates two logical patterns'; ...
    realizationHash(L1) ~= 0, ...
        'a logical realization does not hash to zero'; ...
    realizationHash(L1) == realizationHash(L1), ...
        'realizationHash is deterministic'; ...
    realizationHash([1 2 3]) ~= realizationHash([3 2 1]), ...
        'realizationHash is order sensitive'; ...
    isfinite(realizationHash([1 inf -inf NaN 2])), ...
        'a non-finite entry gives a finite hash, not NaN'; ...
    realizationHash([1 inf 2]) ~= realizationHash([1 -inf 2]), ...
        '+inf and -inf are distinguished'; ...
    realizationHash(zeros(1,5)) ~= 0, ...
        'an all-zero realization does not hash to zero'};


%% ============================================================
% [2] Phase trace shape and reproducibility
% ============================================================

pA = generatePhaseTrace(base);

cB = base; cB.net.seed = 25000002;
pB = generatePhaseTrace(cB);

pA2 = generatePhaseTrace(base);

checks = [checks; { ...
    numel(pA.u) == base.swarm.N + 1, ...
        'one phase per physical sender plus one for the leader payload class'; ...
    all(pA.u >= 0 & pA.u < 1), ...
        'phaseU lies in [0,1)'; ...
    isequal(pA.u, pA2.u), ...
        'the same seed gives the same phase realization'; ...
    ~isequal(pA.u, pB.u), ...
        'a different seed gives a different phase realization'; ...
    pA.hash == pA2.hash, ...
        'the phase hash is reproducible'; ...
    pA.hash ~= pB.hash, ...
        'the phase hash separates seeds'}];


%% ============================================================
% [3] The legacy flag is inert; the new flag is default OFF
%
% cfg.net.phaseOffset never had an effect: the offsets it computed were
% never read by the transmission decision. Both branches of it must give
% the identical trajectory, which is what makes every locked result a
% genuine single-global-clock result regardless of the flag.
% ============================================================

cLegacyOff = base; cLegacyOff.net.phaseOffset = false;
cLegacyOn  = base; cLegacyOn.net.phaseOffset  = true;

oLegacyOff = simSwarm6DOF(cLegacyOff, 'P10');
oLegacyOn  = simSwarm6DOF(cLegacyOn,  'P10');

cAbsent = base;
oAbsent = simSwarm6DOF(cAbsent, 'P10');

cNewOff = base; cNewOff.net.phaseOffsetEnabled = false;
oNewOff = simSwarm6DOF(cNewOff, 'P10');

checks = [checks; { ...
    isequal(oLegacyOff.P, oLegacyOn.P), ...
        'the legacy phaseOffset flag is inert, as every locked result assumed'; ...
    isequal(oAbsent.P, oNewOff.P), ...
        'phaseOffsetEnabled absent equals phaseOffsetEnabled false'; ...
    isnan(oNewOff.phaseHash), ...
        'no phase hash is reported when phase is off'; ...
    all(oNewOff.senderFireCount(2:end) == oNewOff.senderFireCount(1)), ...
        'with phase off every sender fires on one clock'}];


%% ============================================================
% [4] Phase on: per SENDER, not per link, and not inert
% ============================================================

cPhase = base; cPhase.net.phaseOffsetEnabled = true;

oPhase   = simSwarm6DOF(cPhase, 'P10');
oPhase20 = simSwarm6DOF(cPhase, 'P20');

% Direct unit test of the fire mask: only the named sender's payload may
% enter a queue. This is the check that would catch a per-link phase.
leader = leaderReference(0);
netU = initQueuedNetworkState( ...
    cPhase.swarm.initialPositions, cPhase.swarm.initialVelocities, leader, cPhase);

cLossless = cPhase;
cLossless.net.packetLoss = 0;
cLossless.net.delay = 0;

mask = false(cPhase.swarm.N + 1, 1);
mask(3) = true;

netS3 = enqueueNetworkPackets(netU, ...
    cPhase.swarm.initialPositions, cPhase.swarm.initialVelocities, ...
    leader, 0.10, cLossless, [], 0, mask);

grewFrom3 = 0;
grewFromOther = 0;

for i = 1:cPhase.swarm.N
    for j = 1:cPhase.swarm.N
        if isempty(netS3.queue{i,j})
            continue;
        end
        if j == 3
            grewFrom3 = grewFrom3 + 1;
        else
            grewFromOther = grewFromOther + 1;
        end
    end
end

leaderGrew3 = nnz(~cellfun(@isempty, netS3.leaderQueue));

maskLeader = false(cPhase.swarm.N + 1, 1);
maskLeader(end) = true;

netSL = enqueueNetworkPackets(netU, ...
    cPhase.swarm.initialPositions, cPhase.swarm.initialVelocities, ...
    leader, 0.10, cLossless, [], 0, maskLeader);

neighbourGrewL = 0;
for i = 1:cPhase.swarm.N
    for j = 1:cPhase.swarm.N
        neighbourGrewL = neighbourGrewL + ~isempty(netSL.queue{i,j});
    end
end

leaderGrewL = nnz(~cellfun(@isempty, netSL.leaderQueue));

nRecv3 = nnz(cPhase.swarm.A(:,3));

checks = [checks; { ...
    grewFrom3 == nRecv3, ...
        'a firing sender reaches every one of its receivers in the same step'; ...
    grewFromOther == 0, ...
        'a sender whose clock has not fired sends to nobody'; ...
    leaderGrew3 == 0, ...
        'the leader payload class is not dragged along by a neighbour sender'; ...
    neighbourGrewL == 0, ...
        'the leader payload class does not emit neighbour-state packets'; ...
    leaderGrewL == nnz(cPhase.swarm.pin), ...
        'the leader payload class reaches every pinned follower at once'; ...
    ~isequal(oPhase.P, oNewOff.P), ...
        'phase on is not inert for a periodic method'; ...
    oPhase.phaseHash == pA.hash, ...
        'the run consumed the registry phase realization'}];


%% ============================================================
% [5] P10 and P20 share one phase realization, scaled by period
% ============================================================

uShared = pA.u;

firstFireP10 = uShared * 0.10 + 0.10;
firstFireP20 = uShared * 0.05 + 0.05;

checks = [checks; { ...
    oPhase.phaseHash == oPhase20.phaseHash, ...
        'P10 and P20 draw the identical phase realization'; ...
    all(abs(firstFireP20 - (firstFireP10 - 0.10)/2 - 0.05) < 1e-12), ...
        'the shared phaseU scales with each period rather than being redrawn'}];


%% ============================================================
% [6] Phase does not touch the event-driven methods
%
% Neither State-event nor Causal-v3 has a periodic clock, so the phase
% realization must leave them bit-identical. Otherwise the EXP10 phase
% amendment would be confounded with the method comparison it exists to
% make fair.
% ============================================================

oEvOff = simSwarm6DOF(cNewOff, 'State-event');
oEvOn  = simSwarm6DOF(cPhase,  'State-event');

oCaOff = simSwarm6DOF(cNewOff, 'Causal-v3');
oCaOn  = simSwarm6DOF(cPhase,  'Causal-v3');

checks = [checks; { ...
    isequal(oEvOff.P, oEvOn.P), ...
        'phase leaves State-event bit-identical'; ...
    oEvOff.txCount == oEvOn.txCount, ...
        'phase leaves the State-event transmission count identical'; ...
    isequal(oCaOff.P, oCaOn.P), ...
        'phase leaves Causal-v3 bit-identical'; ...
    oCaOff.txCount == oCaOn.txCount, ...
        'phase leaves the Causal-v3 transmission count identical'; ...
    isnan(oCaOn.phaseHash) && isnan(oEvOn.phaseHash), ...
        'the event-driven methods report no phase realization'}];


%% ============================================================
% [7] Traffic volume does not advance the shared realization
%
% Plan section 5. The four methods transmit wildly different numbers of
% packets at the same seed; if the channel realization were consumed per
% transmission rather than indexed by (link, timestep), the busier
% method would meet a different channel and no paired comparison would
% be valid.
% ============================================================

hFwd = [oPhase.traceHash, oPhase20.traceHash, oEvOn.traceHash, oCaOn.traceHash];

txCounts = [oPhase.txCount, oPhase20.txCount, oEvOn.txCount, oCaOn.txCount];

reg = generateNetworkTrace(base);

checks = [checks; { ...
    numel(unique(hFwd)) == 1, ...
        'all four methods report the same forward realization hash'; ...
    hFwd(1) == reg.hash, ...
        'that hash is the one the registry fixed in advance'; ...
    numel(unique(txCounts)) == numel(txCounts), ...
        'the four methods really did transmit different amounts'; ...
    isnan(oPhase.ackTraceHash) && isnan(oEvOn.ackTraceHash), ...
        'a method with no reverse channel reports no ACK realization'; ...
    oCaOn.ackTraceHash == generateAckTrace(base).hash, ...
        'Causal-v3 consumed the registry reverse realization'}];


%% ============================================================
% [8] Fault and blackout realizations are hashed and seed-keyed
% ============================================================

c20 = applyTopologyConfig(defaultConfig(), 20, 'ring2');
c20.net.seed = 25000001;

c20b = c20; c20b.net.seed = 25000002;

fA = generateFaultRealization(c20,  'permanent', 0.20);
fA2 = generateFaultRealization(c20, 'permanent', 0.20);
fB = generateFaultRealization(c20b, 'permanent', 0.20);

bA = generateBlackoutRealization(c20,  1, 5.0);
bA2 = generateBlackoutRealization(c20, 1, 5.0);
bB = generateBlackoutRealization(c20b, 1, 5.0);

fNone = generateFaultRealization(c20, 'none', 0);
bNone = generateBlackoutRealization(c20, 0, 0);

checks = [checks; { ...
    fA.hash == fA2.hash,   'the link-fault hash is reproducible'; ...
    fA.hash ~= fB.hash,    'the link-fault hash separates seeds'; ...
    isequal(fA.down, fA2.down), 'the link-fault realization is reproducible'; ...
    ~isequal(fA.down, fB.down), 'a different seed downs different links'; ...
    isfinite(fA.hash),     'a permanent outage tEnd = inf still hashes finite'; ...
    bA.hash == bA2.hash,   'the blackout hash is reproducible'; ...
    bA.hash ~= bB.hash,    'the blackout hash separates seeds'; ...
    isfinite(fNone.hash) && isfinite(bNone.hash), ...
        'the no-fault realizations are hashed too'; ...
    fNone.hash ~= fA.hash, ...
        'the no-fault link realization is distinguishable from a faulted one'}];


%% ============================================================
% [9] Holdout seed assertion, on the pre-registered block
% ============================================================

rep = assertExp10Seeds(25000001:25000050, false);

checks = [checks; { ...
    rep.baseDisjoint, ...
        'no EXP10 holdout seed was used by EXP01-EXP09'; ...
    rep.internalIndependent, ...
        'the seven EXP10 realization streams are mutually disjoint'; ...
    rep.nSeeds == 50, ...
        'the pre-registered block is 50 seeds'}];


%% ============================================================
% [10] Paired statistics
% ============================================================

sA = pairedCI([1 2 3 4 5]', [2 3 4 5 6]', 5);
sB = pairedCI([1 2 3 NaN 5]', [2 3 4 5 6]', 5);
sC = pairedCI([1 -1 1 -1 0]', zeros(5,1), 5);

tExpect = tinv(0.975, 4);

checks = [checks; { ...
    abs(sA.meanD + 1) < 1e-12,      'the paired mean difference is correct'; ...
    sA.stdD == 0,                   'a constant difference has zero spread'; ...
    ~sA.crossesZero,                'a constant negative difference excludes zero'; ...
    sA.complete && sA.nPairs == 5,  'a complete sample is reported complete'; ...
    sB.nPairs == 4 && sB.nDropped == 1, ...
        'a diverged arm removes exactly one pair'; ...
    ~sB.complete, ...
        'an incomplete sample is flagged, not quietly quoted as 50 seeds'; ...
    sC.crossesZero, ...
        'a difference straddling zero is flagged as containing zero'; ...
    abs(sC.tCrit - tExpect) < 1e-12, ...
        'the t quantile matches tinv(0.975, nPairs-1)'}];


%% ============================================================
% [11] The point registry is the frozen matrix
% ============================================================

pts = exp10Points();

nCell = sum(arrayfun(@(p) numel(p.scenarios), pts));

Ns = unique([pts.N]);

kinds = {pts.kind};

checks = [checks; { ...
    numel(pts) == 8, ...
        'the final matrix has eight selected points'; ...
    nCell == 17, ...
        'the final matrix has seventeen point-scenario cells'; ...
    isequal(Ns, [5 20 50]), ...
        'coverage spans N = 5, 20 and 50'; ...
    numel(pts(1).scenarios) == 3, ...
        'the nominal point carries Clean as well as Moderate and Stressed'; ...
    any(strcmp(kinds,'link')) && any(strcmp(kinds,'node')) && ...
        any(strcmp(kinds,'mismatch')) && any(strcmp(kinds,'estimator')) && ...
        any(strcmp(kinds,'ack')), ...
        'every robustness group named in the plan appears exactly once'}];


%% ============================================================
% [12] applyExp10Point installs the pre-registered values
% ============================================================

sc = exp10Scenarios();

cfgNom = applyExp10Point(pts(1), sc.STRESSED, 25000001);
cfgAck = applyExp10Point(pts(2), sc.STRESSED, 25000001);
cfgMis = applyExp10Point(pts(3), sc.MODERATE, 25000001);
cfgEst = applyExp10Point(pts(4), sc.MODERATE, 25000001);
cfgLnk = applyExp10Point(pts(5), sc.MODERATE, 25000001);
cfgNod = applyExp10Point(pts(6), sc.MODERATE, 25000001);
cfgScl = applyExp10Point(pts(8), sc.MODERATE, 25000001);

checks = [checks; { ...
    cfgNom.net.seed == 25000001, ...
        'the holdout seed reaches cfg.net.seed unmodified'; ...
    cfgNom.net.phaseOffsetEnabled, ...
        'EXP10 runs with transmission phase on'; ...
    cfgNom.net.useTrace && cfgNom.ack.useTrace, ...
        'both channel traces are on'; ...
    ~isfield(cfgNom,'fault') && ~isfield(cfgNom,'blackout') && ...
        ~isfield(cfgNom,'estimator') && ~isfield(cfgNom,'quadTrue'), ...
        'the nominal point installs no perturbation at all'; ...
    cfgAck.ack.loss == 0.10 && cfgAck.ack.delay == sc.delay(sc.STRESSED), ...
        'the ACK point is 10 % reverse loss at the forward DATA delay'; ...
    cfgAck.ack.jitterStd == 0, ...
        'the ACK point carries no reverse jitter'; ...
    abs(cfgMis.quadTrue.m / cfgMis.quad.m - 1.10) < 1e-12 && ...
        abs(cfgMis.quadTrue.linearDrag / cfgMis.quad.linearDrag - 1.20) < 1e-12 && ...
        cfgMis.actuator.tau == 0 && cfgMis.extForce.level == 0.5, ...
        'the mismatch point is EXP09B arm B7 exactly'; ...
    cfgEst.estimator.latency == 0.050 && ...
        cfgEst.estimator.noise.posSigma == 0.03 && ...
        cfgEst.estimator.noise.velSigma == 0.05, ...
        'the estimator point is EXP09C arm C3 exactly'; ...
    strcmpi(cfgLnk.fault.type,'permanent') && cfgLnk.fault.level == 0.20, ...
        'the link point is a permanent 20 % directed-link removal'; ...
    cfgNod.blackout.nNodes == 1 && cfgNod.blackout.duration == 5.0 && ...
        cfgNod.blackout.tStart == 12.0, ...
        'the node point is one follower dark for 5 s from t = 12 s'; ...
    cfgScl.swarm.N == 50 && ~cfgScl.sixdof.enable, ...
        'the scalability anchor is N = 50 double integrator'; ...
    all(cfgScl.swarm.A(1,:) == 0), ...
        'N = 50 uses the EXP08 graph convention, not the EXP06A one'; ...
    cfgNom.sixdof.enable && cfgNom.sixdof.ratio == 10, ...
        'the N = 5 points are 6-DOF at the locked inner ratio'; ...
    ~cfgNom.swarm.normalizeConsensusDegree, ...
        'the original controller is used, not the EXP08A-D diagnostic'}];


%% ============================================================
% [13] Registry: distinct realizations across a sample of seeds
% ============================================================

regS = exp10Registry(25000001:25000004, 5, false);

checks = [checks; { ...
    regS.distinct, ...
        'four holdout seeds give four distinct CONTINUOUS realizations'; ...
    all(isfinite(regS.master(:))), ...
        'every master hash is finite'; ...
    numel(unique(regS.master)) == 4, ...
        'the master hash separates seeds'; ...
    numel(regS.discreteDetail) == 2, ...
        'the two discrete fault realizations are reported, not gated'}];


%% ============================================================
% Verdict
% ============================================================

okFlags = false(size(checks,1),1);
okNames = cell(size(checks,1),1);

for q = 1:size(checks,1)
    okFlags(q) = logical(checks{q,1});
    okNames{q} = checks{q,2};
    fprintf('    %-4s %s\n', verdict(okFlags(q)), okNames{q});
end

fprintf('\n');

nBad = nnz(~okFlags);

if nBad == 0
    fprintf('test_exp10_infrastructure: PASS (%d checks)\n', numel(okFlags));
else
    fprintf('test_exp10_infrastructure: FAIL (%d of %d checks)\n', nBad, numel(okFlags));
    for q = find(~okFlags(:)')
        fprintf('    failed: %s\n', okNames{q});
    end
    error('test_exp10_infrastructure failed.');
end
