%% TEST_EXP14F_SHADOW_CONTRACTS Paired-shadow matching and design checks.

startup;
R=exp14fRegistry();
[registryHash,registryLeaves]=configHash(R);
assert(registryHash==20176987 && registryLeaves==25, ...
    'EXP14F registry hash and leaf count must be frozen after first calculation.');
assert(R.expectedGroups==80 && R.expectedRuns==160 && ...
    ~R.confirmatoryClaimPermitted && ~R.newDesignPermitted, ...
    'EXP14F must remain an 80-pair development design.');

known=[exp14Registry().seeds; exp14cRegistry().seeds; ...
    exp14dRegistry().seeds; exp14eRegistry().seeds];
assert(numel(unique(R.seeds))==20 && isempty(intersect(R.seeds,known)), ...
    'EXP14F development seeds must be unique and unopened by prior studies.');

for k=1:numel(R.cells)
    cfg=applyExp14FCell(R.cells(k).id,0);
    assert(cfg.shared.ackValueLogging.enabled && ...
        strcmp(cfg.shared.ackValueLogging.schema,R.eventSchema), ...
        'Every EXP14F cell must enable the frozen passive event schema.');
end

base=applyExp14FCell('n5-csma',16018998);
[actual,actualMethod]=applyExp14FArm(base,R.arms(1));
[shadow,shadowMethod]=applyExp14FArm(base,R.arms(2));
assert(strcmp(actual.exp14f.role,'actual') && ...
    strcmp(actual.shared.feedbackMode,'adaptive') && ...
    strcmp(shadow.exp14f.role,'shadow') && ...
    strcmp(shadow.shared.feedbackMode,'piggyback') && ...
    strcmp(actualMethod,'mac-aware-broadcast') && ...
    strcmp(shadowMethod,'causal-broadcast'), ...
    'Actual/shadow arm roles and feedback semantics are exact.');

% Synthetic contract: later crossing, already-crossed shadow, and censoring.
A=[event(1.0,2,1,3,0.7,'ack',10); ...
   event(2.0,3,1,5,1.5,'ack',11); ...
   event(3.0,4,1,7,2.7,'ack',12)];
S=[event(1.4,2,1,4,0.9,'data',21); ...
   event(1.6,3,1,5,1.5,'data',20)];
M=matchAckValueEvents(A,S,5.0);
assert(numel(M)==3 && abs(M(1).leadSeconds-0.4)<1e-12 && ...
    M(1).isEarlier && ~M(1).censored && ...
    M(2).leadSeconds==0 && M(2).shadowEarlierOrEqual && ...
    M(3).censored && abs(M(3).leadSeconds-2.0)<1e-12, ...
    'Generation matching, nonnegative lead and horizon censoring are exact.');

bad=rmfield(A,'genTime'); rejected=false;
try
    matchAckValueEvents(bad,S,5.0);
catch
    rejected=true;
end
assert(rejected,'Malformed event schemas must fail at the matcher boundary.');

% Full paired smoke run uses a development-only seed and one absolute trace.
base.swarm.T=2.0; base.shared.evalStart=0;
trace=generateSharedMediumTrace(base);
actual=applyExp14FArm(base,R.arms(1));
shadow=applyExp14FArm(base,R.arms(2));
outA=simSwarmSharedMedium(actual,actualMethod,trace);
outS=simSwarmSharedMedium(shadow,shadowMethod,trace);
M=matchAckValueEvents(outA.ackValueLog,outS.ackValueLog,base.swarm.T);
assert(outA.traceHashExact==outS.traceHashExact && ...
    outA.channelStateHash==outS.channelStateHash, ...
    'Paired arms must consume the same absolute exogenous trace.');
assert(numel(outA.ackValueLog)==outA.netStats.ackEntriesDelivered && ...
    numel(outS.ackValueLog)==outS.netStats.ackEntriesDelivered && ...
    all(string({outS.ackValueLog.transport})=="data"), ...
    'Full runs must preserve confirmation-event accounting semantics.');
if ~isempty(M)
    assert(all([M.leadSeconds]>=0) && ...
        all([M.leadSeconds]<=[M.actualTime]*0+base.swarm.T-[M.actualTime]+1e-12), ...
        'Every matched lead must lie inside its remaining horizon.');
end

unknown=R.arms(1); unknown.id='unregistered'; rejected=false;
try
    applyExp14FArm(base,unknown);
catch
    rejected=true;
end
assert(rejected,'Unregistered EXP14F arms must fail at the boundary.');

fprintf(['test_exp14f_shadow_contracts: PASS ' ...
    '(registry, arm semantics, matcher, censoring, paired smoke)\n']);


function e=event(time,source,target,seq,genTime,transport,frameId)

e=struct('time',time,'sourceReceiver',source,'targetSender',target, ...
    'seq',seq,'genTime',genTime,'transport',transport, ...
    'frameId',frameId,'frameSender',source,'txStart',time-0.1, ...
    'txEnd',time,'bytes',20);

end
