%% TEST_RECEIVER_LIFTED_CLOSURE_RELIABILITY_CONTRACTS Phase reserve bound.
startup;

R=exp23afOnlineClosureRegistry(); [M,C]=fixture(R);
B=receiverLiftedClosureReliabilityCertificate(M,C,8);
assert(B.horizonFeasible&&B.prepareOpportunityCount==7&& ...
    B.claimOpportunityCount==15&&B.responseSuffixAttempts==7&& ...
    B.commitFramesReserved==6&&B.unionFailureUpperBound<1e-3&& ...
    abs(B.completionProbabilityLowerBound+ ...
    B.unionFailureUpperBound-1)<1e-15);

short=C; short.maxFrames=B.latestPrepareFrame+5;
Bs=receiverLiftedClosureReliabilityCertificate(M,short,8);
assert(~Bs.horizonFeasible&&Bs.unionFailureUpperBound==1&& ...
    Bs.completionProbabilityLowerBound==0);

fprintf('test_receiver_lifted_closure_reliability_contracts: PASS\n');


function [M,C]=fixture(R)

N=5; initiator=N; neighbor=false(N); neighbor(initiator,1)=true;
I0=false(N); I1=I0; I1(initiator,[2 3])=true;
I1([2 3],initiator)=true;
F0=buildSenderConflictGraph(neighbor,I0);
F1=buildSenderConflictGraph(neighbor,I1);
slot=elcsWitnessPriorityColor(F0); reach=true(N);
reach(1:N+1:end)=false;
packet=struct('maxDataSlots',2*N,'maxAffectedNodes',N, ...
    'prepareHeaderBytes',R.prepareHeaderBytes, ...
    'affectedEntryBytes',R.affectedEntryBytes,'claimBytes',R.claimBytes, ...
    'quietBytes',R.quietBytes,'lockProofBytes',R.lockProofBytes, ...
    'certificateHeaderBytes',R.certificateHeaderBytes, ...
    'certificateEntryBytes',R.certificateEntryBytes, ...
    'commitBytes',R.commitBytes,'revokeBytes',R.revokeBytes, ...
    'maxControlPacketBytes',R.maxControlPacketBytes);
M=buildReceiverLiftedDependencyMigration( ...
    F0,F1,slot,initiator,reach,packet);
C=struct('maxFrames',48,'prepareFrame',20, ...
    'prepareDenseRetryFrames',7,'prepareMaxBackoffFrames',4, ...
    'prepareRetryAttemptLimit',7,'claimEligibilityDelayFrames',2, ...
    'lockProofRepeatFrames',15,'claimBackoffEnabled',true, ...
    'claimDenseRetryFrames',15,'claimMaxBackoffFrames',8, ...
    'claimRetryAttemptLimit',15,'commitRetryAttemptLimit',6, ...
    'prepareErasureProbability',.2,'quietErasureProbability',.2, ...
    'claimErasureProbability',.2,'lockProofErasureProbability',.2, ...
    'responseErasureProbability',.2,'commitErasureProbability',.2);

end
