%% TEST_TCNS_R2_6_DECISION_IDENTIFIABILITY Synthetic theory and artifact tests.

startup;
fprintf('\n=== TCNS R2.6 decision-identifiability checks ===\n\n');

%% Test 1: a common hidden offset cancels from every relative value.
C = [1 0];
L = [1 1;2 1];
R = tcnsDecisionIdentifiability(C,L);
assert(R.rValue==1 && R.rRelative==0 && ...
    any(~R.individualIdentifiable) && R.fullRelativeIdentifiable, ...
    'R26: common-hidden-offset counterexample failed.');

%% Test 2: a pairwise difference varies along ker(C).
L = [0 1;0 -1];
R = tcnsDecisionIdentifiability(C,L);
assert(R.rRelative==1 && ~R.fullRelativeIdentifiable && ...
    R.pairwiseHiddenNorms(1,2)>0, ...
    'R26: hidden pairwise difference was not detected.');

%% Test 3: the difference is hidden but one action dominates on the fiber.
L = [0 1;0 0];
c = [2;0];
x0 = [0;0];
linear = tcnsDecisionIdentifiability(C,L);
fiber = tcnsFiberwiseArgmax(C,L,c,x0,0.5);
assert(linear.rRelative==1 && ~linear.fullRelativeIdentifiable && ...
    isequal(fiber.commonActions,1) && fiber.actionMargins(1)>0, ...
    'R26: common maximizer with a hidden difference failed.');

%% Test 4: crossing zero leaves no common maximizer.
fiber = tcnsFiberwiseArgmax(C,L,c,x0,3);
assert(~fiber.hasCommonMaximizer && ...
    fiber.pairwiseLower(1,2)<0 && fiber.pairwiseUpper(1,2)>0, ...
    'R26: ambiguous argmax crossing was not detected.');

%% Test 5: two actions reproduce the threshold/sign interval result.
tau = 0.25;
Lbinary = [0 1;0 0];
cbinary = [-tau;0];
binary = tcnsFiberwiseArgmax(C,Lbinary,cbinary,[0;tau],1);
assert(binary.pairwiseLower(1,2)<0 && ...
    binary.pairwiseUpper(1,2)>0 && ~binary.hasCommonMaximizer, ...
    'R26: binary threshold reduction failed.');
boundary = tcnsFiberwiseArgmax(C,Lbinary,[1;0],[0;0],1);
assert(isequal(boundary.commonActions,1) && ...
    boundary.pairwiseLower(1,2)==0, ...
    'R26: binary boundary/tie semantics failed.');

%% Test 6: the relative hidden rank is invariant to difference basis.
L3 = [1 1 0;2 1 1;4 1 -1];
C3 = [1 0 0];
Breference = [1 0 -1;0 1 -1];
Badjacent = [1 -1 0;0 1 -1];
left = tcnsDecisionIdentifiability(C3,L3,Breference);
right = tcnsDecisionIdentifiability(C3,L3,Badjacent);
assert(left.rRelative==right.rRelative && ...
    abs(norm(left.LRelativeHidden,'fro')- ...
    norm(Breference/(Badjacent)*right.LRelativeHidden,'fro'))<1e-10, ...
    'R26: full-rank difference-basis invariance failed.');

%% Persisted post-processing artifact invariants, when generated.
artifactRoot = fullfile(projectRoot(),'results', ...
    'tcns_r2_6_decision_identifiability');
if isfile(fullfile(artifactRoot,'LATEST.txt'))
    runId = strtrim(fileread(fullfile(artifactRoot,'LATEST.txt')));
    runDir = fullfile(artifactRoot,runId);
    sender = readtable(fullfile(runDir, ...
        'decision_identifiability_sender.csv'),'Delimiter',',', ...
        'ReadVariableNames',true,'TextType','string');
    n5 = readtable(fullfile(runDir, ...
        'decision_identifiability_n5_frozen.csv'),'Delimiter',',', ...
        'ReadVariableNames',true,'TextType','string');
    binaryWitness = readtable(fullfile(runDir, ...
        'decision_identifiability_n5_binary_witness.csv'),'Delimiter',',', ...
        'ReadVariableNames',true,'TextType','string');
    assert(height(sender)==448 && all(sender.storedRValueMatch) && ...
        all(sender.rRelative<=sender.rValue), ...
        'R26: frozen-registry post-processing invariant failed.');
    assert(height(n5)==5 && isequal(sort(n5.sender)',1:5), ...
        'R26: frozen N=5 sender table is incomplete.');
    assert(height(binaryWitness)==10 && ...
        all(binaryWitness.strictlyAmbiguousOnWitnessPair), ...
        'R26: frozen binary witness reduction failed.');
end

fprintf('  synthetic theory cases                  6 / 6\n');
fprintf('test_tcns_r2_6_decision_identifiability: PASS\n');
