%% TEST_EXP23AF_ONLINE_CLOSURE_CONTRACTS Registry and paired smoke preflight.
startup;
fprintf('\n============================================================\n');
fprintf('test_exp23af_online_closure_contracts\n');
fprintf('============================================================\n\n');

R=exp23afOnlineClosureRegistry(); checks=0;
assert(R.expectedRuns==120&&numel(R.seeds)==20&&numel(R.arms)==6&& ...
    R.requiredValidationContracts==24&&R.N==10&&R.formationScale==2);
assert(isequal(R.commandTarget,[1.3 .1 0])&&R.commandRampSec==2&& ...
    isequal(R.emergencySlots,(11:15)')&& ...
    ~ismember(R.smokeSeed,R.seeds));
fprintf('    ok   120-row online fixture is frozen\n'); checks=checks+1;

B=continuousTdmaGuardBound( ...
    R.maxOffsetSec,R.maxDriftPpm,R.clockResetHorizonSec);
assert(abs(R.safeGuardSec-B.safeGuardSec)<1e-15&& ...
    strcmp(R.parentCommonPhyStatus, ...
    'RECEIVER_LIFTED_CLOSURE_COMMON_PHY_VALID')&& ...
    strcmp(R.parentRetryStatus,'BOUNDED_RETRY_DEVELOPMENT_FEASIBLE'));
fprintf('    ok   parent mechanisms and affine guard are locked\n');
checks=checks+1;

[rows,context]=runExp23afOnlineClosureSeed(R.smokeSeed,R);
T=struct2table(rows); closure=string(T.kind)=="closure";
normal=string(T.arm)=="closure-iid20-emergency";
response=string(T.arm)=="closure-response-blackout-emergency";
noEmergency=string(T.arm)=="closure-response-blackout-no-emergency";
prepare=string(T.arm)=="closure-prepare-blackout-emergency";
commit=string(T.arm)=="closure-commit-blackout-emergency";

assert(all(T.prefixStateExact(closure)==1)&& ...
    numel(unique(T.decisionStateHash(closure)))==1&& ...
    numel(unique(T.geometryHash(closure)))==1&& ...
    context.prepareFrame>1);
fprintf('    ok   online decision is causal and prefix-identical\n');
checks=checks+1;

assert(all(T.graphAdmissible(closure)==1)&& ...
    all(T.changedSenderEdges(closure)>=1)&& ...
    all(T.nonincidentSenderEdges(closure)>=1)&& ...
    all(T.affectedCount(closure)>=3)&& ...
    all(T.changedSlotCount(closure)>=1)&& ...
    all(T.candidateProper(closure)==1)&& ...
    all(T.protectedSlotFree(closure)==1));
fprintf('    ok   receiver-lifted recoloring stimulus is non-vacuous\n');
checks=checks+1;

assert(T.motionAuthorized(normal)==1&&T.allReactivated(normal)==1&& ...
    T.finalSuppressedCount(normal)==0&& ...
    T.motionAuthorized(response)==1&&T.allReactivated(response)==0&& ...
    T.finalSuppressedCount(response)==T.affectedCount(response)&& ...
    T.motionAuthorized(prepare)==0&&T.barrierClosed(prepare)==0&& ...
    T.motionAuthorized(commit)==1&&T.allReactivated(commit)==0&& ...
    T.finalSuppressedCount(commit)>0&&all(T.motionGateExact(closure)==1));
fprintf('    ok   normal and blackout motion gates are exact\n');
checks=checks+1;

protected=closure&~noEmergency;
assert(all(T.capsuleBoundSatisfied(protected)==1)&& ...
    all(T.actualPhysicalSubset(protected)==1)&& ...
    all(T.actualSenderSubset(protected)==1)&& ...
    all(T.emergencyParallelMode(protected)==1)&& ...
    all(T.emergencyMappingExact(protected)==1)&& ...
    all(T.emergencySuppressedDemand(protected)== ...
    T.emergencyOpportunities(protected))&& ...
    all(T.emergencyOpportunities(protected)>0)&& ...
    all(T.emergencyMaximumNodeOpportunities(protected)>0));
assert(T.emergencyOpportunities(noEmergency)==0&& ...
    T.capsuleBoundSatisfied(noEmergency)==0&& ...
    T.capsuleMaximumRatio(noEmergency)>1&& ...
    T.MISSION_RMSE(noEmergency)>T.MISSION_RMSE(response));
fprintf('    ok   protected service closes the tube; removal is negative\n');
checks=checks+1;

assert(all(T.kernelCollisionFrames(closure)==0)&& ...
    all(T.observedCollisionFrames(closure)==0)&& ...
    all(T.emergencyRecipientCollision(closure)==0)&& ...
    all(T.dataOutcomeMismatches(closure)==0)&& ...
    all(T.dataSkippedNoQueue(closure)==0)&& ...
    all(T.crossPlaneOverlaps(closure)==0));
assert(all(T.expectedDataSuccess(closure)==T.observedDataSuccess(closure))&& ...
    all(T.expectedDataErasure(closure)==T.observedDataErasure(closure)));
fprintf('    ok   common-PHY replay and collision accounting are exact\n');
checks=checks+1;

assert(all(T.controlAttempts(closure)==T.expectedControlAttempts(closure))&& ...
    all(abs(T.controlAirtime(closure)- ...
    T.expectedControlAirtime(closure))<1e-15)&& ...
    all(T.clockConflictFree(closure)==1)&& ...
    all(T.clockResidual(closure)<1e-12)&& ...
    all(T.futureRandomReads(closure)==0)&& ...
    all(T.receiverTruthReads(closure)==0));
fprintf('    ok   accounting, affine timing, and causal reads are exact\n');
checks=checks+1;

assert(all(T.SAFEFAIL==0)&&all(T.DIVERGED==0)&& ...
    ~R.managementRelayingValidated&&~R.freshSeedEvidence&& ...
    ~R.robustnessClaimPermitted&&~R.submissionClaimPermitted);
fprintf('    ok   safety passes without promoting downstream claims\n');
checks=checks+1;

fprintf('\ntest_exp23af_online_closure_contracts: PASS (%d checks)\n',checks);
