%% TEST_EXP23AR_ROUTED_PLANT_CLOSED_LOOP_CONTRACTS Frozen lineage and scope.
startup;

R=exp23arRoutedPlantClosedLoopRegistry();
assert(strcmp(R.version,'EXP23AR-ROUTED-PLANT-CLOSED-LOOP-v1')&& ...
    R.expectedRuns==120&&numel(unique(R.seeds))==20&& ...
    R.seeds(1)==16096401&&R.seeds(end)==16096420&& ...
    ~ismember(R.smokeSeed,R.seeds)&&R.transactionFrames==11&& ...
    R.repetitionsPerHop==4&&R.prepareAttempts==3&& ...
    R.claimAttempts==4&&R.evidencePrefixAttempts==2&& ...
    R.commitAttempts==2&&R.requiredValidationContracts==27);
parent=jsondecode(fileread(fullfile(projectRoot(),'results', ...
    'exp23aq_routed_state_machine_confirmation',R.parentRoutedRun, ...
    'routed_state_verdict.json')));
assert(strcmp(parent.status,R.parentRoutedStatus)&& ...
    parent.gatesPassed==R.parentRoutedGatesPassed&& ...
    parent.gatesTotal==R.parentRoutedGatesTotal&& ...
    parent.managementRelayingValidated&& ...
    ~parent.closedLoopManagementRelayingValidated);
assert(R.managementRelayingValidated&& ...
    ~R.closedLoopManagementRelayingValidated&& ...
    ~R.repeatedOnlineRenewalValidated&&~R.freshSeedEvidence&& ...
    ~R.robustnessClaimPermitted&&~R.submissionClaimPermitted);

fprintf('test_exp23ar_routed_plant_closed_loop_contracts: PASS\n');

