%% TEST_TCNS_ACTUAL_WITNESS_AUDIT Catalog/replay contracts without outcome forcing.

startup;
fprintf('\n=== TCNS actual-action witness audit checks ===\n\n');

[cfg,~] = tcnsGate6Scenario(27020001,'S1');
options.referenceCount = 2;
A = tcnsInformationLimitsActualWitnessAudit(cfg,25,4,options);
T = A.witnessTable;
assert(height(T)==10 && numel(unique(T.actionId))==10, ...
    'ActualWitnessAudit: the frozen ten-action catalog is incomplete.');
allowed = ["NONE" "NO_NULL_DIRECTION" "REACHABILITY_INFEASIBLE" ...
    "NO_SIGN_CROSSING_FOUND" "SATURATION_VIOLATION" "NUMERICAL_FAILURE"];
assert(all(ismember(T.failureReason,allowed)), ...
    'ActualWitnessAudit: a failure lacks a declared primary reason.');
assert(all(T.actualResponseTested | T.failureReason=="NUMERICAL_FAILURE"), ...
    'ActualWitnessAudit: an action was silently skipped.');

success = T.reachableWitnessFound;
assert(all(T.failureReason(success)=="NONE"), ...
    'ActualWitnessAudit: successful row has a failure reason.');
assert(all(T.qMinus(success)<-A.options.signTolerance & ...
    T.qPlus(success)>A.options.signTolerance), ...
    'ActualWitnessAudit: successful witness does not cross the value sign.');
assert(all(T.senderObservationResidual(success)<= ...
    A.options.informationTolerance), ...
    'ActualWitnessAudit: successful sender histories are distinguishable.');
assert(all(T.dynamicReachabilityResidual(success)<= ...
    A.options.reachabilityTolerance), ...
    'ActualWitnessAudit: successful witness fails direct dynamic replay.');
assert(all(T.actionResponseResidual(success)<=A.options.responseTolerance), ...
    'ActualWitnessAudit: successful pair changes the actual action response.');
assert(all(T.oracleValueResidual(success)<=A.options.oracleTolerance), ...
    'ActualWitnessAudit: affine value disagrees with independent oracle.');
assert(all(T.saturationMargin(success)> ...
    A.options.saturationMarginTolerance), ...
    'ActualWitnessAudit: successful pair violates the unsaturated scope.');
assert(all(success==(T.failureReason=="NONE")), ...
    'ActualWitnessAudit: success/failure fields are inconsistent.');

fprintf('  structural nonidentifiable  %d / %d\n', ...
    A.structuralNonidentifiableCount,A.actionCount);
fprintf('  actual responses tested     %d / %d\n', ...
    A.actualResponseTestedCount,A.actionCount);
fprintf('  reachable witnesses         %d / %d\n', ...
    A.reachableWitnessCount,A.actionCount);
fprintf('test_tcns_actual_witness_audit: PASS\n');
