%% TEST_TCNS_FORCED_PERIODIC_BRANCH Exact paired one-action branch contracts.

startup;

fprintf('\n=== TCNS forced periodic branch checks ===\n\n');

[cfg,~] = tcnsGate6Scenario(27020001,'S1');
cfg.swarm.T = 6;
cfg.net.commPeriod = 10*cfg.swarm.dt;
cfg.tcns.logReceiverState = true;
cfg.tcns.logPeriodicSenderFire = true;
base = simSwarmNetworkQueued(cfg);
H = 25;
Q = tcnsOracleQuadraticCrossTerm(base,cfg,H);
trace = generateNetworkTrace(cfg);

fixtures = struct( ...
    'receiver',{3,2},'sender',{2,1}, ...
    'linkClass',{'ordinary','pinned-leader'});
acceptedChecks = 0;
for q = 1:numel(fixtures)
    f = fixtures(q);
    if strcmp(f.linkClass,'ordinary')
        isolated = Q.ordinaryIsolatedResponseEnergy(:,f.receiver,f.sender);
        success = reshape( ...
            trace.lossU(:,f.receiver,f.sender)>=cfg.net.packetLoss,[],1);
        scheduleSlot = f.sender;
    else
        isolated = Q.leaderIsolatedResponseEnergy(:,f.receiver);
        success = reshape( ...
            trace.leaderLossU(:,f.receiver)>=cfg.net.packetLoss,[],1);
        scheduleSlot = cfg.swarm.N+1;
    end
    eligible = base.t>=1 & base.t<=4.5 & ...
        ~base.periodicSenderFireLog(:,scheduleSlot) & ...
        isfinite(isolated) & isolated>1e-10 & success;
    k = find(eligible,1,'first');
    assert(~isempty(k),'ForcedBranch: no successful fixture action found.');

    branchCfg = cfg;
    branchCfg.tcns.forcedPeriodicTransmission = struct( ...
        'enabled',true,'time_s',base.t(k), ...
        'receiver',f.receiver,'sender',f.sender, ...
        'linkClass',f.linkClass);
    branch = simSwarmNetworkQueued(branchCfg);
    F = branch.forcedPeriodicTransmission;
    assert(F.attempted && F.enqueued && F.accepted && F.resolved && ...
        ~F.dropped && F.txDelta==1 && F.dropDelta==0, ...
        'ForcedBranch: successful action metadata is incorrect.');
    assert(branch.txCount==base.txCount+1 && ...
        branch.rxCount==base.rxCount+1 && ...
        branch.dropCount==base.dropCount && ...
        branch.broadcastCount==base.broadcastCount+1, ...
        'ForcedBranch: successful action accounting is incorrect.');
    assert(branch.traceHashExact==base.traceHashExact && ...
        branch.phaseHash==base.phaseHash && ...
        isequal(branch.periodicSenderFireLog,base.periodicSenderFireLog), ...
        'ForcedBranch: paired realization/schedule changed.');
    assert(isequaln(branch.P(1:k,:,:),base.P(1:k,:,:)) && ...
        isequaln(branch.V(1:k,:,:),base.V(1:k,:,:)), ...
        'ForcedBranch: action changed plant state before its decision time.');
    assert(max(abs(branch.P(:)-base.P(:)))>0, ...
        'ForcedBranch: accepted action did not alter the closed loop.');
    acceptedChecks = acceptedChecks+1;
end

% A forced packet assigned a frozen drop outcome must change accounting but
% leave the entire state/control trajectory bit-identical.
i = 3;
j = 2;
isolated = Q.ordinaryIsolatedResponseEnergy(:,i,j);
dropped = reshape(trace.lossU(:,i,j)<cfg.net.packetLoss,[],1);
eligible = base.t>=1 & base.t<=4.5 & ...
    ~base.periodicSenderFireLog(:,j) & ...
    isfinite(isolated) & isolated>1e-10 & dropped;
k = find(eligible,1,'first');
assert(~isempty(k),'ForcedBranch: no dropped fixture action found.');
dropCfg = cfg;
dropCfg.tcns.forcedPeriodicTransmission = struct( ...
    'enabled',true,'time_s',base.t(k),'receiver',i,'sender',j, ...
    'linkClass','ordinary');
dropBranch = simSwarmNetworkQueued(dropCfg);
F = dropBranch.forcedPeriodicTransmission;
assert(F.attempted && F.dropped && F.resolved && ~F.enqueued && ...
    ~F.accepted && F.txDelta==1 && F.dropDelta==1, ...
    'ForcedBranch: dropped action metadata is incorrect.');
assert(dropBranch.txCount==base.txCount+1 && ...
    dropBranch.dropCount==base.dropCount+1 && ...
    dropBranch.rxCount==base.rxCount && ...
    dropBranch.broadcastCount==base.broadcastCount+1, ...
    'ForcedBranch: dropped action accounting is incorrect.');
assert(isequaln(dropBranch.P,base.P) && ...
    isequaln(dropBranch.V,base.V) && isequaln(dropBranch.A,base.A), ...
    'ForcedBranch: a dropped action changed the physical trajectory.');

% Merely attaching a disabled hook must be exactly inert.
disabledCfg = cfg;
disabledCfg.tcns.forcedPeriodicTransmission = struct('enabled',false);
disabled = simSwarmNetworkQueued(disabledCfg);
coreFields = {'P','V','A','meanAoI','txCountLog','broadcastCountLog', ...
    'txCount','dropCount','rxCount','traceHashExact','phaseHash', ...
    'periodicSenderFireLog'};
for f = 1:numel(coreFields)
    name = coreFields{f};
    assert(isequaln(disabled.(name),base.(name)), ...
        'ForcedBranch: disabled hook changed out.%s.',name);
end

fprintf('  accepted ordinary/pinned branch checks       %d\n',acceptedChecks);
fprintf('  dropped action state identity                 PASS\n');
fprintf('  disabled hook identity                        PASS\n');
fprintf('test_tcns_forced_periodic_branch: PASS\n');
