%% TEST_EXP18B_CONTRACTS Frozen design checks without holdout simulations.

startup;
fprintf('\n============================================================\n');
fprintf('test_exp18b_contracts\n');
fprintf('============================================================\n\n');
checks=cell(0,2);

R=exp18bRegistry();
[registryHash,registryLeaves]=configHash(R);
checks(end+1,:)={registryHash==149048254 && registryLeaves==153 && ...
    R.expectedRuns==8000 && R.primaryFamilySize==9, ...
    'registry hash, matrix and nine-test family are frozen'};

known=[exp14Registry().seeds; exp14cRegistry().seeds; ...
    exp14dRegistry().seeds; exp14eRegistry().seeds; ...
    exp14fRegistry().seeds; exp14gRegistry().seeds; ...
    exp14hRegistry().seeds; exp14iRegistry().seeds; ...
    exp16Registry().seeds; exp17Registry().seeds; exp18Registry().seeds];
checks(end+1,:)={numel(unique(R.seeds))==100 && ...
    isempty(intersect(R.seeds,known)) && ...
    R.seeds(1)==16025001 && R.seeds(end)==16025100, ...
    '100 holdout seeds are unique, exact and disjoint from known blocks'};

checks(end+1,:)={numel(R.feasibleTests)==5 && ...
    strcmp(R.abstentionCell,'n5-stressed-bg0') && ...
    strcmp(R.abstentionMac,'aloha') && ...
    numel(R.n10CollisionCells)==4 && ...
    ~R.universalOptimalityClaimPermitted && ...
    ~R.populationSafetyClaimPermitted && ~R.hardwareClaimPermitted, ...
    'primary cells, abstention boundary and claim ceilings are frozen'};

% Short executions use the reserved development seed, never a holdout seed.
cases={ ...
    'n5-moderate-bg0','csma',true,'frame-piggyback'; ...
    'n5-moderate-bg0','aloha',true,'frame-adaptive'; ...
    'n5-stressed-bg0','aloha',false,'frame-piggyback'; ...
    'n10-moderate-bg0','aloha',false,'frame-piggyback'};
for q=1:size(cases,1)
    cellId=cases{q,1}; mac=cases{q,2}; expectedFeasible=cases{q,3};
    referenceId=cases{q,4};
    base=applyExp18BCell(cellId,R.developmentSeed);
    base.mac.type=mac; base.mac.pAccess=min(0.20,1/base.swarm.N);
    base.swarm.T=0.30; base.shared.evalStart=0; base.sixdof.enable=false;
    trace=generateSharedMediumTrace(base);
    out=cell(numel(R.arms),1); details=cell(numel(R.arms),1);
    certs=cell(numel(R.arms),1);
    for k=1:numel(R.arms)
        [cfg,method,~,details{k},certs{k}]=applyExp18BArm(base,R.arms(k));
        out{k}=simSwarmSharedMedium(cfg,method,trace);
    end
    candidate=find(strcmp({R.arms.id},R.candidate));
    reference=find(strcmp({R.arms.id},referenceId));
    exact=isequaln(out{candidate}.P,out{reference}.P) && ...
        isequaln(out{candidate}.V,out{reference}.V) && ...
        isequaln(out{candidate}.dataAttemptLog, ...
        out{reference}.dataAttemptLog) && ...
        isequaln(out{candidate}.ackAttemptLog, ...
        out{reference}.ackAttemptLog) && ...
        out{candidate}.traceHashExact==out{reference}.traceHashExact;
    allCerts=cellfun(@(x) x.feasible,certs);
    checks(end+1,:)={all(allCerts==expectedFeasible) && ...
        strcmp(details{candidate}.routedReference,referenceId) && exact, ...
        sprintf('%s/%s screen and exact routed alias execute',cellId,mac)};
end

base=applyExp18BCell('n5-moderate-bg0',R.developmentSeed);
base.mac.type='aloha'; base.swarm.T=0.20; base.shared.evalStart=0;
[cfg,method,label,details,certificate]=applyExp18BArm(base,R.arms(1));
meta=struct('stage','contract-test','scenario','n5-moderate-bg0', ...
    'scenarioLabel','contract','family','EXP18B test', ...
    'arm',R.candidate,'pointIndex',1,'parameterValue',0, ...
    'role','core','channel','moderate','modifier','nominal', ...
    'basePAccess',base.mac.pAccess);
row=runExp18BCell(cfg,method,label,meta, ...
    generateSharedMediumTrace(base),details,certificate);
checks(end+1,:)={isequal(fieldnames(row),fieldnames(exp18bEmptyRow())) && ...
    row.candidateFlag==1 && strcmp(row.routeRule,'capacity-gated-mac'), ...
    'holdout row schema and candidate metadata close'};

unknown=false;
try
    fake=R.arms(1); fake.id='post-hoc-arm';
    applyExp18BArm(base,fake);
catch
    unknown=true;
end
checks(end+1,:)={unknown,'unknown post-hoc arm is rejected'};

flags=cellfun(@logical,checks(:,1));
for k=1:size(checks,1)
    if flags(k), tag='ok'; else, tag='FAIL'; end
    fprintf('    %-4s %s\n',tag,checks{k,2});
end
if ~all(flags)
    error('test_exp18b_contracts: %d of %d checks failed.', ...
        nnz(~flags),numel(flags));
end
fprintf('\ntest_exp18b_contracts: PASS (%d checks)\n',numel(flags));
