%% TEST_EXP19A_END_TO_END Short integrated scheduler/control regression.

startup;
fprintf('\n============================================================\n');
fprintf('test_exp19a_end_to_end\n');
fprintf('============================================================\n\n');
checks=cell(0,2);
R=exp19aRegistry();
base=applyExp19ACell('n5-stressed-bg0',16025999);
base.swarm.T=1.0;
base.shared.evalStart=0.2;
base.sixdof.enable=false;
trace=generateSharedMediumTrace(base);
ids={'collision-free-tdma-piggyback', ...
    'oracle-deficit-maxweight-piggyback', ...
    'oracle-urgency-maxweight-piggyback','periodic-tdma-p8p333'};
rows=repmat(exp19aEmptyRow(),numel(ids),1);
for k=1:numel(ids)
    idx=find(strcmp({R.arms.id},ids{k}),1);
    [cfg,method,label,details]=applyExp19AArm(base,R.arms(idx));
    meta=struct('stage','preflight','scenario','n5-stressed-bg0', ...
        'scenarioLabel','short integrated preflight', ...
        'family','EXP19A preflight','arm',ids{k}, ...
        'pointIndex',k,'parameterValue',R.arms(idx).periodicRateHz);
    rows(k)=runExp19ACell(cfg,method,label,meta,trace,details);
end
T=struct2table(rows);
checks(end+1,:)={all(isfinite(T.RMSE)) && ...
    all(isfinite(T.OFFERED_UTIL)) && all(T.INVARIANT_VIOLATIONS==0), ...
    'short control/network trajectories are finite and causal'};
checks(end+1,:)={all(T.SERVICE_COMPLETIONS==T.DATA_DELIVERED) && ...
    all(T.VIRTUAL_DEFICIT_TERMINAL== ...
    T.SERVICE_ADMISSIONS-T.SERVICE_COMPLETIONS), ...
    'integrated virtual-service accounting closes exactly'};
checks(end+1,:)={all(T.SERVICE_DECISION_LOG_VALID==1) && ...
    all(T.SERVICE_DECISIONS>0) && all(T.FUTURE_RANDOM_READS==0), ...
    'integrated service decision logs are complete and future-blind'};
checks(end+1,:)={all(T.ACK_STANDALONE==0) && ...
    all(T.ENDOGENOUS_COLLISION_FRAMES==0), ...
    'all scheduled arms remain standalone-free and collision-free'};
checks(end+1,:)={isscalar(unique(T.TRACE_HASH_EXACT)) && ...
    isscalar(unique(T.CHANNEL_STATE_HASH)), ...
    'all integrated arms replay one absolute channel realization'};

flags=cellfun(@logical,checks(:,1));
for k=1:size(checks,1)
    if flags(k), tag='ok'; else, tag='FAIL'; end
    fprintf('    %-4s %s\n',tag,checks{k,2});
end
if ~all(flags)
    error('test_exp19a_end_to_end: %d of %d checks failed.', ...
        nnz(~flags),numel(flags));
end
fprintf('\ntest_exp19a_end_to_end: PASS (%d checks)\n',numel(flags));
