%% TEST_TCNS_R2_GENERALIZATION Structural invariants, not favorable outcomes.

startup;
fprintf('\n=== TCNS R2 generalization invariant checks ===\n\n');

options = struct('NValues',5,'graphIds',"ring2",'pinIds',"even", ...
    'HValues',25,'DValues',4,'enableVpa',true);
R = tcnsR2GeneralizationAudit(options);
assert(height(R.registryTable)==1 && R.registryTable.admissible, ...
    'R2Generalization: deterministic sentinel configuration is inadmissible.');
[cfg,~] = tcnsGate6Scenario(R.options.seed,'S1');
model = tcnsInformationLimitsModel(cfg,25,4,0);
catalog = tcnsInformationLimitsActionCatalog(model);
assert(height(R.actionTable)==height(catalog), ...
    'R2Generalization: an action disappeared from the sentinel audit.');
assert(height(R.toleranceTable)==height(catalog)*numel(R.options.toleranceGrid), ...
    'R2Generalization: tolerance-grid row count is inconsistent.');
assert(all(R.senderTable.missingRank<=R.senderTable.actionCount), ...
    'R2Generalization: r_j* exceeds p_j.');
assert(all(R.actionTable.historyRank+R.actionTable.historyNullity==model.nState), ...
    'R2Generalization: conditioned rank/nullity is inconsistent.');
assert(all(abs(R.actionTable.normalizedRowSpaceResidual- ...
    R.actionTable.directNormalizedResidual)<=1e-9), ...
    'R2Generalization: compressed and direct row-space calculations disagree.');
assert(all(R.actionTable.augmentedRankIncrease>=0 & ...
    R.actionTable.augmentedRankIncrease<=1), ...
    'R2Generalization: a scalar row changes rank by more than one.');
assert(any(R.actionTable.vpaAttempted) && ...
    all(R.actionTable.vpaFailure(R.actionTable.vpaAttempted)=="NONE") && ...
    all(R.actionTable.vpaNormalizedResidual( ...
    R.actionTable.vpaAttempted)>0), ...
    'R2Generalization: selected high-precision audit did not complete.');

% Repeated construction must preserve tolerance-stability fields exactly.
repeat = tcnsR2GeneralizationAudit(options);
assert(isequal(R.actionTable.toleranceStable, ...
    repeat.actionTable.toleranceStable) && ...
    isequal(R.toleranceTable.identifiable, ...
    repeat.toleranceTable.identifiable) && ...
    isequaln(R.toleranceTable.normalizedRowSpaceResidual, ...
    repeat.toleranceTable.normalizedRowSpaceResidual), ...
    'R2Generalization: tolerance-grid fields are not reproducible.');

% Reconstruct every reported minimum coalition and check all target rows.
for s = 1:height(R.senderTable)
    coalitionStrings = split(R.senderTable.minimumCoalitions(s),';');
    assert(~isempty(coalitionStrings) && coalitionStrings(1)~="", ...
        'R2Generalization: reported minimum coalition is empty.');
    members = str2double(split(coalitionStrings(1),'+'))';
    C = zeros(0,model.nState);
    for member = members
        C = [C;tcnsInformationLimitsSenderMap( ...
            model,member,[],0).currentMap]; %#ok<AGROW>
    end
    ids = find(catalog.sender==R.senderTable.sender(s));
    for a = reshape(ids,1,[])
        action = catalog.actionMap{a};
        ell = -2*action.successProbability/model.m* ...
            action.fullCrossTermCoefficient;
        assert(tcnsLinearIdentifiability(C,ell).identifiable, ...
            'R2Generalization: a reported coalition does not identify an action.');
    end
end

% Persisted authoritative CSV/JSON catalogs must retain all action rows.
latestRoot = fullfile('results','tcns_r2_generalization_validation');
if isfile(fullfile(latestRoot,'LATEST.txt'))
    latestId = strtrim(fileread(fullfile(latestRoot,'LATEST.txt')));
    latestDir = fullfile(latestRoot,latestId);
    % The singular-value column intentionally contains many semicolons, so
    % automatic delimiter detection can mistake ';' for the CSV delimiter.
    persistedCsv = readtable( ...
        fullfile(latestDir,'generalization_actions.csv'), ...
        'Delimiter',',','ReadVariableNames',true);
    persistedJson = jsondecode(fileread( ...
        fullfile(latestDir,'generalization_actions.json')));
    assert(height(persistedCsv)==numel(persistedJson), ...
        'R2Generalization: persisted CSV/JSON action row counts disagree.');
end

fprintf('  action rows       %d\n',height(R.actionTable));
fprintf('  sender rows       %d\n',height(R.senderTable));
fprintf('  tolerance rows    %d\n',height(R.toleranceTable));
fprintf('test_tcns_r2_generalization: PASS\n');
