%% TEST_TCNS_GATE5_FRONTIER_MATCHING Pareto and automatic matching contracts.

startup;

fprintf('\n=== TCNS Gate-5 frontier/matching checks ===\n\n');

T = table((1:7)',[8;7;7.5;5;5;6;3],[1;2;2;3;4;4;5], ...
    'VariableNames',{'id','error','cost'});
[F,mask] = tcnsParetoFrontier(T,'cost','error');
assert(isequal(F.id,[1;2;4;7]) && nnz(mask)==4, ...
    'Gate5: weak dominance or duplicate-cost handling is incorrect.');
assert(all(diff(F.cost)>0) && all(diff(F.error)<0), ...
    'Gate5: frontier ordering contract failed.');

A = table([1;2;3;4],[8;6;4;2], ...
    'VariableNames',{'cost','error'});
B = table([1.5;2.5;3.5;4.5],[7.5;5.5;3.5;1.5], ...
    'VariableNames',{'cost','error'});
M = tcnsMatchFrontiers(A,B,'cost','error',101);
assert(isequal(M.budgetOverlap,[1.5 4]) && ...
    isequal(M.performanceOverlap,[2 7.5]), ...
    'Gate5: shared interpolation domains are incorrect.');
assert(height(M.budgetMatched)==101 && ...
    height(M.performanceMatched)==101, ...
    'Gate5: fixed matching grid size is not respected.');
assert(max(abs(M.budgetMatched.errorDifferenceAminusB+0.5))<1e-14, ...
    'Gate5: budget-matched linear interpolation is incorrect.');
assert(max(abs(M.performanceMatched.costDifferenceAminusB+0.25))<1e-14, ...
    'Gate5: performance-matched inverse interpolation is incorrect.');

noOverlapCaught = false;
try
    tcnsMatchFrontiers(A,table([5;6],[1;0], ...
        'VariableNames',{'cost','error'}),'cost','error',11);
catch err
    noOverlapCaught = strcmp(err.identifier, ...
        'tcnsMatchFrontiers:NoBudgetOverlap');
end
assert(noOverlapCaught, ...
    'Gate5: matching silently extrapolated beyond observed budgets.');

fprintf('  exact weak-Pareto filtering                  PASS\n');
fprintf('  101-point bidirectional interpolation        PASS\n');
fprintf('  no-extrapolation contract                    PASS\n');
fprintf('test_tcns_gate5_frontier_matching: PASS\n');
