%% TEST_EXP23AO_MULTI_ORIGIN_ROUTING_CONTRACTS Frozen development design.
startup;

R=exp23aoMultiOriginRoutingRegistry();
assert(strcmp(R.version,'EXP23AO-MULTI-ORIGIN-ROUTED-CONTROL-v1')&& ...
    strcmp(R.experimentName,'exp23ao_multi_origin_routing')&& ...
    strcmp(R.validStatus, ...
    'MULTI_ORIGIN_ROUTED_CONTROL_DIAGNOSTIC_VALID')&& ...
    R.parentGatesPassed==19&&R.parentGatesTotal==19&& ...
    isequal(R.uniformRepetitionGrid,(1:7)')&& ...
    R.selectedUniformRepetitions==4);
assert(isequal(R.expectedLogicalPackets,[1 3 10 10 1])&& ...
    isequal(R.expectedRoutedPackets,[1 3 10 9 1])&& ...
    R.selectedPrepareAttempts==3&&R.selectedClaimAttempts==4&& ...
    R.selectedEvidencePrefixAttempts==2&& ...
    R.selectedCommitAttempts==2&&R.selectedMaximumFrames==11&& ...
    R.maximumTransactionFailure==1e-3&& ...
    R.postRequestTimeBudgetSec==6.5);
assert(R.expectedBundleRows==5&&R.expectedFrontierRows==7&& ...
    R.expectedMonteCarloRows==5&&R.requiredValidationContracts==16&& ...
    ~R.multiOriginRoutingValidated&&~R.managementRelayingValidated&& ...
    ~R.closedLoopManagementRelayingValidated&& ...
    ~R.repeatedOnlineRenewalValidated&&~R.freshSeedEvidence&& ...
    ~R.robustnessClaimPermitted&&~R.submissionClaimPermitted);

fprintf('test_exp23ao_multi_origin_routing_contracts: PASS\n');
