%% TEST_TCNS_R2_5_ADVERSARIAL_ARTIFACT Machine-readable audit invariants.

startup;
fprintf('\n=== TCNS R2.5 adversarial artifact checks ===\n\n');

root = fullfile('results','tcns_r2_5_adversarial_validation');
runId = strtrim(fileread(fullfile(root,'LATEST.txt')));
runDir = fullfile(root,runId);
registry = localRead(fullfile(runDir,'registry_adversarial_audit.csv'));
numeric = localRead(fullfile(runDir,'numerical_rank_diagnostic.csv'));
vpa = localRead(fullfile(runDir,'fragile_vpa_diagnostic.csv'));
witness = localRead(fullfile(runDir,'actual_witness_independent_replay.csv'));
normalization = localRead( ...
    fullfile(runDir,'practical_normalization_sensitivity.csv'));
coalition = localRead(fullfile(runDir,'coalition_independent_audit.csv'));
distribution = localRead(fullfile(runDir,'coalition_size_distribution.csv'));

assert(height(registry)==72 && all(registry.modelFeasible) && ...
    all(~registry.scientificResultExcluded) && ...
    all(registry.noSilentExclusion), ...
    'R25Artifact: registry coverage/exclusion invariant failed.');
assert(height(numeric)==6600 && numel(unique(numeric.tolerance))==5, ...
    'R25Artifact: tolerance diagnostic does not contain 6600 rows.');
assert(all(~numeric.identifiable) && ...
    all(numeric.storedRankMatch) && ...
    all(numeric.storedIdentifiabilityMatch), ...
    'R25Artifact: independent identifiability reconstruction disagrees.');
assert(all(numeric.normalizedBasisRankIncrease==1), ...
    'R25Artifact: normalized value row does not add one dimension.');
assert(any(numeric.rawAugmentedRankIncrease~=1), ...
    'R25Artifact: raw-rank counterexample unexpectedly disappeared.');
assert(all(vpa.failureReason=="NONE") && ...
    all(abs(vpa.doubleNormalizedResidual- ...
    vpa.vpaNormalizedResidual)<1e-12), ...
    'R25Artifact: fragile-case VPA cross-check failed.');
assert(height(witness)==10 && all(witness.replayPass) && ...
    all(witness.fixedResponseConsistent) && ...
    all(witness.qMinus<0 & witness.qPlus>0), ...
    'R25Artifact: independent actual-witness replay failed.');
assert(height(normalization)==10 && ...
    all(normalization.referenceValidCount==32) && ...
    all(normalization.failureReason=="NONE"), ...
    'R25Artifact: practical normalization audit is incomplete.');
assert(height(coalition)==448 && ...
    all(coalition.storedMinimumSizeMatch) && ...
    all(coalition.storedMultiplicityMatch) && ...
    all(coalition.allReportedCoalitionsIdentify) && ...
    all(coalition.allSmallerCoalitionsFail), ...
    'R25Artifact: independent coalition enumeration failed.');
assert(sum(distribution.frequency(distribution.scope=="ALL"))==448, ...
    'R25Artifact: coalition distribution does not cover every sender-cell.');

fprintf('  registry cells             %d\n',height(registry));
fprintf('  tolerance rows             %d\n',height(numeric));
fprintf('  independent witnesses      %d\n',height(witness));
fprintf('  coalition sender-cells     %d\n',height(coalition));
fprintf('test_tcns_r2_5_adversarial_artifact: PASS\n');


function T = localRead(path)
T = readtable(path,'Delimiter',',','ReadVariableNames',true, ...
    'TextType','string');
end
