%% TEST_EXP19A_POSTHOC_CONTRACTS Canonical descriptive-audit contract.

startup;
fprintf('\n============================================================\n');
fprintf('test_exp19a_posthoc_contracts\n');
fprintf('============================================================\n\n');
runDir=fullfile(projectRoot(),'results','exp19a_oracle_service_diagnostic', ...
    '2026-08-31_175039');
A=analyzeExp19APosthoc(runDir);
checks=cell(0,2);
checks(end+1,:)={height(A.contrasts)==6*6*6 && ...
    height(A.failures)==6*6 && height(A.pareto)==6*9, ...
    'audit retains every declared context/pair/metric row'};
checks(end+1,:)={all(A.contrasts.nPairs==30) && ...
    all(A.contrasts.complete==1), ...
    'all descriptive continuous contrasts use 30 paired seeds'};
checks(end+1,:)={strcmp(A.verdict.status, ...
    'ACCESS_HEADROOM_BUT_NO_REGISTERED_SEMANTIC_PROMOTION') && ...
    ~A.verdict.registeredVerdictChanged && ...
    ~A.verdict.semanticSchedulerPrimaryNoveltyPermitted && ...
    ~A.verdict.exp19bPermitted, ...
    'post-hoc audit cannot rewrite the registered development decision'};
checks(end+1,:)={A.verdict.boundaryAccessParetoInterval && ...
    A.verdict.n10ModerateAccessFailureRepair, ...
    'audit distinguishes access headroom from semantic promotion'};

flags=cellfun(@logical,checks(:,1));
for k=1:size(checks,1)
    if flags(k), tag='ok'; else, tag='FAIL'; end
    fprintf('    %-4s %s\n',tag,checks{k,2});
end
if ~all(flags)
    error('test_exp19a_posthoc_contracts: %d of %d checks failed.', ...
        nnz(~flags),numel(flags));
end
fprintf('\ntest_exp19a_posthoc_contracts: PASS (%d checks)\n',numel(flags));
