%% TEST_EXP23AP_ROUTED_STATE_MACHINE_CONTRACTS Frozen development design.
startup;

R=exp23apRoutedStateMachineRegistry();
assert(strcmp(R.version, ...
    'EXP23AP-ROUTED-STATE-MACHINE-COMMON-PHY-v1')&& ...
    strcmp(R.parentStatus, ...
    'MULTI_ORIGIN_ROUTED_CONTROL_DIAGNOSTIC_VALID')&& ...
    R.parentGatesPassed==16&&R.parentGatesTotal==16&& ...
    R.repetitionsPerHop==4&&R.prepareAttempts==3&& ...
    R.claimAttempts==4&&R.evidencePrefixAttempts==2&& ...
    R.commitAttempts==2&&R.maxFrames==11&& ...
    abs(R.transactionFailureUpperBound-0.00090955439743163613)<1e-16&& ...
    abs(R.conservativeTransactionTimeSec-5.0346184407376295)<1e-15&& ...
    R.postRequestTimeBudgetSec==6.5);
assert(R.normalTrials==500&&numel(unique(R.normalSeeds))==500&& ...
    ~ismember(R.faultSeed,R.normalSeeds)&&R.expectedFaultRows==3&& ...
    R.expectedBundleEnvelopeRows==5&&R.requiredValidationContracts==18);
assert(~R.managementRelayingValidated&& ...
    ~R.closedLoopManagementRelayingValidated&& ...
    ~R.repeatedOnlineRenewalValidated&&~R.freshSeedEvidence&& ...
    ~R.robustnessClaimPermitted&&~R.submissionClaimPermitted);

fprintf('test_exp23ap_routed_state_machine_contracts: PASS\n');
