function D=coherenceSelfRevocationDecision(advertisement,current,monitorStepSec)
%COHERENCESELFREVOCATIONDECISION Fail-silent local tube monitor.

requiredA={'p','v','positionError','velocityError', ...
    'accelerationBound','issuedAt','expiryTime','tupleVersion'};
requiredC={'p','v','a','time'};
if ~isstruct(advertisement) || ~all(isfield(advertisement,requiredA)) || ...
        ~isstruct(current) || ~all(isfield(current,requiredC))
    error('coherenceSelfRevocationDecision: incomplete input.');
end
p0=reshape(double(advertisement.p),1,[]);
v0=reshape(double(advertisement.v),1,[]);
p=reshape(double(current.p),1,[]);
v=reshape(double(current.v),1,[]);
a=reshape(double(current.a),1,[]);
if ~isequal(size(p0),size(v0),size(p),size(v),size(a)) || ...
        any(~isfinite([p0 v0 p v a]))
    error('coherenceSelfRevocationDecision: invalid state dimension.');
end
values=[advertisement.positionError advertisement.velocityError ...
    advertisement.accelerationBound advertisement.issuedAt ...
    advertisement.expiryTime advertisement.tupleVersion current.time ...
    monitorStepSec];
if any(~isfinite(values)) || advertisement.positionError<0 || ...
        advertisement.velocityError<0 || ...
        advertisement.accelerationBound<0 || monitorStepSec<0 || ...
        advertisement.expiryTime<advertisement.issuedAt || ...
        current.time<advertisement.issuedAt
    error('coherenceSelfRevocationDecision: invalid bounds/times.');
end

elapsed=current.time-advertisement.issuedAt;
nextElapsed=elapsed+monitorStepSec;
center=p0+v0*elapsed;
nextCenter=p0+v0*nextElapsed;
radius=tubeRadius(elapsed);
nextRadius=tubeRadius(nextElapsed);
predictedNext=p+v*monitorStepSec+0.5*a*monitorStepSec^2;
currentDeviation=norm(p-center);
nextDeviation=norm(predictedNext-nextCenter);
accelerationViolation=norm(a)>advertisement.accelerationBound+1e-12;
currentOutside=currentDeviation>radius+1e-12;
nextOutside=nextDeviation>nextRadius+1e-12;
unexpired=current.time<advertisement.expiryTime-1e-12;
selfRevoke=unexpired && (accelerationViolation || currentOutside || nextOutside);
scheduledPermitted=unexpired && ~selfRevoke;

D=struct('version','COHERENCE-SELF-REVOCATION-v1', ...
    'tupleVersion',advertisement.tupleVersion,'elapsedSec',elapsed, ...
    'monitorStepSec',monitorStepSec,'currentTubeRadius',radius, ...
    'nextTubeRadius',nextRadius,'currentDeviation',currentDeviation, ...
    'nextDeviation',nextDeviation, ...
    'accelerationViolation',accelerationViolation, ...
    'currentOutsideTube',currentOutside,'nextOutsideTube',nextOutside, ...
    'leaseUnexpired',unexpired,'selfRevokeRequired',selfRevoke, ...
    'scheduledUsePermitted',scheduledPermitted, ...
    'revokeDeliveryRequiredForSafety',false, ...
    'futureRandomReads',0,'receiverTruthDecisionReads',0);

    function r=tubeRadius(tau)
        r=advertisement.positionError+ ...
            advertisement.velocityError*tau+ ...
            0.5*advertisement.accelerationBound*tau^2;
    end

end
