function D=coherenceRevokeCacheDecision( ...
    cachedVersion,messageOldVersion,messageNewVersion,authenticated)
%COHERENCEREVOKECACHEDECISION Validate a version-bound REVOKE.

validScalar=@(x) isscalar(x) && isfinite(x) && x>=1 && x==floor(x);
wellFormed=validScalar(messageOldVersion) && ...
    validScalar(messageNewVersion) && ...
    messageNewVersion==messageOldVersion+1;
accept=logical(authenticated) && wellFormed && ...
    validScalar(cachedVersion) && cachedVersion==messageOldVersion;
D=struct('accept',accept,'authenticated',logical(authenticated), ...
    'wellFormed',wellFormed,'cachedVersion',cachedVersion, ...
    'messageOldVersion',messageOldVersion, ...
    'messageNewVersion',messageNewVersion, ...
    'createsValidity',false);

end
