function C=evaluateSweptRadialContractionContract( ...
    nominalRelative,actualRelative,physicalCertificate, ...
    radialContractionBound,interferenceRadius)
%EVALUATESWEPTRADIALCONTRACTIONCONTRACT One-sided conflict certificate.
%
% For every pair omitted from physicalCertificate, the construction premise
% is
%   ||rbar_ij|| > interferenceRadius + b_ij.
% If the realized inward distance contraction additionally satisfies
%   [||rbar_ij||-||r_ij||]_+ <= b_ij,
% then ||r_ij|| > interferenceRadius. Tangential and outward tracking errors
% do not consume this conflict-safety budget. Pairs already included in the
% certificate require no contraction bound.

p=double(nominalRelative); x=double(actualRelative);
if ~ismatrix(p)||isempty(p)||~isequal(size(p),size(x))|| ...
        any(~isfinite(p),'all')||any(~isfinite(x),'all')
    error('evaluateSweptRadialContractionContract: invalid positions.');
end
N=size(p,1); graph=logical(physicalCertificate);
bound=double(radialContractionBound);
if ~isequal(size(graph),[N N])||any(diag(graph))|| ...
        ~isequal(graph,graph')||~isequal(size(bound),[N N])|| ...
        any(~isfinite(bound),'all')||any(bound<0,'all')|| ...
        any(abs(diag(bound))>0)||any(bound(~eye(N))<=0)|| ...
        norm(bound-bound','fro')>1e-12|| ...
        ~isscalar(interferenceRadius)||~isfinite(interferenceRadius)|| ...
        interferenceRadius<0
    error('evaluateSweptRadialContractionContract: invalid contract.');
end

nominalDistance=zeros(N); actualDistance=zeros(N); vectorError=zeros(N);
for i=1:N
    for j=i+1:N
        nominalDistance(i,j)=norm(p(i,:)-p(j,:));
        actualDistance(i,j)=norm(x(i,:)-x(j,:));
        vectorError(i,j)=norm((x(i,:)-x(j,:))-(p(i,:)-p(j,:)));
        nominalDistance(j,i)=nominalDistance(i,j);
        actualDistance(j,i)=actualDistance(i,j);
        vectorError(j,i)=vectorError(i,j);
    end
end
inward=max(0,nominalDistance-actualDistance);
upper=triu(true(N),1); omitted=upper&~graph;
actualGraph=actualDistance<=interferenceRadius;
actualGraph(1:N+1:end)=false;
tol=1e-12;
premise=all(nominalDistance(omitted)> ...
    interferenceRadius+bound(omitted)-tol);
radialSatisfied=all(inward(omitted)<=bound(omitted)+tol);
actualSubset=~any(actualGraph(omitted));
if any(omitted,'all')
    radialRatio=max(inward(omitted)./bound(omitted));
    vectorRatio=max(vectorError(omitted)./bound(omitted));
    minimumMargin=min(actualDistance(omitted)-interferenceRadius);
else
    radialRatio=0; vectorRatio=0; minimumMargin=inf;
end
theoremCertified=premise&&radialSatisfied;
implicationExact=~theoremCertified||actualSubset;
if ~implicationExact
    error(['evaluateSweptRadialContractionContract: theorem ' ...
        'implication violated.']);
end

C=struct('version','SWEPT-RADIAL-CONTRACTION-CONTRACT-v1', ...
    'N',N,'interferenceRadius',interferenceRadius, ...
    'constructionPremiseSatisfied',double(premise), ...
    'radialBoundSatisfied',double(radialSatisfied), ...
    'theoremCertified',double(theoremCertified), ...
    'actualPhysicalSubset',double(actualSubset), ...
    'implicationExact',double(implicationExact), ...
    'omittedPairCount',nnz(omitted), ...
    'maximumRadialContractionRatio',radialRatio, ...
    'maximumVectorErrorRatio',vectorRatio, ...
    'minimumOmittedPairMargin',minimumMargin, ...
    'nominalDistance',nominalDistance,'actualDistance',actualDistance, ...
    'inwardRadialContraction',inward,'vectorTrackingError',vectorError, ...
    'actualPhysicalGraph',actualGraph, ...
    'hashExact',realizationHash([p(:);x(:);double(graph(:));bound(:); ...
    interferenceRadius;double(premise);double(radialSatisfied); ...
    double(actualSubset)]));

end
