function T=generateReceiverLiftedRoutedClosureTrace(seedValue,M,C,routeSpec)
%GENERATERECEIVERLIFTEDROUTEDCLOSURETRACE Predraw routed link outcomes.

required={'linkErasureProbability','repetitionsPerHop'};
if ~isscalar(seedValue)||~isfinite(seedValue)||seedValue~=floor(seedValue)|| ...
        ~isstruct(M)||~isscalar(M)||~isfield(M,'N')|| ...
        ~isstruct(C)||~isscalar(C)||~isfield(C,'maxFrames')|| ...
        ~isstruct(routeSpec)||~isscalar(routeSpec)|| ...
        ~all(isfield(routeSpec,required))
    error('generateReceiverLiftedRoutedClosureTrace: invalid input.');
end
F=C.maxFrames; N=M.N; r=routeSpec.repetitionsPerHop;
if ~isscalar(r)||~isfinite(r)||r<1||r~=floor(r)
    error('generateReceiverLiftedRoutedClosureTrace: invalid repetition.');
end
stream=RandStream('mt19937ar','Seed',seedValue);
kinds={'prepare','quiescent','claim','lockproof','response','commit'};
linkUniform=struct();
for k=1:numel(kinds)
    linkUniform.(kinds{k})=rand(stream,F,N,N,N,r);
end
T=struct('version','RECEIVER-LIFTED-ROUTED-CLOSURE-TRACE-v1', ...
    'seed',seedValue,'linkUniform',linkUniform, ...
    'actualGraphAfter',repmat(reshape(M.newGraph,1,N,N),F,1,1), ...
    'prepareVersion',C.transactionVersion*ones(F,1), ...
    'prepareDigest',M.hashExact*ones(F,1), ...
    'quietVersion',C.transactionVersion*ones(F,N), ...
    'quietDigest',M.hashExact*ones(F,N), ...
    'claimVersion',C.transactionVersion*ones(F,N), ...
    'claimDigest',M.hashExact*ones(F,N), ...
    'lockProofVersion',C.transactionVersion*ones(F,N), ...
    'lockProofDigest',M.hashExact*ones(F,N), ...
    'responseVersion',C.transactionVersion*ones(F,N), ...
    'responseDigest',M.hashExact*ones(F,N), ...
    'commitVersion',C.transactionVersion*ones(F,1), ...
    'commitDigest',M.hashExact*ones(F,1), ...
    'repetitionsPerHop',r);
T.hashExact=receiverLiftedRoutedClosureTraceHash(T);

end
