function [net, txState] = initAckChannelState(net, P, V, leader, cfg)
%INITACKCHANNELSTATE Set up the reverse ACK channel and causal transmitter memory.
%
%   [net, txState] = initAckChannelState(net, P, V, leader, cfg)
%
% Adds to net:
%   ackQueue{i,j}        ACKs in flight from receiver i back to transmitter j
%   leaderAckQueue{i}    ACKs in flight from pinned follower i back to the leader
%   ack* counters        protocol accounting and the six causality invariants
%
% Returns txState, the ONLY state the transmitter is allowed to consult when
% deciding whether to transmit. It contains no receiver register: every field
% is written exclusively by deliverAckPackets from ACK packets that actually
% arrived.
%
% Contrast with simSwarmAoIAware/initializeAoITxState, which seeds ackGenTime
% straight from net.genTime. Here it is seeded from a local constant, so the
% transmitter never reads receiver state, not even once at t = 0.

N = cfg.swarm.N;


%% ============================================================
% Reverse channel queues
% ============================================================

net.ackQueue = cell(N,N);

for i = 1:N
    for j = 1:N
        net.ackQueue{i,j} = {};
    end
end


net.leaderAckQueue = cell(N,1);

for i = 1:N
    net.leaderAckQueue{i} = {};
end


%% ============================================================
% Protocol accounting
% ============================================================

net.ackTxCount    = 0;      % ACKs generated by receivers
net.ackRxCount    = 0;      % ACKs that reached the transmitter
net.ackDropCount  = 0;      % ACKs lost on the reverse channel
net.ackUpdateCount = 0;     % ACKs that advanced transmitter memory

% Expected to be > 0 under impairment: a late ACK superseded by a newer one.
% Discarding these is correct behaviour, not a violation.
net.staleAckDiscardedCount = 0;


%% ============================================================
% The six causality invariants
%
% Every one of these must be exactly 0. They are not diagnostics;
% they are the definition of a causal protocol.
% ============================================================

net.ackBeforeAcceptCount   = 0;   % ACK reached sender before it was created
net.ackForDroppedDataCount = 0;   % ACK for a DATA packet the channel dropped
net.senderRollbackCount    = 0;   % attempt to move ackGenTime backwards
net.futureGenTimeCount     = 0;   % a timestamp from the future
net.staleAckAcceptedCount  = 0;   % a stale ACK that still modified state
net.unknownSeqAckCount     = 0;   % ACK matching no attempt the sender made


%% ============================================================
% Transmitter memory
%
% ackPos / ackVel / ackGenTime describe what the transmitter BELIEVES the
% receiver holds. Under loss and delay this belief is stale, and that
% staleness is the whole point of the experiment.
% ============================================================

txState.ackPos     = nan(N,N,3);
txState.ackVel     = nan(N,N,3);
txState.ackGenTime = nan(N,N);
txState.lastTxTime = zeros(N,N);
txState.nextSeq    = ones(N,N);
txState.pending    = cell(N,N);


for i = 1:N
    for j = 1:N

        txState.pending{i,j} = emptyPendingRecord();

        if cfg.swarm.A(i,j) ~= 0

            % The t = 0 state is treated as already known to both ends,
            % matching every other simulator in the project. Seeded from
            % the local copy of P/V, never from net.
            txState.ackPos(i,j,:) = P(j,:);
            txState.ackVel(i,j,:) = V(j,:);
            txState.ackGenTime(i,j) = 0;

        end

    end
end


%% ============================================================
% Leader link transmitter memory
% ============================================================

txState.leaderAckPos     = nan(N,3);
txState.leaderAckVel     = nan(N,3);
txState.leaderAckGenTime = nan(N,1);
txState.leaderLastTxTime = zeros(N,1);
txState.leaderNextSeq    = ones(N,1);
txState.leaderPending    = cell(N,1);


for i = 1:N

    txState.leaderPending{i} = emptyPendingRecord();

    if i >= 2 && cfg.swarm.pin(i)

        txState.leaderAckPos(i,:) = leader.pos';
        txState.leaderAckVel(i,:) = leader.vel';
        txState.leaderAckGenTime(i) = 0;

    end

end

end


%% ============================================================
% LOCAL FUNCTION
% ============================================================

function q = emptyPendingRecord()
%EMPTYPENDINGRECORD A 0x0 struct array with the pending-packet fields.

q = struct( ...
    'genTime',  {}, ...
    'seq',      {}, ...
    'pos',      {}, ...
    'vel',      {}, ...
    'dropped',  {});

end
