function B=receiverLiftedClosureReliabilityCertificate( ...
    M,C,evidencePrefixAttempts)
%RECEIVERLIFTEDCLOSURERELIABILITYCERTIFICATE Finite transaction bound.
%
% The certificate reserves: (i) the complete PREPARE/QUIET retry window,
% (ii) an evidence prefix of CLAIM opportunities, (iii) a disjoint RESPONSE
% suffix, and (iv) the complete COMMIT retry window. Under independent
% receiver-level erasures, a union bound covers every required delivery.

if ~isstruct(M)||~isscalar(M)||~isfield(M,'admissible')||~M.admissible
    error('receiverLiftedClosureReliabilityCertificate: admissible M required.');
end
required={'maxFrames','prepareFrame','prepareDenseRetryFrames', ...
    'prepareMaxBackoffFrames','prepareRetryAttemptLimit', ...
    'claimEligibilityDelayFrames','lockProofRepeatFrames', ...
    'claimBackoffEnabled','claimDenseRetryFrames', ...
    'claimMaxBackoffFrames','claimRetryAttemptLimit', ...
    'commitRetryAttemptLimit'};
for k=1:numel(required)
    if ~isfield(C,required{k})||~isscalar(C.(required{k}))|| ...
            ~isfinite(C.(required{k}))||C.(required{k})<0
        error('receiverLiftedClosureReliabilityCertificate: invalid C.%s.', ...
            required{k});
    end
end
if ~isscalar(evidencePrefixAttempts)||~isfinite(evidencePrefixAttempts)|| ...
        evidencePrefixAttempts<1|| ...
        evidencePrefixAttempts~=floor(evidencePrefixAttempts)
    error(['receiverLiftedClosureReliabilityCertificate: invalid ' ...
        'evidence prefix.']);
end

P=struct('maxFrames',C.maxFrames,'eligibleFrame',C.prepareFrame, ...
    'claimBackoffEnabled',true, ...
    'claimDenseRetryFrames',C.prepareDenseRetryFrames, ...
    'claimMaxBackoffFrames',C.prepareMaxBackoffFrames, ...
    'claimRetryAttemptLimit',C.prepareRetryAttemptLimit);
[~,preparePolicy]=localUnionMigrationClaimSchedule(P);
latestPrepareFrame=preparePolicy.lastOpportunityFrame;
worstEligibleFrame=latestPrepareFrame+1+C.claimEligibilityDelayFrames;
claimPolicy=struct('opportunityCount',0,'lastOpportunityFrame',NaN, ...
    'scheduleHashExact',NaN); claimDue=false(C.maxFrames,1);
if worstEligibleFrame<=C.maxFrames
    Q=C; Q.eligibleFrame=worstEligibleFrame;
    [claimDue,claimPolicy]=localUnionMigrationClaimSchedule(Q);
end
claimFrames=find(claimDue); claimCount=numel(claimFrames);
responseSuffixAttempts=max(0,claimCount-evidencePrefixAttempts);
if claimCount>=evidencePrefixAttempts
    evidenceLastFrame=claimFrames(evidencePrefixAttempts);
else
    evidenceLastFrame=inf;
end
proofLastFrame=min(C.maxFrames, ...
    worstEligibleFrame+C.lockProofRepeatFrames-1);
evidenceProofFrames=max(0,proofLastFrame-worstEligibleFrame+1);
commitFramesReserved=0;
if ~isempty(claimFrames)
    commitFramesReserved=C.maxFrames-claimFrames(end)+1;
end
horizonFeasible=preparePolicy.opportunityCount== ...
    C.prepareRetryAttemptLimit&&claimCount==C.claimRetryAttemptLimit&& ...
    responseSuffixAttempts>=1&& ...
    evidenceLastFrame<=proofLastFrame&& ...
    commitFramesReserved>=C.commitRetryAttemptLimit;

pPrepare=probability(C,'prepareErasureProbability');
pQuiet=probability(C,'quietErasureProbability');
pClaim=probability(C,'claimErasureProbability');
pProof=probability(C,'lockProofErasureProbability');
pResponse=probability(C,'responseErasureProbability');
pCommit=probability(C,'commitErasureProbability');

affected=logical(M.affectedMask(:));
remoteAffected=max(0,M.affectedCount-1);
prepareRounds=preparePolicy.opportunityCount;
prepareNodeFailure=pPrepare^prepareRounds;
for firstSuccess=1:prepareRounds
    prepareNodeFailure=prepareNodeFailure+ ...
        pPrepare^(firstSuccess-1)*(1-pPrepare)* ...
        pQuiet^(prepareRounds-firstSuccess+1);
end
prepareFailure=min(1,remoteAffected*prepareNodeFailure);

claimObligations=0; proofObligations=0; responseObligations=0;
for edge=1:M.incidentUnionEdgeCount
    witness=M.incidentEdgeWitness(edge);
    endpoints=[M.incidentEdgeA(edge) M.incidentEdgeB(edge)];
    for endpoint=endpoints
        if endpoint==witness, continue; end
        if affected(endpoint)
            claimObligations=claimObligations+1;
        else
            proofObligations=proofObligations+1;
        end
    end
    if witness~=M.initiator
        responseObligations=responseObligations+1;
    end
end
evidenceFailure=min(1, ...
    claimObligations*pClaim^evidencePrefixAttempts+ ...
    proofObligations*pProof^evidenceProofFrames);
responseFailure=min(1, ...
    responseObligations*pResponse^responseSuffixAttempts);
commitFailure=min(1,remoteAffected* ...
    pCommit^C.commitRetryAttemptLimit);
if horizonFeasible
    unionFailure=min(1,prepareFailure+evidenceFailure+ ...
        responseFailure+commitFailure);
else
    unionFailure=1;
end

B=struct('version','RECEIVER-LIFTED-CLOSURE-RELIABILITY-v1', ...
    'assumption','independent receiver-level control erasures', ...
    'horizonFeasible',double(horizonFeasible), ...
    'latestPrepareFrame',latestPrepareFrame, ...
    'worstEligibleFrame',worstEligibleFrame, ...
    'prepareOpportunityCount',preparePolicy.opportunityCount, ...
    'claimOpportunityCount',claimCount, ...
    'evidencePrefixAttempts',evidencePrefixAttempts, ...
    'evidenceProofFrames',evidenceProofFrames, ...
    'responseSuffixAttempts',responseSuffixAttempts, ...
    'commitFramesReserved',commitFramesReserved, ...
    'remoteAffectedCount',remoteAffected, ...
    'prepareNodeFailureUpperBound',prepareNodeFailure, ...
    'claimObligations',claimObligations, ...
    'proofObligations',proofObligations, ...
    'responseObligations',responseObligations, ...
    'prepareFailureUpperBound',prepareFailure, ...
    'evidenceFailureUpperBound',evidenceFailure, ...
    'responseFailureUpperBound',responseFailure, ...
    'commitFailureUpperBound',commitFailure, ...
    'unionFailureUpperBound',unionFailure, ...
    'completionProbabilityLowerBound',1-unionFailure, ...
    'prepareScheduleHashExact',preparePolicy.scheduleHashExact, ...
    'claimScheduleHashExact',claimPolicy.scheduleHashExact, ...
    'hashExact',realizationHash([preparePolicy.scheduleHashExact; ...
    claimPolicy.scheduleHashExact;evidencePrefixAttempts; ...
    remoteAffected;claimObligations;proofObligations; ...
    responseObligations;prepareFailure;evidenceFailure; ...
    responseFailure;commitFailure;unionFailure]));

end


function p=probability(C,name)

p=0; if isfield(C,name), p=C.(name); end
if ~isscalar(p)||~isfinite(p)||p<0||p>1
    error('receiverLiftedClosureReliabilityCertificate: invalid C.%s.',name);
end

end
