function O=simulateMultiOriginRoutedControl(S,linkUniform, ...
    erasureProbability,packetBytes,phyRateBps,guardSec,maxPacketBytes)
%SIMULATEMULTIORIGINROUTEDCONTROL Packet-isolated common-PHY route replay.

required={'N','packetCount','routePlans','repetitionsPerPacket', ...
    'directReach','physicalInterference','taskCount','taskPacket', ...
    'taskSender','taskChildren','taskRepetitions','taskStartSlot', ...
    'taskEndSlot','slotTaskMask','reservedSlotCount','conflictFree', ...
    'precedenceExact','admissible','hashExact'};
if ~isstruct(S)||~isscalar(S)||~all(isfield(S,required))|| ...
        ~S.admissible||~S.conflictFree||~S.precedenceExact
    error('simulateMultiOriginRoutedControl: admissible schedule required.');
end
K=S.packetCount; N=S.N;
if ~iscell(linkUniform)||numel(linkUniform)~=K
    error('simulateMultiOriginRoutedControl: one draw tensor per packet.');
end
p=reshape(double(erasureProbability),[],1);
if isscalar(p), p=repmat(p,K,1); end
bytes=reshape(double(packetBytes),[],1);
if nargin<7||isempty(maxPacketBytes), maxPacketBytes=max(bytes); end
if numel(p)~=K||numel(bytes)~=K||any(~isfinite(p))||any(p<0|p>1)|| ...
        any(~isfinite(bytes))||any(bytes<1)||any(bytes~=floor(bytes))|| ...
        ~isscalar(maxPacketBytes)||~isfinite(maxPacketBytes)|| ...
        maxPacketBytes<max(bytes)||maxPacketBytes~=floor(maxPacketBytes)|| ...
        ~isscalar(phyRateBps)||~isfinite(phyRateBps)||phyRateBps<=0|| ...
        ~isscalar(guardSec)||~isfinite(guardSec)||guardSec<0
    error('simulateMultiOriginRoutedControl: invalid physical inputs.');
end
U=reshape(linkUniform,[],1);
for k=1:K
    U{k}=double(U{k}); repetitions=S.repetitionsPerPacket(k);
    if size(U{k},1)~=N||size(U{k},2)~=N|| ...
            size(U{k},3)~=repetitions||ndims(U{k})>3|| ...
            any(~isfinite(U{k}),'all')||any(U{k}<0|U{k}>1,'all')
        error('simulateMultiOriginRoutedControl: invalid draw tensor.');
    end
end

known=false(K,N); recipients=false(K,N); sources=zeros(K,1);
for k=1:K
    P=S.routePlans{k}; sources(k)=P.source;
    known(k,P.source)=true; recipients(k,:)=P.recipientMask;
end
taskActive=false(S.taskCount,1); taskTransmissions=zeros(S.taskCount,1);
packetAttempts=zeros(K,1); packetPhysicalBytes=zeros(K,1);
attempts=0; physicalBytes=0; busySlots=0; linkReads=0;
successLinks=0; erasedLinks=0; collisionRecipients=0;
slotAttemptCount=zeros(S.reservedSlotCount,1);
for slot=1:S.reservedSlotCount
    starting=find(S.taskStartSlot==slot);
    for task=reshape(starting,1,[])
        taskActive(task)=known(S.taskPacket(task),S.taskSender(task));
    end
    scheduled=find(S.slotTaskMask(slot,:));
    active=scheduled(taskActive(scheduled));
    if isempty(active), continue; end
    busySlots=busySlots+1; slotAttemptCount(slot)=numel(active);
    newKnown=false(K,N);
    for task=reshape(active,1,[])
        k=S.taskPacket(task); sender=S.taskSender(task);
        repetition=slot-S.taskStartSlot(task)+1;
        attempts=attempts+1; packetAttempts(k)=packetAttempts(k)+1;
        physicalBytes=physicalBytes+bytes(k);
        packetPhysicalBytes(k)=packetPhysicalBytes(k)+bytes(k);
        taskTransmissions(task)=taskTransmissions(task)+1;
        receivers=find(S.taskChildren(:,task));
        for receiver=reshape(receivers,1,[])
            otherTasks=active(active~=task);
            otherSenders=S.taskSender(otherTasks);
            detectable=reshape(S.physicalInterference( ...
                receiver,otherSenders)|S.directReach( ...
                receiver,otherSenders),[],1);
            collision=any(otherSenders==receiver|detectable);
            if collision
                collisionRecipients=collisionRecipients+1; continue;
            end
            linkReads=linkReads+1;
            if U{k}(receiver,sender,repetition)>p(k)
                newKnown(k,receiver)=true; successLinks=successLinks+1;
            else
                erasedLinks=erasedLinks+1;
            end
        end
    end
    known=known|newKnown;
end
packetDelivered=false(K,1);
for k=1:K
    packetDelivered(k)=all(known(k,recipients(k,:)));
end
plannedAttemptBound=sum(S.taskRepetitions);
offeredAirtime=8*physicalBytes/phyRateBps;
slotDuration=8*maxPacketBytes/phyRateBps+guardSec;
O=struct('version','MULTI-ORIGIN-ROUTED-CONTROL-REPLAY-v1', ...
    'scheduleHash',S.hashExact,'packetDelivered',packetDelivered, ...
    'allPacketsDelivered',double(all(packetDelivered)), ...
    'knownPacketNode',known,'packetSource',sources, ...
    'taskActive',taskActive,'taskTransmissions',taskTransmissions, ...
    'packetAttempts',packetAttempts,'packetPhysicalBytes', ...
    packetPhysicalBytes,'attempts',attempts,'physicalBytes',physicalBytes, ...
    'offeredAirtimeSec',offeredAirtime,'busySlots',busySlots, ...
    'channelBusyAirtimeSec',busySlots*8*maxPacketBytes/phyRateBps, ...
    'reservedDurationSec',S.reservedSlotCount*slotDuration, ...
    'plannedAttemptBound',plannedAttemptBound, ...
    'attemptBoundSatisfied',double(attempts<=plannedAttemptBound), ...
    'slotAttemptCount',slotAttemptCount,'linkRandomReads',linkReads, ...
    'successfulLinks',successLinks,'erasedLinks',erasedLinks, ...
    'collisionRecipients',collisionRecipients, ...
    'crossPacketStateWrites',0,'duplicateForwards',0, ...
    'futureRandomReads',0,'receiverTruthDecisionReads',0, ...
    'hashExact',realizationHash([S.hashExact;p;bytes;maxPacketBytes; ...
    phyRateBps;guardSec;double(known(:));double(taskActive); ...
    taskTransmissions;packetAttempts;packetPhysicalBytes;attempts; ...
    physicalBytes;busySlots;slotAttemptCount;linkReads;successLinks; ...
    erasedLinks;collisionRecipients]));

end
