function B=slottedManagementFloodReliabilityCertificate( ...
    plan,linkErasureProbability,independentFloodAttempts)
%SLOTTEDMANAGEMENTFLOODRELIABILITYCERTIFICATE Unique-path flood bound.
%
% Recipient r at depth h_r receives one tree flood exactly when its h_r
% parent links succeed, so q_r=(1-p)^h_r. Repeating the complete flood A
% times with independent link draws gives failure (1-q_r)^A. A union bound
% covers the multicast set. Conditional relay silence can only reduce the
% physical attempt count below the planned tree-transmitter bound.

required={'N','admissible','recipientMask','depth','transmitterMask', ...
    'plannedTransmitterCount','treeEdgeCount','reservedSlotCount','hashExact'};
if ~isstruct(plan)||~isscalar(plan)||~all(isfield(plan,required))|| ...
        ~plan.admissible
    error(['slottedManagementFloodReliabilityCertificate: ' ...
        'admissible plan required.']);
end
if ~isscalar(linkErasureProbability)|| ...
        ~isfinite(linkErasureProbability)||linkErasureProbability<0|| ...
        linkErasureProbability>1|| ...
        ~isscalar(independentFloodAttempts)|| ...
        ~isfinite(independentFloodAttempts)||independentFloodAttempts<1|| ...
        independentFloodAttempts~=floor(independentFloodAttempts)
    error('slottedManagementFloodReliabilityCertificate: invalid input.');
end

recipients=find(plan.recipientMask);
depth=plan.depth(recipients);
singleDelivery=(1-linkErasureProbability).^depth;
recipientFailure=(1-singleDelivery).^independentFloodAttempts;
unionFailure=min(1,sum(recipientFailure));
expectedTransmittersPerFlood=sum( ...
    (1-linkErasureProbability).^plan.depth(plan.transmitterMask));
B=struct('version','SLOTTED-MANAGEMENT-FLOOD-RELIABILITY-v1', ...
    'assumption','independent per-link erasures across links and floods', ...
    'planHash',plan.hashExact,'linkErasureProbability', ...
    linkErasureProbability,'independentFloodAttempts', ...
    independentFloodAttempts,'recipientNode',recipients, ...
    'recipientDepth',depth,'singleFloodDeliveryProbability', ...
    singleDelivery,'recipientFailureUpperBound',recipientFailure, ...
    'multicastFailureUnionUpperBound',unionFailure, ...
    'multicastSuccessLowerBound',1-unionFailure, ...
    'maximumPhysicalAttemptBound',independentFloodAttempts* ...
    plan.plannedTransmitterCount, ...
    'expectedTransmittersPerFlood',expectedTransmittersPerFlood, ...
    'treeEdgeCount',plan.treeEdgeCount, ...
    'reservedSlotsPerFlood',plan.reservedSlotCount, ...
    'hashExact',realizationHash([plan.hashExact;linkErasureProbability; ...
    independentFloodAttempts;recipients;depth;singleDelivery; ...
    recipientFailure;unionFailure;expectedTransmittersPerFlood]));

end
