function aggregate = aggregateTcnsFrontierRuns(raw,arms,expectedSeedCount)
%AGGREGATETCNSFRONTIERRUNS One stable aggregate row per declared arm.

if ~istable(raw)
    error('aggregateTcnsFrontierRuns:Type','raw must be a table.');
end
validateattributes(expectedSeedCount,{'numeric'}, ...
    {'real','finite','integer','positive','scalar'}, ...
    mfilename,'expectedSeedCount',3);

prototype = struct('armId',"",'methodFamily',"",'method',"", ...
    'parameterName',"",'parameterValue',NaN,'period_s',NaN, ...
    'epsilonPosition_m',NaN,'seedCount',NaN,'failedRuns',NaN, ...
    'divergedRuns',NaN,'saturatedRuns',NaN, ...
    'meanFormationRMSE_m',NaN,'stdFormationRMSE_m',NaN, ...
    'meanPrimaryFormationRMSE_m',NaN,'stdPrimaryFormationRMSE_m',NaN, ...
    'meanEvaluationCost025PerChannel_Hz',NaN, ...
    'stdEvaluationCost025PerChannel_Hz',NaN, ...
    'meanCost025PerChannel_Hz',NaN,'stdCost025PerChannel_Hz',NaN, ...
    'meanEventAllocationRatio',NaN,'meanControlViolationRatio',NaN);
out = repmat(prototype,numel(arms),1);

for q = 1:numel(arms)
    r = raw(raw.armId==arms(q).id,:);
    good = ~r.failed;
    out(q).armId = arms(q).id;
    out(q).methodFamily = arms(q).family;
    out(q).method = arms(q).label;
    out(q).parameterName = arms(q).parameterName;
    out(q).parameterValue = arms(q).parameterValue;
    out(q).period_s = arms(q).period_s;
    out(q).epsilonPosition_m = arms(q).epsilon_m;
    out(q).seedCount = height(r);
    out(q).failedRuns = nnz(~good);
    out(q).divergedRuns = nnz(r.diverged);
    if nnz(good)==expectedSeedCount
        out(q).meanFormationRMSE_m = mean(r.formationRMSE_m(good));
        out(q).stdFormationRMSE_m = std(r.formationRMSE_m(good));
        out(q).meanPrimaryFormationRMSE_m = ...
            mean(r.primaryFormationRMSE_m(good));
        out(q).stdPrimaryFormationRMSE_m = ...
            std(r.primaryFormationRMSE_m(good));
        out(q).meanEvaluationCost025PerChannel_Hz = ...
            mean(r.evaluationCost025PerChannel_Hz(good));
        out(q).stdEvaluationCost025PerChannel_Hz = ...
            std(r.evaluationCost025PerChannel_Hz(good));
        out(q).meanCost025PerChannel_Hz = ...
            mean(r.cost025PerChannel_Hz(good));
        out(q).stdCost025PerChannel_Hz = ...
            std(r.cost025PerChannel_Hz(good));
        out(q).meanEventAllocationRatio = ...
            mean(r.eventAllocationRatio(good),'omitnan');
        out(q).meanControlViolationRatio = ...
            mean(r.controlViolationRatio(good),'omitnan');
        out(q).saturatedRuns = nnz(r.saturationFraction(good)>0);
    end
end
aggregate = struct2table(out);

end
