function R = exp14Registry()
%EXP14REGISTRY Immutable design registry for the EXP14 holdout.

R.version = 'EXP14-FROZEN-v1';
R.frozenDate = '2026-08-29';
R.seedStatus = 'unopened when this registry was written';
R.seeds = (14014001:14014100)';
R.bootstrapReplicates = 10000;
R.bootstrapSeed = 14141414;

R.scenarios = exp14ChannelScenarios();

R.frontiers = struct( ...
    'id',{'periodic','state','aoi','aoci','belief','proposed'}, ...
    'label',{'Periodic','State-event','Causal AoI-only', ...
    'AoCI-inspired','Delayed-ACK belief','Causal-Broadcast'}, ...
    'values',{[5 10 12.5 20 25],[0.5 0.75 1 1.5 2], ...
    [0.06 0.09 0.12 0.18 0.24],[0.5 0.75 1 1.5 2], ...
    [0.06 0.09 0.12 0.18 0.24],[0.5 0.75 1 1.5 2]});

R.mechanisms = struct( ...
    'id',{'causal-unicast','broadcast-data-only','broadcast-standalone', ...
    'broadcast-piggyback','broadcast-hybrid'}, ...
    'label',{'Causal unicast + standalone ACK','Broadcast DATA only', ...
    'Broadcast + standalone ACK','Broadcast + piggyback ACK', ...
    'Full Causal-Broadcast'}, ...
    'method',{'causal-unicast','state-event','causal-broadcast', ...
    'causal-broadcast','causal-broadcast'}, ...
    'feedbackMode',{'standalone','none','standalone','piggyback','hybrid'});

R.oodPoints = struct( ...
    'id',{'n10-ring2','n20-ring2','n10-sparse4','background030', ...
    'hidden-terminal','reverse-asymmetric','estimator-c3','aloha-p020'}, ...
    'label',{'N10 ring2','N20 ring2','N10 sparse4','30% background busy', ...
    'hidden terminals','reverse-asymmetric ACK','C3 estimator','ALOHA p=0.2'});

R.oodMethods = struct( ...
    'id',{'periodic-p10','periodic-p20','state-default','belief-default', ...
    'proposed-hybrid','proposed-piggyback'}, ...
    'label',{'Periodic-P10','Periodic-P20','State-event default', ...
    'Delayed-ACK belief default','Causal-Broadcast hybrid', ...
    'Causal-Broadcast piggyback'}, ...
    'method',{'periodic','periodic','state-event','delayed-ack-belief', ...
    'causal-broadcast','causal-broadcast'}, ...
    'periodHz',{10,20,NaN,NaN,NaN,NaN}, ...
    'feedbackMode',{'none','none','none','hybrid','hybrid','piggyback'});

R.primaryContrasts = { ...
    'Clean: proposed default minus Periodic-P10'; ...
    'Stressed: proposed default minus Periodic-P10'; ...
    'Stressed: proposed default minus delayed-belief default'; ...
    'Moderate: hybrid broadcast minus causal unicast'; ...
    'Moderate: piggyback-only minus hybrid broadcast'};

nSeed = numel(R.seeds);
R.expected.primaryFrontierRuns = nSeed*numel(R.scenarios)* ...
    numel(R.frontiers)*5;
R.expected.primaryMechanismRuns = nSeed*numel(R.scenarios)* ...
    numel(R.mechanisms);
R.expected.primaryRuns = R.expected.primaryFrontierRuns + ...
    R.expected.primaryMechanismRuns;
R.expected.oodRuns = nSeed*numel(R.oodPoints)*numel(R.oodMethods);
R.expected.totalRuns = R.expected.primaryRuns+R.expected.oodRuns;

end
