function R=exp14cRegistry()
%EXP14CREGISTRY Fixed development matrix for post-holdout MAC-aware v2.

R.version='EXP14C-DEVELOPMENT-v1';
R.seeds=(16016001:16016008)';
R.cells=struct( ...
    'id',{'n5-csma','n5-aloha','n5-background030','n5-hidden', ...
    'n10-ring2','n20-ring2'}, ...
    'label',{'N5 CSMA','N5 ALOHA','N5 30% background', ...
    'N5 hidden terminals','N10 ring2','N20 ring2'});
R.arms=struct( ...
    'id',{'frozen-hybrid','frozen-piggyback','adaptive-only', ...
    'access-only','guarded-adaptive','full-v2'}, ...
    'label',{'Frozen hybrid','Frozen piggyback','Adaptive ACK only', ...
    'Access scaling only','Adaptive ACK + guard','Full MAC-aware v2'});
R.expectedRuns=numel(R.seeds)*numel(R.cells)*numel(R.arms);
R.confirmatoryClaimPermitted=false;
R.selectedCandidate='full-v2';

end
