function R=exp14eRegistry()
%EXP14EREGISTRY Frozen 100-seed selected-candidate holdout.

R.version='EXP14E-PREREGISTERED-HOLDOUT-v1';
R.frozenDate='2026-08-30';
R.seedStatus='unopened when this registry was written';
R.seeds=(14015001:14015100)';
R.bootstrapReplicates=10000;
R.bootstrapSeed=14151515;
R.familywiseAlpha=0.05;
R.primaryMetrics={'RMSE','OFFERED_UTIL'};
R.primaryCells={'n5-csma','n10-ring2','n20-ring2'};
R.boundaryCells={'n5-aloha'};
R.candidate='selected-adaptive-scaled';
R.primaryComparator='access-only';
R.cells=struct( ...
    'id',{'n5-csma','n10-ring2','n20-ring2','n5-aloha'}, ...
    'label',{'N5 CSMA','N10 ring2','N20 ring2','N5 ALOHA'}, ...
    'role',{'primary','primary','primary','boundary'});
R.arms=struct( ...
    'id',{'selected-adaptive-scaled','access-only','historical-hybrid', ...
    'piggyback-scaled','state-scaled','belief-scaled','periodic-p10-scaled'}, ...
    'label',{'Selected adaptive + scaled','Access-only hybrid', ...
    'Historical hybrid p=0.2','Piggyback-only + scaled', ...
    'State-event + scaled','Delayed-belief + scaled','Periodic-P10 + scaled'}, ...
    'scaledAccess',{true,true,false,true,true,true,true}, ...
    'historicalReference',{false,false,true,false,false,false,false});
R.expectedRuns=numel(R.seeds)*numel(R.cells)*numel(R.arms);
R.confirmatoryClaimPermitted=true;
R.universalMacClaimPermitted=false;

end
