function R=exp18a4Registry()
%EXP18A4REGISTRY Development-only capacity-gated fixed-route selector.

A2=exp18a2Registry();
R=A2;
R.version='EXP18A4-CAPACITY-GATED-SELECTOR-DEVELOPMENT-v1';
R.stage='development-amendment-4';
R.arm=struct('id','capacity-gated-selector', ...
    'label','Capacity-gated fixed feedback route', ...
    'accessDesign','frame-aware','ackDesign','capacity-gated-mac');
R.aliasFields={'RMSE','MINSEP','SAFEFAIL','DIVERGED','CONTROL_EFFORT', ...
    'MEAN_TRUE_AOI','MEAN_EST_AOI','DATA_GENERATED','DATA_ATTEMPTED', ...
    'DATA_RECIPIENT_SUCCESS','COLLISION_FRAMES','QUEUE_DROPS', ...
    'OFFERED_UTIL','DATA_AIRTIME','ACK_AIRTIME','ACK_STANDALONE', ...
    'RECIPIENT_GOODPUT_HZ'};
R.requireExactAlias=true;

end
