function row=exp23pCoherencePacketEmptyRow()
%EXP23PCOHERENCEPACKETEMPTYROW Stable coherence packet row.

row=exp23hCumulativeReceiptEmptyRow();
fields={'geometryIndex','networkIndex','BASE_GEOMETRY_HASH', ...
    'DATA_NEIGHBOR_GRAPH_HASH','MANAGEMENT_GRAPH_HASH', ...
    'SELECTOR_HASH_EXACT','SELECTED_HORIZON_SEC', ...
    'SELECTED_HORIZON_INDEX','SELECTED_CONFLICT_EDGES', ...
    'SELECTED_HIDDEN_EDGES','COHERENCE_ENABLED', ...
    'COHERENCE_ADMISSIBLE','COHERENCE_HORIZON_FRAMES', ...
    'RENEWAL_PERIOD_FRAMES','LEASE_FRAMES','CLAIM_PACKET_BYTES', ...
    'CERTIFICATE_HEADER_BYTES','CERTIFICATE_ENTRY_BYTES', ...
    'REVOKE_PACKET_BYTES','MAX_RESPONSE_PACKET_BYTES', ...
    'PACKET_MTU_VIOLATIONS','BLACKOUT_APPLIED','SELF_REVOCATIONS', ...
    'REVOKE_ATTEMPTS','REVOKE_BYTES'};
for k=1:numel(fields), row.(fields{k})=NaN; end
row.geometryCondition='';
row.networkCondition='';
row.bindingReason='';

end
