function row=exp23afOnlineClosureEmptyRow()
%EXP23AFONLINECLOSUREEMPTYROW Stable online closure trajectory schema.

names={'seed','traceHash','decisionStateHash','finalDecisionStateHash', ...
    'decisionStateMaxDifference','geometryHash','selectorHash', ...
    'kernelTraceHash','kernelStateHash','kernelVersionHash','scheduleHash', ...
    'prefixScheduleHash','probePrefixScheduleHash','prefixStateExact', ...
    'graphAdmissible','changedSenderEdges','nonincidentSenderEdges', ...
    'affectedCount','changedSlotCount','candidateProper', ...
    'prepareBytes','maxResponseBytes','protectedSlotFree', ...
    'barrierClosed','motionAuthorized','graphActivationFrame', ...
    'commitReady','allReactivated','reactivatedCount', ...
    'finalSuppressedCount','prepareBudgetExhausted', ...
    'commitBudgetExhausted','motionStartSec','motionLatencySec', ...
    'motionGateExact','capsuleMaximumRatio','capsuleBoundSatisfied', ...
    'criticalCapsuleMaximumRatio','criticalCapsuleBoundSatisfied', ...
    'criticalCapsulePairChecks','criticalRadialMaximumRatio', ...
    'criticalRadialBoundSatisfied','minimumOmittedEdgeMargin', ...
    'radialConstructionPremise','radialTheoremCertified', ...
    'reliabilityCertificateHash','transactionHorizonFeasible', ...
    'transactionFailureUpperBound','completionProbabilityLowerBound', ...
    'prepareFailureUpperBound','evidenceFailureUpperBound', ...
    'responseFailureUpperBound','commitFailureUpperBound', ...
    'kernelActualSubsetOld','kernelActualSubsetUnion', ...
    'kernelFinalColoringProper','prematureActivationFrames', ...
    'controlAttemptBoundRatio','controlByteBoundRatio', ...
    'prepareAttempts','quietAttempts','claimAttempts', ...
    'responseAttempts','commitAttempts', ...
    'maxCommandPairDeviation','maxLeaderPairDeviation', ...
    'maxOtherPairDeviation', ...
    'maxCommandPairRadialContraction', ...
    'maxLeaderPairRadialContraction','maxOtherPairRadialContraction', ...
    'actualPhysicalSubset','actualSenderSubset', ...
    'actualSubsetCheckSamples','emergencyEnabled', ...
    'emergencyParallelMode','emergencyMappingExact', ...
    'emergencySuppressedDemand','emergencyOpportunities', ...
    'emergencyMinimumNodeOpportunities', ...
    'emergencyMaximumNodeOpportunities','emergencyRecipientSuccess', ...
    'emergencyRecipientErasure','emergencyRecipientCollision', ...
    'kernelCollisionFrames','expectedCollisionRecipients', ...
    'observedCollisionFrames','dataOutcomeMismatches', ...
    'dataSkippedNoQueue','crossPlaneOverlaps','expectedDataSuccess', ...
    'observedDataSuccess','expectedDataErasure','observedDataErasure', ...
    'controlAttempts','expectedControlAttempts','controlBytes', ...
    'observedControlBytes','expectedControlBytes', ...
    'controlAirtime','expectedControlAirtime','clockConflictFree', ...
    'clockResidual','futureRandomReads','receiverTruthReads', ...
    'RMSE','MISSION_RMSE','MINSEP','SAFEFAIL','DIVERGED', ...
    'DATA_AIRTIME','MANAGEMENT_AIRTIME','TOTAL_COST'};
row=struct('arm','','kind','','fault','');
for k=1:numel(names), row.(names{k})=NaN; end

end
