function row=exp21dDstrEmptyRow()
%EXP21DDSTREMPTYROW Stable schema for D-STR kernel outcomes.

row=struct( ...
    'seed',0,'N',0,'condition','','conditionLabel','','scope','', ...
    'topology','','maxFrames',0,'dataErasureProbability',NaN, ...
    'managementErasureProbability',NaN,'churnEnabled',0, ...
    'firstResolutionFrame',NaN,'firstConvergenceFrame',NaN, ...
    'recoveryFrame',NaN,'finalAllResolved',0,'finalCollisionFree',0, ...
    'finalFrameAgreement',0,'finalConverged',0,'finalDataSlots',NaN, ...
    'finalResolvedNodes',NaN,'finalAssignedNodes',NaN, ...
    'maxFrameDisagreement',NaN,'maxAssignedSlot',NaN, ...
    'conflictFrameFraction',NaN,'falseResolvedNodeFrames',NaN, ...
    'dataAttempts',NaN,'dataRecipientAttempts',NaN, ...
    'dataRecipientSuccess',NaN,'dataRecipientErasure',NaN, ...
    'dataRecipientCollision',NaN,'dataCollisionFrames',NaN, ...
    'managementAttempts',NaN,'managementRecipientAttempts',NaN, ...
    'managementRecipientSuccess',NaN, ...
    'managementRecipientErasure',NaN, ...
    'managementRecipientCollision',NaN, ...
    'managementCollisionSlots',NaN,'growRequests',NaN, ...
    'growNacks',NaN,'growthEvents',NaN,'shrinkRequests',NaN, ...
    'shrinkObjects',NaN,'shrinkNacks',NaN,'shrinkEvents',NaN, ...
    'elapsedSec',NaN,'offeredAirtimeSec',NaN,'busyAirtimeSec',NaN, ...
    'offeredUtilization',NaN,'channelUtilization',NaN, ...
    'accountingCloses',0,'deliveryWitnessValid',0, ...
    'futureRandomReads',NaN,'receiverTruthDecisionReads',NaN, ...
    'traceHash',NaN,'configHash',NaN,'realizationHash',NaN);

end
