function row=exp23arRoutedPlantClosedLoopEmptyRow()
%EXP23ARROUTEDPLANTCLOSEDLOOPEMPTYROW Stable routed-plant row schema.

row=struct('seed',0,'arm',"",'kind',"",'fault',"", ...
    'emergencyEnabled',0,'sharedTraceHash',NaN,'routeTraceHash',NaN, ...
    'decisionStateHash',NaN,'finalDecisionStateHash',NaN, ...
    'decisionStateMaxDifference',NaN,'prefixScheduleHash',NaN, ...
    'probePrefixScheduleHash',NaN,'prefixStateExact',0, ...
    'geometryHash',NaN,'selectorHash',NaN,'graphAdmissible',0, ...
    'changedSenderEdges',0,'nonincidentSenderEdges',0, ...
    'affectedCount',0,'changedSlotCount',0,'candidateProper',0, ...
    'barrierClosed',0,'motionAuthorized',0,'commitReady',0, ...
    'allAffectedReactivated',0,'reactivatedCount',0, ...
    'finalSuppressedCount',0,'prepareBudgetExhausted',0, ...
    'commitBudgetExhausted',0,'graphActivationFrame',NaN, ...
    'motionStartSec',NaN,'motionLatencySec',NaN,'motionGateExact',0, ...
    'kernelStateHash',NaN,'kernelVersionHash',NaN, ...
    'continuousVersionHash',NaN,'missionVersionHash',NaN, ...
    'physicalControlAttempts',0,'expectedControlAttempts',0, ...
    'observedControlAttempts',0,'physicalControlBytes',0, ...
    'expectedControlBytes',0,'observedControlBytes',0, ...
    'expectedControlAirtime',0,'observedControlAirtime',0, ...
    'integerManagementAccountingExact',0,'routeCollisionRecipients',0, ...
    'crossPacketStateWrites',0,'forbiddenReads',0, ...
    'scheduledCollisionFrames',0,'prematureActivationFrames',0, ...
    'transactionDurationSec',NaN,'transactionFailureUpperBound',NaN, ...
    'completionProbabilityLowerBound',NaN, ...
    'transactionMissionEmbeddingExact',0,'controlDataNonOverlap',0, ...
    'clockConflictFree',0,'clockResidual',NaN, ...
    'dataOutcomeMismatches',0,'dataSkippedNoQueue',0, ...
    'crossPlaneOverlaps',0,'expectedDataSuccess',0, ...
    'observedDataSuccess',0,'expectedDataErasure',0, ...
    'observedDataErasure',0,'expectedDataCollision',0, ...
    'observedCollisionFrames',0,'emergencyParallelMode',0, ...
    'emergencyMappingExact',0,'emergencySuppressedDemand',0, ...
    'emergencyOpportunities',0,'emergencyMinimumNodeOpportunities',NaN, ...
    'emergencyMaximumInterOpportunitySec',NaN, ...
    'transactionMaximumFrameDurationSec',NaN, ...
    'radialConstructionPremise',NaN, ...
    'radialTheoremCertified',NaN,'actualPhysicalSubset',NaN, ...
    'actualSenderSubset',NaN,'criticalRadialMaximumRatio',NaN, ...
    'minimumOmittedEdgeMargin',NaN,'RMSE',NaN,'MISSION_RMSE',NaN, ...
    'MINSEP',NaN,'SAFEFAIL',NaN,'DIVERGED',NaN, ...
    'DATA_AIRTIME',NaN,'MANAGEMENT_AIRTIME',NaN,'TOTAL_COST',NaN);

end
