function row=exp21bTimingEmptyRow()
%EXP21BTIMINGEMPTYROW Stable schema for timing-model validity results.

row=struct( ...
    'seed',0,'N',0,'syncPeriodSec',NaN,'guardFactor',NaN, ...
    'maxOffsetSec',NaN,'maxDriftPpm',NaN,'safeGuardSec',NaN, ...
    'guardTimeSec',NaN,'dataAirtimeSec',NaN, ...
    'slotDurationSec',NaN,'frameDurationSec',NaN, ...
    'transmissions',NaN,'collisionFrames',NaN, ...
    'temporalOverlapPairs',NaN,'offeredAirtimeSec',NaN, ...
    'busyTimeSec',NaN,'offeredUtilization',NaN, ...
    'channelUtilization',NaN,'maxClockEquationResidual',NaN, ...
    'collisionWitnessValid',NaN,'guardAtOrAboveBound',NaN, ...
    'clockDrawHash',NaN,'configHash',NaN,'realizationHash',NaN);

end
