function R=exp23wFastReactivationHoldoutRegistry()
%EXP23WFASTREACTIVATIONHOLDOUTREGISTRY Frozen fixed-graph confirmation.

U=exp23uDynamicClosedLoopEnvelopeRegistry();
R=U;
R.version='EXP23W-FAST-REACTIVATION-FIXED-GRAPH-HOLDOUT-v1';
R.frozenDate='2026-09-04';
R.stage='fast-reactivation-fixed-graph-confirmatory-holdout';
R.studyFamilyLabel='EXP23W fast-reactivation holdout';
R.parentDevelopmentRun='2026-09-04_222905';
R.parentDevelopmentStatus='FAST_REACTIVATION_DEVELOPMENT_FEASIBLE';
R.seedStatus='unopened when registry was written';
R.priorSeedUpperBound=16082060;
R.seeds=(16083001:16083100)';
R.developmentTestSeed=16082001;
R.arms=struct( ...
    'id',{'periodic-exp23d-lower','coherence-static-target', ...
        'conservative-early-delivered','fast-early-delivered', ...
        'fast-early-revoke-blackout','conservative-late-delivered', ...
        'fast-late-delivered','fast-early-response-blackout'}, ...
    'label',{'Periodic static TDMA / EXP23D lower-cost boundary', ...
        'Coherence ELCS-W / no revocation', ...
        'Conservative old-fence / event 3 s', ...
        'Witness-confirmed reactivation / event 3 s', ...
        'Witness-confirmed / event 3 s / REVOKE blackout', ...
        'Conservative old-fence / event 8 s', ...
        'Witness-confirmed reactivation / event 8 s', ...
        'Witness-confirmed / event 3 s / RESPONSE blackout'}, ...
    'family',{'periodic-static','candidate-elcs-w','candidate-elcs-w', ...
        'candidate-elcs-w','candidate-elcs-w','candidate-elcs-w', ...
        'candidate-elcs-w','candidate-elcs-w'}, ...
    'kind',{'periodic-frontier','coherence-static-target', ...
        'dynamic-early-delivered','fast-early-delivered', ...
        'fast-early-revoke-blackout','dynamic-late-delivered', ...
        'fast-late-delivered','fast-early-response-blackout'}, ...
    'clockEnabled',{false,true,true,true,true,true,true,true}, ...
    'dynamicEnabled',{false,false,true,true,true,true,true,true}, ...
    'eventTimeSec',{NaN,NaN,3,3,3,8,8,3}, ...
    'revokeBlackout',{false,false,false,false,true,false,false,false}, ...
    'responseBlackout',{false,false,false,false,false,false,false,true}, ...
    'fastReactivation',{false,false,false,true,true,false,true,true});
R.periodicArm=R.arms(1).id;
R.staticArm=R.arms(2).id;
R.oldEarlyArm=R.arms(3).id;
R.fastEarlyArm=R.arms(4).id;
R.fastRevokeBlackoutArm=R.arms(5).id;
R.oldLateArm=R.arms(6).id;
R.fastLateArm=R.arms(7).id;
R.fastResponseBlackoutArm=R.arms(8).id;
R.fastArms={R.fastEarlyArm,R.fastRevokeBlackoutArm, ...
    R.fastLateArm,R.fastResponseBlackoutArm};
R.familywiseAlpha=0.05;
R.primaryFamilySize=6;
R.staticRmseNoninferiorityMargin=0.01;
R.oldFenceCostPenaltyMargin=0.05;
R.bootstrapReplicates=10000;
R.bootstrapSeedBase=16083900;
R.epsilonRmse=0.01;
R.requiredCostImprovement=0.01;
R.requiredValidationContracts=21;
R.confirmatory=true;
R.freshSeedEvidence=true;
R.policyOptimizationAllowed=false;
R.broadRobustnessClaimPermitted=false;
R.confirmedFixedGraphPromotionPermitted=true;
R.submissionClaimPermitted=false;
R.expectedRuns=numel(R.seeds)*numel(R.arms);

end
