function row=exp21aEmptyRow()
%EXP21AEMPTYROW Stable persisted schema for scheduling reality check.

row=exp20aFormationEmptyRow();
row.cellRole='';
row.controlReach='';
row.DISTRIBUTED_FLAG=NaN;
row.IDEAL_FLAG=NaN;
row.EXP21_TRACE_HASH_EXACT=NaN;
row.RESERVATION_EPOCHS=NaN;
row.CONTROL_FRAMES=NaN;
row.CONTROL_REQUEST_FRAMES=NaN;
row.CONTROL_RESPONSE_FRAMES=NaN;
row.CONTROL_COMMIT_FRAMES=NaN;
row.CONTROL_RECIPIENT_ATTEMPTS=NaN;
row.CONTROL_RECIPIENT_SUCCESS=NaN;
row.CONTROL_RECIPIENT_LOSS=NaN;
row.CONTROL_ACCOUNTING_CLOSE=NaN;
row.CONTROL_AIRTIME=NaN;
row.CONTROL_OVERHEAD_FRACTION=NaN;
row.RESERVATION_NACKS=NaN;
row.RESERVATION_MIGRATIONS=NaN;
row.RESERVATION_SCHEDULE_CHANGES=NaN;
row.SCHEDULE_CONFLICT_FRACTION=NaN;
row.FIRST_CONVERGENCE_SEC=NaN;
row.CONVERGED_BY_2SEC=NaN;
row.CHURN_APPLIED=NaN;
row.CHURN_RECOVERY_SEC=NaN;
row.RECOVERED_BY_2SEC=NaN;
row.FINAL_ASSIGNED_NODES=NaN;
row.FINAL_FULL_UNIQUE=NaN;
row.MAX_ABS_CLOCK_OFFSET_SEC=NaN;
row.MAX_ABS_CLOCK_DRIFT_PPM=NaN;
row.LOCAL_SCHEDULE_ONLY=NaN;

end
