function R=exp21cRegistry()
%EXP21CREGISTRY Frozen closed-loop timing-integration comparison.

R.version='EXP21C-CLOSED-LOOP-TIMING-INTEGRATION-v1';
R.frozenDate='2026-09-01';
R.stage='development-model-integration';
R.policyOptimizationAllowed=false;
R.submissionClaimPermitted=false;
R.seeds=(16032001:16032030)';
R.maxOffsetSec=0.25e-3;
R.maxDriftPpm=40;
R.syncPeriodSec=0.5;
B=continuousTdmaGuardBound( ...
    R.maxOffsetSec,R.maxDriftPpm,R.syncPeriodSec);
R.safeGuardSec=B.safeGuardSec;
R.periodicRateHz=1/0.12;
R.cells=struct( ...
    'id',{'n5-stressed','n10-moderate'}, ...
    'label',{'N5 Stressed','N10 Moderate'}, ...
    'exp21aCell',{'n5-stressed-nominal','n10-moderate-nominal'});
R.arms=struct( ...
    'id',{'ideal-tdma-p8p333','continuous-zero-clock', ...
        'continuous-clock-unguarded','continuous-clock-safe-guard'}, ...
    'label',{'Ideal TDMA 8.333 Hz','Continuous local TDMA zero clock', ...
        'Continuous local TDMA unguarded clock', ...
        'Continuous local TDMA safe guard'}, ...
    'kind',{'ideal-reference','integration-zero', ...
        'integration-witness','integration-safe'}, ...
    'schedulerMode',{'round-robin','continuous-local-static-tdma', ...
        'continuous-local-static-tdma','continuous-local-static-tdma'}, ...
    'clockEnabled',{false,false,true,true}, ...
    'guardFactor',{NaN,0,0,1});
R.idealArm='ideal-tdma-p8p333';
R.zeroArm='continuous-zero-clock';
R.witnessArm='continuous-clock-unguarded';
R.safeArm='continuous-clock-safe-guard';
R.maxZeroRelativeRmseGap=0.10;
R.maxZeroAbsoluteUtilGap=0.05;
R.expectedRuns=numel(R.seeds)*numel(R.cells)*numel(R.arms);

end
