function row=exp21dClosedLoopEmptyRow()
%EXP21DCLOSEDLOOPEMPTYROW Stable D-STR integration output schema.

row=exp21cEmptyRow();
row.DSTR_NATIVE_FLAG=NaN;
row.DSTR_WARM_FLAG=NaN;
row.DSTR_SCHEDULE_HASH_EXACT=NaN;
row.DSTR_KERNEL_TRACE_HASH_EXACT=NaN;
row.DSTR_KERNEL_CONFIG_HASH=NaN;
row.DSTR_SCHEDULED_DATA_ATTEMPTS=NaN;
row.DSTR_EXPECTED_DATA_COLLISION_FRAMES=NaN;
row.DSTR_EXPECTED_DATA_RECIPIENT_SUCCESS=NaN;
row.DSTR_EXPECTED_DATA_RECIPIENT_ERASURE=NaN;
row.DSTR_EXPECTED_DATA_RECIPIENT_COLLISION=NaN;
row.DSTR_OBSERVED_DATA_RECIPIENT_SUCCESS=NaN;
row.DSTR_OBSERVED_DATA_RECIPIENT_ERASURE=NaN;
row.DSTR_OBSERVED_DATA_RECIPIENT_COLLISION=NaN;
row.DSTR_DATA_OUTCOME_MISMATCHES=NaN;
row.DSTR_DATA_OPPORTUNITIES=NaN;
row.DSTR_DATA_ATTEMPTS=NaN;
row.DSTR_DATA_SKIPPED_NO_QUEUE=NaN;
row.DSTR_DATA_COLLISION_WITNESS_MATCH=NaN;
row.DSTR_MANAGEMENT_BUSY_SLOTS=NaN;
row.DSTR_MANAGEMENT_ATTEMPTS=NaN;
row.DSTR_MANAGEMENT_AIRTIME=NaN;
row.DSTR_MANAGEMENT_RECIPIENT_ATTEMPTS=NaN;
row.DSTR_MANAGEMENT_RECIPIENT_SUCCESS=NaN;
row.DSTR_MANAGEMENT_RECIPIENT_ERASURE=NaN;
row.DSTR_MANAGEMENT_RECIPIENT_COLLISION=NaN;
row.DSTR_MANAGEMENT_COLLISION_SLOTS=NaN;
row.DSTR_MANAGEMENT_ACCOUNTING_CLOSE=NaN;
row.DSTR_CROSS_PLANE_OVERLAPS=NaN;
row.DSTR_FIRST_CONVERGENCE_SEC=NaN;
row.DSTR_KERNEL_FIRST_RESOLUTION_FRAME=NaN;
row.DSTR_KERNEL_FIRST_CONVERGENCE_FRAME=NaN;
row.DSTR_KERNEL_FINAL_RESOLVED=NaN;
row.DSTR_KERNEL_FINAL_COLLISION_FREE=NaN;
row.DSTR_KERNEL_FINAL_FRAME_AGREEMENT=NaN;
row.DSTR_KERNEL_FINAL_DATA_SLOTS=NaN;
row.DSTR_KERNEL_MAX_FRAME_DISAGREEMENT=NaN;
row.DSTR_KERNEL_FALSE_RESOLVED_NODE_FRAMES=NaN;
row.DSTR_KERNEL_RECOVERY_FRAME=NaN;
row.DSTR_LAST_DATA_TIME=NaN;
row.DSTR_LAST_CONTROL_TIME=NaN;

end
