function row=exp23aeClosureCommonPhyEmptyRow()
%EXP23AECLOSURECOMMONPHYEMPTYROW Stable common-PHY result schema.

names={'seed','N','clockImpaired','selectorHash','traceHash', ...
    'kernelStateHash','nativeScheduleHash','scheduleHash','logicalHash', ...
    'selectorAdmissible','physicalChangeCount','senderChangeCount', ...
    'nonincidentSenderChangeCount','affectedCount','changedSlotCount', ...
    'candidateProper','actualSubsetUnion','barrierClosed', ...
    'motionAuthorized','commitReady','allReactivated', ...
    'reactivatedCount','finalSuppressedCount','prepareBudgetExhausted', ...
    'commitBudgetExhausted','dataStateSlotExact', ...
    'kernelControlAttempts','physicalControlAttempts', ...
    'kernelControlBytes','physicalControlBytes','kernelControlAirtime', ...
    'physicalControlAirtime','kernelRecipientAttempts', ...
    'physicalRecipientAttempts','kernelRecipientSuccess', ...
    'physicalRecipientSuccess','kernelRecipientErasure', ...
    'physicalRecipientErasure','prepareMapped','quietMapped', ...
    'claimMapped','proofMapped','responseMapped','commitMapped', ...
    'revokeMapped','kernelPrepareAttempts','kernelQuietAttempts', ...
    'kernelClaimAttempts','kernelProofAttempts', ...
    'kernelResponseAttempts','kernelCommitAttempts', ...
    'kernelRevokeAttempts','piggybackRevoke','maxControlPacketBytes', ...
    'nativeDataAttempts','physicalDataAttempts', ...
    'dataRecipientAttempts','dataRecipientSuccess', ...
    'dataRecipientCollision','dataRecipientPartitionExact', ...
    'kernelCollisionFrames','physicalCollisionAttempts', ...
    'physicalCollisionFrames','clockTimingConflictFree', ...
    'clockEquationResidual','clockMinIntergroupGap', ...
    'clockMaxIntragroupSkew','nativeControlAttempts', ...
    'physicalFrameDuration','horizonSec','attemptBoundRatio', ...
    'byteBoundRatio','futureRandomReads','receiverTruthReads'};
row=struct('condition','','clockArm','');
for k=1:numel(names), row.(names{k})=NaN; end

end
