function row=exp23adClosureKernelEmptyRow()
%EXP23ADCLOSUREKERNELEMPTYROW Stable kernel result schema.

row=struct('seed',NaN,'N',NaN,'condition','', ...
    'traceHash',NaN,'selectorHash',NaN,'stateHash',NaN, ...
    'physicalChangeCount',NaN,'senderChangeCount',NaN, ...
    'nonincidentSenderChangeCount',NaN,'initiatorIsChangedEndpoint',NaN, ...
    'affectedCount',NaN,'affectedHash',NaN,'changedSlotCount',NaN, ...
    'outsideUnchanged',NaN,'candidateProper',NaN,'prepareBytes',NaN, ...
    'maxResponseBytes',NaN,'barrierClosed',NaN,'barrierFrame',NaN, ...
    'motionAuthorized',NaN,'activationFrame',NaN,'commitReady',NaN, ...
    'allReactivated',NaN,'reactivatedCount',NaN, ...
    'finalSuppressedCount',NaN,'prepareBudgetExhausted',NaN, ...
    'commitBudgetExhausted',NaN,'edgeReceipts',NaN, ...
    'requiredEdgeReceipts',NaN,'actualSubsetUnion',NaN, ...
    'collisionFrames',NaN,'collisionEdges',NaN, ...
    'controlAttempts',NaN,'controlBytes',NaN,'controlAirtime',NaN, ...
    'attemptBound',NaN,'byteBound',NaN,'attemptBoundRatio',NaN, ...
    'byteBoundRatio',NaN,'recipientAttempts',NaN, ...
    'recipientSuccess',NaN,'recipientErasure',NaN, ...
    'prepareAttempts',NaN,'quietAttempts',NaN,'claimAttempts',NaN, ...
    'proofAttempts',NaN,'responseAttempts',NaN,'commitAttempts',NaN, ...
    'revokeAttempts',NaN,'futureRandomReads',NaN, ...
    'receiverTruthReads',NaN);

end
