function R=exp23uDynamicClosedLoopEnvelopeRegistry()
%EXP23UDYNAMICCLOSEDLOOPENVELOPEREGISTRY Frozen operating-envelope matrix.

T=exp23tStaticCoherenceClosedLoopRegistry();
R=T;
R.version='EXP23U-DYNAMIC-CLOSED-LOOP-ENVELOPE-v1';
R.frozenDate='2026-09-04';
R.stage='dynamic-common-phy-closed-loop-operating-envelope';
R.parentStaticRun='2026-09-04_180732';
R.parentStaticStatus='STATIC_COHERENCE_COMMON_PHY_SURVIVES';
R.parentDynamicKernelRun='2026-09-04_180028';
R.parentDynamicKernelStatus='DYNAMIC_COHERENCE_REVOCATION_KERNEL_VALID';
R.seeds=(16082001:16082060)';
R.revokeNode=5;
R.reacquireEligibilityDelaySec=0.5;
R.arms=struct( ...
    'id',{'periodic-exp23d-lower','coherence-static-target', ...
        'dynamic-early-delivered','dynamic-early-revoke-blackout', ...
        'dynamic-late-delivered','dynamic-early-response-blackout'}, ...
    'label',{'Periodic static TDMA / EXP23D lower-cost boundary', ...
        'Coherence ELCS-W / no revocation', ...
        'Coherence ELCS-W / revoke at 3 s', ...
        'Coherence ELCS-W / revoke at 3 s / REVOKE blackout', ...
        'Coherence ELCS-W / revoke at 8 s', ...
        'Coherence ELCS-W / revoke at 3 s / RESPONSE blackout'}, ...
    'family',{'periodic-static','candidate-elcs-w','candidate-elcs-w', ...
        'candidate-elcs-w','candidate-elcs-w','candidate-elcs-w'}, ...
    'kind',{'periodic-frontier','coherence-static-target', ...
        'dynamic-early-delivered','dynamic-early-revoke-blackout', ...
        'dynamic-late-delivered','dynamic-early-response-blackout'}, ...
    'clockEnabled',{false,true,true,true,true,true}, ...
    'dynamicEnabled',{false,false,true,true,true,true}, ...
    'eventTimeSec',{NaN,NaN,3,3,8,3}, ...
    'revokeBlackout',{false,false,false,true,false,false}, ...
    'responseBlackout',{false,false,false,false,false,true});
R.periodicArm=R.arms(1).id;
R.staticArm=R.arms(2).id;
R.earlyArm=R.arms(3).id;
R.revokeBlackoutArm=R.arms(4).id;
R.lateArm=R.arms(5).id;
R.responseBlackoutArm=R.arms(6).id;
R.bootstrapSeedBase=16082900;
R.requiredValidationContracts=21;
R.expectedRuns=numel(R.seeds)*numel(R.cells)* ...
    numel(R.conditions)*numel(R.arms);

end
