function row=exp23zLocalMigrationClosedLoopEmptyRow()
%EXP23ZLOCALMIGRATIONCLOSEDLOOPEMPTYROW Stable output schema.

row=struct('seed',NaN,'arm','','kind','','condition','', ...
    'dataLoss',NaN,'controlLoss',NaN,'traceHash',NaN, ...
    'geometryHash',NaN,'selectorHash',NaN,'scheduleHash',NaN, ...
    'kernelTraceHash',NaN,'kernelStateHash',NaN, ...
    'interferenceEventHash',NaN,'RMSE',NaN,'MINSEP',NaN, ...
    'SAFEFAIL',NaN,'DIVERGED',NaN,'TOTAL_COST',NaN, ...
    'DATA_AIRTIME',NaN,'MANAGEMENT_AIRTIME',NaN, ...
    'DATA_ATTEMPTS',NaN,'DATA_RECIPIENT_SUCCESS',NaN, ...
    'DATA_RECIPIENT_LOSS',NaN,'COLLISION_FRAMES',NaN, ...
    'BACKGROUND_COLLISION_FRAMES',NaN,'graphAdmissible',NaN, ...
    'graphLocalOnly',NaN,'graphAddedEdges',NaN, ...
    'graphRemovedEdges',NaN,'oldSlot',NaN,'newSlot',NaN, ...
    'eventFrame',NaN,'eligibleFrame',NaN,'reacquired',NaN, ...
    'firstReacquiredFrame',NaN,'finalSuppressed',NaN, ...
    'controlAttempts',NaN,'controlBytes',NaN, ...
    'controlAirtime',NaN,'expectedControlAttempts',NaN, ...
    'expectedControlAirtime',NaN,'expectedDataSuccess',NaN, ...
    'expectedDataErasure',NaN,'expectedDataCollision',NaN, ...
    'observedDataSuccess',NaN,'observedDataErasure',NaN, ...
    'observedDataCollision',NaN,'dataOutcomeMismatches',NaN, ...
    'dataSkippedNoQueue',NaN,'crossPlaneOverlaps',NaN, ...
    'clockConflictFree',NaN,'clockResidual',NaN, ...
    'futureRandomReads',NaN,'receiverTruthReads',NaN, ...
    'suppressionHash',NaN,'reacquisitionHash',NaN, ...
    'revokeBlackout',NaN,'responseBlackout',NaN, ...
    'geometryCoupledToPlant',NaN,'emergencyEnabled',NaN, ...
    'emergencySlot',NaN,'emergencyOpportunities',NaN, ...
    'emergencyExpectedSuccess',NaN,'emergencyExpectedErasure',NaN, ...
    'emergencyExpectedCollision',NaN,'claimBackoffEnabled',NaN, ...
    'claimDenseRetryFrames',NaN,'claimMaxBackoffFrames',NaN, ...
    'claimRetryAttemptLimit',NaN,'claimOpportunityCount',NaN, ...
    'claimScheduleHash',NaN,'claimAttempts',NaN, ...
    'lockProofAttempts',NaN,'responseAttempts',NaN, ...
    'retryBudgetExhausted',NaN,'retryEntryFailureBound',NaN, ...
    'retryUnionFailureBound',NaN);

end
