function finishExperiment(R)
%FINISHEXPERIMENT Close out a run started by startExperiment.
%
% Writes meta.json, stops the diary, updates LATEST.txt and appends one row
% to results/INDEX.md.

elapsed = toc(R.t0);

R.meta.finishedAt  = char(datetime('now','Format','yyyy-MM-dd HH:mm:ss'));
R.meta.elapsedSec  = elapsed;
R.meta.elapsedText = localDuration(elapsed);


%% ============================================================
% Inventory of what was actually produced
% ============================================================

figFiles = dir(fullfile(R.figDir,'*.png'));

R.meta.figureCount = numel(figFiles);

R.meta.hasWorkspace = ...
    exist(fullfile(R.dir,'workspace.mat'),'file') == 2;

R.meta.hasTidy = ...
    exist(fullfile(R.dir,'tidy.csv'),'file') == 2;


%% ============================================================
% meta.json
% ============================================================

fid = fopen(fullfile(R.dir,'meta.json'),'w');

if fid > 0
    fprintf(fid,'%s\n', jsonencode(R.meta,'PrettyPrint',true));
    fclose(fid);
end


%% ============================================================
% Console summary
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('DONE : %s\n', R.name);
fprintf('TIME : %s\n', R.meta.elapsedText);
fprintf('FIGS : %d\n', R.meta.figureCount);
fprintf('DIR  : %s\n', R.dir);
fprintf('============================================================\n');

diary off;


%% ============================================================
% LATEST.txt
% ============================================================

fid = fopen(fullfile(R.expRoot,'LATEST.txt'),'w');

if fid > 0
    fprintf(fid,'%s\n', R.runId);
    fclose(fid);
end


%% ============================================================
% results/INDEX.md
% ============================================================

indexFile = fullfile(projectRoot(),'results','INDEX.md');

isNew = exist(indexFile,'file') ~= 2;

fid = fopen(indexFile,'a');

if fid > 0

    if isNew
        fprintf(fid,'# Experiment run log\n\n');
        fprintf(fid,'Auto-generated by `finishExperiment`. One row per run.\n\n');
        fprintf(fid,'| Run ID | Experiment | Elapsed | Figures | Workspace | Tidy CSV | MATLAB | Commit |\n');
        fprintf(fid,'|---|---|---|---|---|---|---|---|\n');
    end

    fprintf(fid,'| %s | %s | %s | %d | %s | %s | %s | %s |\n', ...
        R.runId, ...
        R.name, ...
        R.meta.elapsedText, ...
        R.meta.figureCount, ...
        localYesNo(R.meta.hasWorkspace), ...
        localYesNo(R.meta.hasTidy), ...
        R.meta.matlabRelease, ...
        localDash(R.meta.gitCommit));

    fclose(fid);

end

end


%% ============================================================
% LOCAL FUNCTIONS
% ============================================================

function s = localDuration(sec)

if sec < 60
    s = sprintf('%.1f s', sec);
elseif sec < 3600
    s = sprintf('%d m %02.0f s', floor(sec/60), mod(sec,60));
else
    s = sprintf('%d h %02.0f m', floor(sec/3600), mod(sec,3600)/60);
end

end


function s = localYesNo(tf)

if tf
    s = 'yes';
else
    s = '-';
end

end


function s = localDash(x)

if isempty(x)
    s = '-';
else
    s = x;
end

end
