function row=runExp21dDstrKernelCell(seedValue,N,condition,R,T)
%RUNEXP21DDSTRKERNELCELL Execute and flatten one frozen kernel cell.

[C,details]=applyExp21dDstrCondition(N,condition.id,R);
out=simulateDstrScheduling(C,T);
row=exp21dDstrEmptyRow();
row.seed=seedValue;
row.N=N;
row.condition=condition.id;
row.conditionLabel=condition.label;
row.scope=condition.scope;
row.topology=details.topology;
row.maxFrames=C.maxFrames;
row.dataErasureProbability=C.dataErasureProbability;
row.managementErasureProbability=C.managementErasureProbability;
row.churnEnabled=double(C.churnEnabled);
row.firstResolutionFrame=out.firstResolutionFrame;
row.firstConvergenceFrame=out.firstConvergenceFrame;
row.recoveryFrame=out.recoveryFrame;
row.finalAllResolved=double(out.finalAllResolved);
row.finalCollisionFree=double(out.finalCollisionFree);
row.finalFrameAgreement=double(out.finalFrameAgreement);
row.finalConverged=double(isfinite(out.firstConvergenceFrame) && ...
    out.frameLog(end).converged);
row.finalDataSlots=out.finalDataSlots;
row.finalResolvedNodes=nnz(out.state==2);
row.finalAssignedNodes=nnz(out.assignedSlot>0);
row.maxFrameDisagreement=out.maxFrameDisagreement;
row.maxAssignedSlot=out.maxAssignedSlot;
row.conflictFrameFraction=out.conflictFrameFraction;
row.falseResolvedNodeFrames=out.falseResolvedNodeFrames;
row.dataAttempts=out.dataAttempts;
row.dataRecipientAttempts=out.dataRecipientAttempts;
row.dataRecipientSuccess=out.dataRecipientSuccess;
row.dataRecipientErasure=out.dataRecipientErasure;
row.dataRecipientCollision=out.dataRecipientCollision;
row.dataCollisionFrames=out.dataCollisionFrames;
row.managementAttempts=out.managementAttempts;
row.managementRecipientAttempts=out.managementRecipientAttempts;
row.managementRecipientSuccess=out.managementRecipientSuccess;
row.managementRecipientErasure=out.managementRecipientErasure;
row.managementRecipientCollision=out.managementRecipientCollision;
row.managementCollisionSlots=out.managementCollisionSlots;
row.growRequests=out.growRequests;
row.growNacks=out.growNacks;
row.growthEvents=out.growthEvents;
row.shrinkRequests=out.shrinkRequests;
row.shrinkObjects=out.shrinkObjects;
row.shrinkNacks=out.shrinkNacks;
row.shrinkEvents=out.shrinkEvents;
row.elapsedSec=out.elapsedSec;
row.offeredAirtimeSec=out.offeredAirtimeSec;
row.busyAirtimeSec=out.busyAirtimeSec;
row.offeredUtilization=out.offeredUtilization;
row.channelUtilization=out.channelUtilization;
row.accountingCloses=double(out.accountingCloses);
row.deliveryWitnessValid=double(out.deliveryWitnessValid);
row.futureRandomReads=out.futureRandomReads;
row.receiverTruthDecisionReads=out.receiverTruthDecisionReads;
row.traceHash=out.traceHash;
row.configHash=out.configHash;
row.realizationHash=out.realizationHash;

end
