function pass = tcnsO1OracleContractPass(outputs,arms,taskArm)
%TCNSO1ORACLECONTRACTPASS Audit O1 privilege, threshold and accounting.

pass = true;
for q = 1:numel(outputs)
    if arms(taskArm(q)).kind~="centralized-state-oracle"
        continue;
    end
    out = outputs{q};
    if isempty(out) || ~isfield(out,'centralizedStateOracleActive')
        pass = false;
        continue;
    end
    action = out.oracleActions;
    threshold = arms(taskArm(q)).oracleLambda;
    pass = pass && out.centralizedStateOracleActive && ...
        strcmp(out.centralizedStateOracleLabel,'centralized_state_oracle') && ...
        out.onlineNonanticipative && ~out.usesFutureChannelOutcome && ...
        ~out.usesFutureDisturbance && ~out.usesFutureFormationChange && ...
        ~out.usesFutureTrajectory && out.ackCountLog(end)==0 && ...
        out.txCount==out.oracleSendCount && ...
        height(action)==out.oracleSendCount && ...
        all(action.predictedValue>threshold) && ...
        all(abs(action.predictedValue - ...
        (action.predictedCrossContribution - ...
         action.predictedIsolatedEnergy))<1e-12);
end

end
