function row = tcnsFrontierRow()
%TCNSFRONTIERROW Stable machine-readable schema for one frontier run.

row = struct('armId',"",'methodFamily',"",'method',"", ...
    'parameterName',"",'parameterValue',NaN,'period_s',NaN, ...
    'epsilonPosition_m',NaN,'retryInterval_s',NaN,'seed',NaN, ...
    'scenarioId',"",'scenario',"",'formationRMSE_m',NaN, ...
    'primaryFormationRMSE_m',NaN,'maxFormationError_m',NaN, ...
    'primaryMaxFormationError_m',NaN,'txCount',NaN,'ackCount',NaN, ...
    'dataRatePerChannel_Hz',NaN,'cost025PerChannel_Hz',NaN, ...
    'evaluationCost025PerChannel_Hz',NaN, ...
    'eventCost025PerChannel_Hz',NaN,'quietCost025PerChannel_Hz',NaN, ...
    'eventTrafficConcentration',NaN,'eventDurationFraction',NaN, ...
    'eventAllocationRatio',NaN,'broadcastRate_Hz',NaN, ...
    'maxEvaluationAcceleration_mps2',NaN,'saturationFraction',NaN, ...
    'diverged',false,'invariantViolations',NaN,'traceHashExact',NaN, ...
    'controlViolationRatio',NaN,'controlMaxNormalizedRisk',NaN, ...
    'runtime_s',NaN,'failed',false,'errorIdentifier',"",'errorMessage',"");

end
