function report=validateMeasuredSharedMediumTrace(trace,cfg)
%VALIDATEMEASUREDSHAREDMEDIUMTRACE Validate a built EXP15 measured trace.

if nargin~=2 || ~isstruct(trace) || ~isscalar(trace) || ...
        ~isstruct(cfg) || ~isscalar(cfg)
    error('measuredTrace:InvalidTrace', ...
        'trace and cfg must be scalar structs.');
end
required={'sourceMode','schemaVersion','sourceId','slotTime','K','N', ...
    'modelSignature','measurementHash','hashExact','channelStateHash', ...
    'accessU','lossU','ackLossU','measuredDataLossProbability', ...
    'measuredAckLossProbability','measuredBackgroundActive', ...
    'dataBadState','ackBadState','dataBadFraction','ackBadFraction'};
for k=1:numel(required)
    if ~isfield(trace,required{k})
        error('measuredTrace:MissingTraceField', ...
            'trace lacks required field %s.',required{k});
    end
end
if ~strcmp(char(string(trace.sourceMode)),'measured-probability-v1') || ...
        ~strcmp(char(string(trace.schemaVersion)), ...
        'MEASURED-SHARED-MEDIUM-v1')
    error('measuredTrace:UnsupportedTraceMode', ...
        'trace mode/schema is not supported.');
end
if isempty(strtrim(char(string(trace.sourceId))))
    error('measuredTrace:InvalidSourceId','trace.sourceId must be nonempty.');
end
mac=sharedMediumConfig(cfg); N=cfg.swarm.N;
minimumK=ceil(cfg.swarm.T/mac.slotTime)+2;
if ~isscalar(trace.K) || trace.K<minimumK || trace.K~=floor(trace.K) || ...
        trace.N~=N || abs(trace.slotTime-mac.slotTime)>1e-12
    error('measuredTrace:TraceDimensionMismatch', ...
        'trace K, N or slotTime does not match cfg.');
end
if trace.modelSignature~=sharedMediumChannelSignature(mac,N)
    error('measuredTrace:ModelSignatureMismatch', ...
        'trace modelSignature does not match cfg.');
end
probabilityFields={'measuredDataLossProbability', ...
    'measuredAckLossProbability'};
for k=1:numel(probabilityFields)
    x=trace.(probabilityFields{k});
    if ~isequal([size(x,1) size(x,2) size(x,3)],[trace.K N N]) || ...
            any(~isfinite(x(:)) | x(:)<0 | x(:)>1)
        error('measuredTrace:InvalidTraceProbability', ...
            '%s has invalid shape or values.',probabilityFields{k});
    end
end
drawFields={'lossU','ackLossU'};
for k=1:numel(drawFields)
    x=trace.(drawFields{k});
    if ~isequal([size(x,1) size(x,2) size(x,3)],[trace.K N N]) || ...
            any(~isfinite(x(:)) | x(:)<0 | x(:)>=1)
        error('measuredTrace:InvalidTraceDraw', ...
            '%s has invalid shape or values.',drawFields{k});
    end
end
if ~isequal(size(trace.accessU),[trace.K N]) || ...
        any(~isfinite(trace.accessU(:)) | trace.accessU(:)<0 | ...
        trace.accessU(:)>=1)
    error('measuredTrace:InvalidAccessDraw','accessU is invalid.');
end
if ~isequal(size(trace.measuredBackgroundActive),[trace.K 1]) || ...
        any(trace.measuredBackgroundActive(:)~=0 & ...
        trace.measuredBackgroundActive(:)~=1)
    error('measuredTrace:InvalidBackground', ...
        'measuredBackgroundActive must be K-by-1 binary.');
end
for field={'dataBadState','ackBadState'}
    x=trace.(field{1});
    if ~isequal([size(x,1) size(x,2) size(x,3)],[trace.K N N]) || ...
            any(x(:)~=0 & x(:)~=1)
        error('measuredTrace:InvalidTraceState', ...
            '%s must be K-by-N-by-N binary.',field{1});
    end
end
for n=1:N
    if any(trace.measuredDataLossProbability(:,n,n)~=0) || ...
            any(trace.measuredAckLossProbability(:,n,n)~=0) || ...
            any(trace.dataBadState(:,n,n)~=0) || ...
            any(trace.ackBadState(:,n,n)~=0)
        error('measuredTrace:NonzeroDiagonal', ...
            'self-link probability and state entries must be zero.');
    end
end
hashValues=[trace.accessU(:);trace.lossU(:);trace.ackLossU(:); ...
    double(trace.measuredBackgroundActive(:)); ...
    trace.measuredDataLossProbability(:); ...
    trace.measuredAckLossProbability(:);double(trace.dataBadState(:)); ...
    double(trace.ackBadState(:))];
if trace.hashExact~=realizationHash(hashValues)
    error('measuredTrace:HashMismatch','trace.hashExact is invalid.');
end
stateHash=realizationHash([trace.dataBadState(:);trace.ackBadState(:)]);
if trace.channelStateHash~=stateHash
    error('measuredTrace:StateHashMismatch', ...
        'trace.channelStateHash is invalid.');
end
report=struct('schemaVersion',char(string(trace.schemaVersion)), ...
    'sourceId',char(string(trace.sourceId)),'slots',trace.K,'N',trace.N, ...
    'measurementHash',trace.measurementHash,'hashExact',trace.hashExact, ...
    'channelStateHash',trace.channelStateHash,'valid',true);

end
